src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bundle__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate if this client has purchased Bundle</description>
        <label>Bundle</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bundle__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bundles</relationshipLabel>
        <relationshipName>Bundles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Allocated_Days__c</fullName>
        <label>Total Allocated Day(s)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Teacher</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Supply Cover</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Bundle_Job_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bundle__c</fullName>
        <label>Bundle</label>
        <referenceTo>Bundle__c</referenceTo>
        <relationshipName>Bundle_Job_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Bundle_Job_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vacancy Bundle</label>
    <nameField>
        <displayFormat>VB-{0000000}</displayFormat>
        <label>Vacancy Bundle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancy Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BundleJobJunctionTriggerTest.cls
@isTest(seeAlldata= false)
public class BundleJobJunctionTriggerTest {
    
    @isTest
    public static void test(){
        
        Account testAccount = new Account(Name = 'Test Account34687');
        insert testAccount;           
        
        TR1__Job__c testJob = RC_UtilityClass.insertJob();
        testJob.TR1__Account__c  = testAccount.Id;
        update testJob;                
        
        Bundle__c testBundle = new Bundle__c(Name = 'Test Bundle4521734',Account__c =testAccount.Id, Type__c  = 'Teacher',Total_Allocated_Days__c = 1,Invoice_Amount__c =60000);
        insert testBundle;                
        
        Bundle_Job_Junction__c testBundleJobJunction = new Bundle_Job_Junction__c(Bundle__c =testBundle.Id, Job__c = testJob.Id) ;
        insert testBundleJobJunction;
        
        testBundleJobJunction.Active__c  = true;
        update testBundleJobJunction;
        
    }
    
}