src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Closing_Report_Schedule__c.object
<CustomObject>
    <description>A schedule record is created for each day a Candidate is assigned to the Vacancy</description>
    <fields>
        <fullName>Closing_Report__c</fullName>
        <label>Closing Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TR1__Closing_Report__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report Schedule</label>
    <nameField>
        <displayFormat>CRS-{0000000}</displayFormat>
        <label>CRS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Assignment_Ended__c</fullName>
        <label>Assignment Ended</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Rate Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Booking_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Declared date – vacancy closed as agreed/won</inlineHelpText>
        <label>Booking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Candidate_Percentage__c</fullName>
        <label>Candidate Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Conversion_Date__c</fullName>
        <label>Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Generate_Timesheet__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Generate Timesheet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Percentage__c</fullName>
        <label>Job Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Marketing_Percentage__c</fullName>
        <label>Marketing Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Other2_Percentage__c</fullName>
        <label>Other2 Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Other_Percentage__c</fullName>
        <label>Other Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Rate_Change_Effective_Date__c</fullName>
        <label>Rate Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Receive_Timesheet_Email_Alerts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Receive Timesheet Email Alerts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__TalentRoverProperties__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>System Properties of Talent Rover</description>
    <fields>
        <fullName>TR1__Candidate_Status_When_Assignment_Ended__c</fullName>
        <description>Specify Picklist value when to Set Candidate Status when Assignment Ended on Closing Report</description>
        <label>Candidate Status When Assignment Ended</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TalentRover Properties</label>
</CustomObject>

src/classes/ClosingReportButtonsCtrl.cls
public with sharing class ClosingReportButtonsCtrl{
    public TR1__Closing_Report__c currentcr{get;set;}
    public TR1__Closing_Report__c newcr{get;set;}
    public Boolean isSuccess{get;set;}
    private Set<String> accessibleNames = new Set<String>();
    public Id unknownAccountId;
    
    public Pagereference SaveEndAssignment(){
       //Added on 5/22 - Start
        Contact con = new Contact(Id = currentcr.TR1__Person_Placed__c);        
        con.TR1__Candidate_Status__c = 'Consult Hot';        
        if(TR1__TalentRoverProperties__c.getOrgDefaults() != null && TR1__TalentRoverProperties__c.getOrgDefaults().TR1__Candidate_Status_When_Assignment_Ended__c != null && TR1__TalentRoverProperties__c.getOrgDefaults().TR1__Candidate_Status_When_Assignment_Ended__c.trim() != '')
        	con.TR1__Candidate_Status__c = TR1__TalentRoverProperties__c.getOrgDefaults().TR1__Candidate_Status_When_Assignment_Ended__c;
        	
        if(unknownAccountId != null) con.AccountId = unknownAccountId;
        
         //Added on 5/22 - End
        currentcr.TR1__Generate_Timesheet__c = false;
        currentcr.TR1__Receive_Timesheet_Email_Alerts__c = false;
        currentcr.TR1__Assignment_Ended__c = 'Yes';
        
        //Added on 30Mar2017
        List<Closing_Report_Schedule__c> CRS_List = [SELECT Id,Status__c FROM Closing_Report_Schedule__c WHERE Schedule_Date__c >: currentcr.TR1__End_Date__c AND Closing_Report__c =:currentcr.Id];
        for(Closing_Report_Schedule__c crs : CRS_List){
            crs.Status__c = 'Cancelled';
        }
        system.debug('=============================Con====='+con);
        
        try{
            update currentcr;
            //Added on 30Mar2017
            update CRS_List;
            //Added on 5/22 
            update con;
            this.isSuccess = true;
            return null;
        }
        catch(DMLException ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,ex.getDMLMessage(0)));
            return null;
        }  
        catch(Exception ex){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,ex.getMessage()));
            return null;
        }       
    }   

    public ClosingReportButtonsCtrl(ApexPages.StandardController controller) 
    {
        Map<String, Schema.SobjectField> fields = Schema.SobjectType.TR1__Closing_Report__c.fields.getMap();
        for (String s : fields.keySet()) {           
            if (fields.get(s).getDescribe().isAccessible()){
                accessibleNames.add(s);
            }            
        }
        if(!Test.isrunningtest())
        {
            controller.addFields(new List<String>(accessibleNames));
            this.currentcr = (TR1__Closing_Report__c)controller.getRecord();
        }
        else
        {
             Id recordId = controller.getRecord().Id;
             this.currentcr = [select Id,TR1__Generate_Timesheet__c ,TR1__Receive_Timesheet_Email_Alerts__c ,TR1__Conversion_Date__c,
                                TR1__Job_Percentage__c,TR1__Candidate_Percentage__c  ,TR1__Marketing_Percentage__c ,
                                TR1__Other_Percentage__c ,TR1__Other2_Percentage__c ,TR1__Assignment_Ended__c ,TR1__End_Date__c,TR1__Rate_Change_Effective_Date__c
                                , TR1__Salary__c,TR1__Job__c,TR1__Person_Placed__c from TR1__Closing_Report__c
                                where Id = :recordId ];
        
        }
        this.newcr = currentcr.clone();
        this.newcr.TR1__Start_Date__c = null;
        this.newcr.TR1__Booking_Date__c = null;
        this.isSuccess = false;
        
        try{
            Account acc = [SELECT Id FROM Account Where Name = 'Unknown'];
            this.unknownAccountId = acc.Id;
        }
        catch(Exception ex){}
    }
}