src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Day_Charge_Rate__c</fullName>
        <label>Day Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Day_Pay_Rate__c</fullName>
        <label>Day Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Charge_Rate__c</fullName>
        <label>Hour Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Pay_Rate__c</fullName>
        <label>Hour Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <formula>TEXT(TR1__Job__r.TR1__Regional_Area__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subject</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <formula>TR1__Job__r.TR1__Contact__r.FirstName &amp; &quot; &quot; &amp;  TR1__Job__r.TR1__Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Generate_Timesheet__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Generate Timesheet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Percentage__c</fullName>
        <label>Job Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Hour_Charge_Rate__c</fullName>
        <label>Maximum Hour Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Pay_Rate__c</fullName>
        <label>Maximum Hour Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject (Old)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accountancy</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Art and Design</fullName>
                </value>
                <value>
                    <fullName>Basic Skills Tutor</fullName>
                </value>
                <value>
                    <fullName>Business Studies</fullName>
                </value>
                <value>
                    <fullName>Careers Education</fullName>
                </value>
                <value>
                    <fullName>Citizenship</fullName>
                </value>
                <value>
                    <fullName>Classics</fullName>
                </value>
                <value>
                    <fullName>CL - Greek</fullName>
                </value>
                <value>
                    <fullName>CL - Latin</fullName>
                </value>
                <value>
                    <fullName>Communications Technology</fullName>
                </value>
                <value>
                    <fullName>Dance</fullName>
                </value>
                <value>
                    <fullName>Drama</fullName>
                </value>
                <value>
                    <fullName>DT - Electronics</fullName>
                </value>
                <value>
                    <fullName>DT - Graphics</fullName>
                </value>
                <value>
                    <fullName>DT Non-resistant Material</fullName>
                </value>
                <value>
                    <fullName>DT Resistant Material</fullName>
                </value>
                <value>
                    <fullName>DT - Textiles</fullName>
                </value>
                <value>
                    <fullName>E2E Tutor</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Employability Tutor</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>English - General</fullName>
                </value>
                <value>
                    <fullName>English - Language</fullName>
                </value>
                <value>
                    <fullName>English - Literature</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Film</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Key_Stage__c</fullName>
        <label>Year/Key Stage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Foundation Stage 3-5yrs</fullName>
                </value>
                <value>
                    <fullName>KS1</fullName>
                </value>
                <value>
                    <fullName>KS2</fullName>
                </value>
                <value>
                    <fullName>KS3/4</fullName>
                </value>
                <value>
                    <fullName>KS3-5</fullName>
                </value>
                <value>
                    <fullName>Post-16</fullName>
                </value>
                <value>
                    <fullName>Nursery 0-5yrs</fullName>
                </value>
                <value>
                    <fullName>Y1(KS1)</fullName>
                </value>
                <value>
                    <fullName>Y2(KS1)</fullName>
                </value>
                <value>
                    <fullName>Y3(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y4(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y5(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y6(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y7(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y8(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y9(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y10(KS4)</fullName>
                </value>
                <value>
                    <fullName>Y11(KS4)</fullName>
                </value>
                <value>
                    <fullName>Y12(KS5)</fullName>
                </value>
                <value>
                    <fullName>Y13(KS5)</fullName>
                </value>
                <value>
                    <fullName>Primary 1-2 -1 Tutor</fullName>
                    <isActive>false</isActive>
                    <label>Primary 1-2 -1 Tutor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataUtility.cls
/**
 * This class willl provide data for test classes
 * This class is used by following classes
 * 1. TestTimeSheets_v1
 * 
**/


@isTest
public class TestDataUtility {
    
    public static Id CONSULTING_RECORDTYPE_JOB = Schema.SObjectType.TR1__Job__c.getRecordTypeInfosByName().get('Consulting').getRecordTypeId();
    public static Id CONSULTING_RECORDTYPE_CLOSINGREPORT = Schema.SObjectType.TR1__Closing_Report__c.getRecordTypeInfosByName().get('Consulting').getRecordTypeId();
    
    public static User createUser(Boolean isInsert){
        Profile sysAdminProfile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        //UserRole ur = [Select Id, Name From UserRole limit 1];
        User testUser = new User(/**UserRoleId  = ur.Id,**/Alias = String.valueOf(datetime.now()).substring(0,8), Email='testUser@suppludesk.com',
                                EmailEncodingKey='UTF-8', LastName='User'+String.valueOf(date.today()), LanguageLocaleKey='fr',
                                LocaleSidKey='fr_FR', ProfileId = sysAdminProfile.Id,
                                TimeZoneSidKey='Europe/London', UserName='testUser'+String.valueOf(Math.random())+'@supplydesk.com',FirstName='Test');
        if(isInsert){
            insert testUser;
        }
        return testUser;
    }
    
    public static Account createAccount(Boolean isInsert){
        Account testAccount = new Account(Name='Test Account', BillingStreet  ='123', BillingCity ='test city', BillingState ='test county', BillingPostalCode  = '234345',
                                        BillingCountry  = 'test Country', ShippingStreet = '1233', ShippingCity='Test City', ShippingState='Test State', ShippingPostalCode='564533',
                                        ShippingCountry='Test Country');
        if(isInsert){
            insert testAccount;
        }
        return testAccount;
    }
  
    public static Contact createContact(Id accountId,Boolean isInsert){
        Contact testContact = new Contact(FirstName = 'Test', LastName='Candidate', Email='testcandidate@suppludesk.com');
        if(isInsert){
            insert testContact;
        }
        return testContact;
    }
    
    public static TR1__Job__c createJob(Id recordTypeId,Id accountId,Boolean isInsert){
        TR1__Job__c testJob = new TR1__Job__c(RecordTypeId = recordTypeId, TR1__Account__c = accountId, Name = 'Test Job',TR1__Status__c='Open', Subject__c ='Art', Year_Key_Stage__c ='KS1');
        if(isInsert){
            insert testJob;
        }
        return testJob;
    }
    
    public static TR1__Closing_Report__c createClosingReport(Id recordTypeId,Id accountId,Id jobId,Id personPlacedId,Id jobCreditId,Boolean isInsert){
        
        TR1__Closing_Report__c testClosingReport = new TR1__Closing_Report__c(
                                                                                    TR1__Account__c= accountId,
                                                                                    RecordTypeId = recordTypeId,
                                                                                    TR1__Job__c=jobId,
                                                                                    TR1__Person_Placed__c=personPlacedId,
                                                                                    TR1__Job_Percentage__c = 100,
                                                                                    TR1__Job_Credit__c = jobCreditId,
                                                                                    TR1__Start_Date__c = Date.today().addDays(-15),
                                                                                    TR1__End_Date__c = Date.today().addDays(30),
                                                                                    TR1__Generate_Timesheet__c = true,
                                                                                    Maximum_Day_Pay_Rate__c = 23,
                                                                                    Maximum_Day_Charge_Rate__c = 23,
                                                                                    Maximum_Hour_Charge_Rate__c = 23,
                                                                                    Maximum_Hour_Pay_Rate__c = 23
                                                                                );
        if(isInsert){
            insert testClosingReport;
        }
        return testClosingReport;
    }
    
    public static TR1__Qualification__c createQualification(String qualificationName,Boolean isInsert){
        TR1__Qualification__c testQualification = new TR1__Qualification__c(Name = qualificationName);
        if(isInsert){
            insert testQualification;
        }
        return testQualification;
    }
    
    public static TR1__Associated_Qualification__c createAssociatedQualification(Id qualificationId,Id contactId,String status, Boolean isInsert){
        TR1__Associated_Qualification__c testAssociatedQualification = new TR1__Associated_Qualification__c	(TR1__Qualification__c = qualificationId,TR1__Status__c = status,TR1__Contact__c = contactId);
        if(isInsert){
            insert testAssociatedQualification;
        }
        return testAssociatedQualification;
    }
}