src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Booking Confirmed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Candidate_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Candidate_Percentage__c</fullName>
        <label>Candidate Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <formula>TR1__Job__r.TR1__Contact__r.FirstName &amp; &quot; &quot; &amp;  TR1__Job__r.TR1__Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Generate_Timesheet__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Generate Timesheet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Percentage__c</fullName>
        <label>Job Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Marketing_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Marketing_Percentage__c</fullName>
        <label>Marketing Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Other2_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Other2 Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closes4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Other2_Percentage__c</fullName>
        <label>Other2 Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Other_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Other Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closes3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Other_Percentage__c</fullName>
        <label>Other Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Closes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timesheet_Frequency__c</fullName>
        <label>Timesheet Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                    <default>true</default>
                    <label>Weekly</label>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Subject2__c</fullName>
        <label>Subject</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Cover</fullName>
                </value>
                <value>
                    <fullName>Accountancy</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Art and Design</fullName>
                </value>
                <value>
                    <fullName>Basic Skills Tutor</fullName>
                </value>
                <value>
                    <fullName>Business Studies</fullName>
                </value>
                <value>
                    <fullName>Careers Education</fullName>
                </value>
                <value>
                    <fullName>Citizenship</fullName>
                </value>
                <value>
                    <fullName>Classics</fullName>
                </value>
                <value>
                    <fullName>CL - Greek</fullName>
                </value>
                <value>
                    <fullName>CL - Latin</fullName>
                </value>
                <value>
                    <fullName>Communications Technology</fullName>
                </value>
                <value>
                    <fullName>Dance</fullName>
                </value>
                <value>
                    <fullName>Drama</fullName>
                </value>
                <value>
                    <fullName>DT - Electronics</fullName>
                </value>
                <value>
                    <fullName>DT - Graphics</fullName>
                </value>
                <value>
                    <fullName>DT Non-resistant Material</fullName>
                </value>
                <value>
                    <fullName>DT Resistant Material</fullName>
                </value>
                <value>
                    <fullName>DT - Textiles</fullName>
                </value>
                <value>
                    <fullName>E2E Tutor</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Employability Tutor</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>English - Language</fullName>
                </value>
                <value>
                    <fullName>English - Literature</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Film</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Estimated_End_Date__c</fullName>
        <label>Estimated End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Estimated_Start_Date__c</fullName>
        <label>Estimated Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Maximum_Bill_Rate__c</fullName>
        <label>Maximum Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Minimum_Pay_Rate__c</fullName>
        <label>Minimum Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Timesheet Approver)</relationshipLabel>
        <relationshipName>Jobs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year_Key_Stage__c</fullName>
        <label>Year/Key Stage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Foundation Stage 3-5yrs</fullName>
                </value>
                <value>
                    <fullName>KS1</fullName>
                </value>
                <value>
                    <fullName>KS2</fullName>
                </value>
                <value>
                    <fullName>KS3/4</fullName>
                </value>
                <value>
                    <fullName>KS3-5</fullName>
                </value>
                <value>
                    <fullName>Post-16</fullName>
                </value>
                <value>
                    <fullName>Nursery 0-5yrs</fullName>
                </value>
                <value>
                    <fullName>Y1(KS1)</fullName>
                </value>
                <value>
                    <fullName>Y2(KS1)</fullName>
                </value>
                <value>
                    <fullName>Y3(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y4(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y5(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y6(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y7(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y8(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y9(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y10(KS4)</fullName>
                </value>
                <value>
                    <fullName>Y11(KS4)</fullName>
                </value>
                <value>
                    <fullName>Y12(KS5)</fullName>
                </value>
                <value>
                    <fullName>Y13(KS5)</fullName>
                </value>
                <value>
                    <fullName>Primary 1-2 -1 Tutor</fullName>
                    <isActive>false</isActive>
                    <label>Primary 1-2 -1 Tutor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/autoSubmitTimesheetsBatchTest.cls
@isTest
private class autoSubmitTimesheetsBatchTest {

    private static testMethod void autoSubmitTimesheetsTest() {
        // Create Test data
       Test.StartTest();
      
      User u1=TestUtility.getUserDetail();
          
        
        System.runAs(u1){
            Account acc=TestUtility.getAccountDetail();
        Contact con =TestUtility.getContactDetail(u1,acc);
            insert con;
            
        Id consultingid = Schema.SObjectType.TR1__Job__c.getRecordTypeInfosByName().get('Consulting').getRecordTypeId();
        Date todayDate = system.today();
        TR1__Job__c job1 = new TR1__Job__c(RecordTypeId=consultingid,TR1__Account__c=acc.Id,Name='Job 2',TR1__Contact__c=con.Id,TR1__Estimated_Start_Date__c=todayDate,TR1__Estimated_End_Date__c=todayDate.addDays(7),
                                TR1__Minimum_Pay_Rate__c=100,TR1__Maximum_Bill_Rate__c=100,Subject2__c='Accountancy',Year_Key_Stage__c='Y4(KS2)');
        TR1__Job__c[] joblist = new TR1__Job__c[]{job1};        
        insert joblist;
        Contact candidate1 = new Contact(LastName = 'Candidate 1');
        Contact[] candidatelist = new Contact[]{candidate1};  
        insert candidatelist;
       
        
        DateTime dateTimeVar = system.today();
        Id crconsultingId = Schema.SObjectType.TR1__Closing_Report__c.getRecordTypeInfosByName().get('Consulting').getRecordTypeId();
            
        TR1__Closing_Report__c cr1 = new TR1__Closing_Report__c(RecordTypeId = crconsultingId, TR1__Job__c = job1.Id,TR1__Account__c=acc.Id, TR1__Person_Placed__c = con.Id, TR1__Salary__c = 125000.00, TR1__Job_Percentage__c = 20,
                                    TR1__Candidate_Percentage__c = 20, TR1__Marketing_Percentage__c = 20, TR1__Other_Percentage__c = 20, TR1__Other2_Percentage__c = 20,
                                    TR1__Job_Credit__c = u1.Id, TR1__Candidate_Credit__c = u1.Id, TR1__Marketing_Credit__c = u1.Id, TR1__Other_Credit__c = u1.Id, TR1__Other2_Credit__c = u1.Id,Timesheet_Frequency__c = 'Weekly',
                                    TR1__Start_Date__c = todayDate.addDays(-15), TR1__End_Date__c = todayDate.addDays(10), TR1__Generate_Timesheet__c = true, TR1__Timesheet_Approver__c = candidatelist[0].Id,Booking_Confirmed__c = true); 
        insert cr1;
        
        autoSubmitTimesheetsBatch batchClass = new autoSubmitTimesheetsBatch();
        ID batchprocessid = Database.executeBatch(batchClass);
        
        autoSubmitTimesheetsBatchSchedulable sch = New autoSubmitTimesheetsBatchSchedulable();
        String constr = '0 0 23 * * ?';
        system.schedule('Auto Submit Timesheet Batch',constr,sch);
        Test.StopTest();
        }
        
    }
    

}