src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Hour_Charge_Rate__c</fullName>
        <label>Maximum Hour Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SEN_Additional_Experience__c</fullName>
        <label>SEN Skills, Quals and Training</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ADHD Awareness</fullName>
                </value>
                <value>
                    <fullName>Art Therapy</fullName>
                </value>
                <value>
                    <fullName>Autism Awareness</fullName>
                </value>
                <value>
                    <fullName>Behaviour Mentor &amp; Tuition Training</fullName>
                </value>
                <value>
                    <fullName>BSL Level 1-3</fullName>
                </value>
                <value>
                    <fullName>Bullying Support Training</fullName>
                </value>
                <value>
                    <fullName>Disability Sports Coaching Award</fullName>
                </value>
                <value>
                    <fullName>Drug Awareness Training</fullName>
                </value>
                <value>
                    <fullName>Dyslexia Support Training</fullName>
                </value>
                <value>
                    <fullName>EAL Specialist</fullName>
                </value>
                <value>
                    <fullName>Eating Disorder Awareness</fullName>
                </value>
                <value>
                    <fullName>Emergency First Aid</fullName>
                </value>
                <value>
                    <fullName>Epilepsy Training</fullName>
                </value>
                <value>
                    <fullName>Jolly Phonics</fullName>
                </value>
                <value>
                    <fullName>Makaton</fullName>
                </value>
                <value>
                    <fullName>Moving and Handling</fullName>
                </value>
                <value>
                    <fullName>Music Therapy</fullName>
                </value>
                <value>
                    <fullName>PECS</fullName>
                    <isActive>false</isActive>
                    <label>PECS</label>
                </value>
                <value>
                    <fullName>Phonics Trained</fullName>
                </value>
                <value>
                    <fullName>Physical Disabilities</fullName>
                </value>
                <value>
                    <fullName>Safeguarding</fullName>
                </value>
                <value>
                    <fullName>Safe Handling &amp; Administration of Medicine</fullName>
                </value>
                <value>
                    <fullName>Speech and Language Trained</fullName>
                </value>
                <value>
                    <fullName>Suspected Physical &amp; Mental Abuse Awareness</fullName>
                </value>
                <value>
                    <fullName>Team Teach</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SEN_Experience__c</fullName>
        <label>SEN Experience</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>ADHD</fullName>
                </value>
                <value>
                    <fullName>ASD</fullName>
                </value>
                <value>
                    <fullName>Aspergers</fullName>
                </value>
                <value>
                    <fullName>AUTISM</fullName>
                    <isActive>false</isActive>
                    <label>AUTISM</label>
                </value>
                <value>
                    <fullName>BSL</fullName>
                    <isActive>false</isActive>
                    <label>BSL</label>
                </value>
                <value>
                    <fullName>Downs Syndrome Experience</fullName>
                </value>
                <value>
                    <fullName>DYSLEXIA</fullName>
                </value>
                <value>
                    <fullName>EAL/ EFL</fullName>
                </value>
                <value>
                    <fullName>EBD</fullName>
                </value>
                <value>
                    <fullName>Epilepsy Training</fullName>
                    <isActive>false</isActive>
                    <label>Epilepsy Training</label>
                </value>
                <value>
                    <fullName>Gifted &amp;Talented (G&amp;T)</fullName>
                </value>
                <value>
                    <fullName>HAPS</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>Makaton</fullName>
                    <isActive>false</isActive>
                    <label>Makaton</label>
                </value>
                <value>
                    <fullName>Mappa</fullName>
                    <isActive>false</isActive>
                    <label>Mappa</label>
                </value>
                <value>
                    <fullName>MLD</fullName>
                </value>
                <value>
                    <fullName>Moving &amp;Handling Training</fullName>
                    <isActive>false</isActive>
                    <label>Moving &amp;Handling Training</label>
                </value>
                <value>
                    <fullName>Physical Disabilities</fullName>
                    <isActive>false</isActive>
                    <label>Physical Disabilities</label>
                </value>
                <value>
                    <fullName>PMLD</fullName>
                </value>
                <value>
                    <fullName>PRU/Centre of Education</fullName>
                </value>
                <value>
                    <fullName>SEMH</fullName>
                </value>
                <value>
                    <fullName>SENCO</fullName>
                </value>
                <value>
                    <fullName>SEN Mainstream</fullName>
                </value>
                <value>
                    <fullName>Sign Language Experience</fullName>
                </value>
                <value>
                    <fullName>SLD</fullName>
                </value>
                <value>
                    <fullName>Speech and Language</fullName>
                </value>
                <value>
                    <fullName>Team Teach</fullName>
                    <isActive>false</isActive>
                    <label>Team Teach</label>
                </value>
                <value>
                    <fullName>VI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector1__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Children&apos;s Centre</fullName>
                </value>
                <value>
                    <fullName>College (6th)</fullName>
                </value>
                <value>
                    <fullName>Further Education</fullName>
                </value>
                <value>
                    <fullName>HMP Prison</fullName>
                </value>
                <value>
                    <fullName>Infant</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>Overseas Client</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Private Nursery</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Special Needs</fullName>
                </value>
                <value>
                    <fullName>Tech College</fullName>
                </value>
                <value>
                    <fullName>Through School</fullName>
                </value>
                <value>
                    <fullName>Virtual School</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Estimated_End_Date__c</fullName>
        <label>Estimated End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Estimated_Start_Date__c</fullName>
        <label>Estimated Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Maximum_Bill_Rate__c</fullName>
        <label>Maximum Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Maximum_Pay_Rate__c</fullName>
        <label>Maximum Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year_Key_Stage__c</fullName>
        <label>Year/Key Stage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Foundation Stage 3-5yrs</fullName>
                </value>
                <value>
                    <fullName>KS1</fullName>
                </value>
                <value>
                    <fullName>KS2</fullName>
                </value>
                <value>
                    <fullName>KS3/4</fullName>
                </value>
                <value>
                    <fullName>KS3-5</fullName>
                </value>
                <value>
                    <fullName>Post-16</fullName>
                </value>
                <value>
                    <fullName>Nursery 0-5yrs</fullName>
                </value>
                <value>
                    <fullName>Y1(KS1)</fullName>
                </value>
                <value>
                    <fullName>Y2(KS1)</fullName>
                </value>
                <value>
                    <fullName>Y3(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y4(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y5(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y6(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y7(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y8(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y9(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y10(KS4)</fullName>
                </value>
                <value>
                    <fullName>Y11(KS4)</fullName>
                </value>
                <value>
                    <fullName>Y12(KS5)</fullName>
                </value>
                <value>
                    <fullName>Y13(KS5)</fullName>
                </value>
                <value>
                    <fullName>Primary 1-2 -1 Tutor</fullName>
                    <isActive>false</isActive>
                    <label>Primary 1-2 -1 Tutor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>TR1__Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Timesheet Detail</label>
    <nameField>
        <displayFormat>TS-{MM}{DD}{YY}-{0}</displayFormat>
        <label>Timesheet Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateTimesheetExportControllerTest.cls
@isTest
public class CreateTimesheetExportControllerTest {

    public static testmethod void test(){
 User u1=TestUtility.getUserDetail();
          
        
        System.runAs(u1){
            Account testAccount=TestUtility.getAccountDetail();
        Contact testContact =TestUtility.getContactDetail(u1,testAccount);
            insert testContact;
        CreateTimesheetExportController c = new CreateTimesheetExportController();
        c.doTimesheetExport();

       

        Id conCandidId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();

        

        Id consultingid = Schema.SObjectType.TR1__Job__c.getRecordTypeInfosByName().get('Consulting').getRecordTypeId();

        TR1__Job__c testJob = new TR1__Job__c(RecordTypeId=consultingid, TR1__Account__c=testAccount.Id, Name='Job 2',TR1__Estimated_Start_Date__c=Date.today(),TR1__Estimated_End_Date__c=Date.today().addDays(7),TR1__Contact__c=testContact.Id,Sector1__c='Nursery', Year_Key_Stage__c ='KS1',Maximum_Hour_Charge_Rate__c=23,TR1__Maximum_Pay_Rate__c=54,TR1__Maximum_Bill_Rate__c=45,SEN_Experience__c='ADHD',SEN_Additional_Experience__c ='ADHD Awareness');
        insert testJob;

        TR1__Timesheet__c testTimesheet = new TR1__Timesheet__c(TR1__Status__c = 'Unsubmitted', TR1__Job_Order__c = testJob.Id ,TR1__Client__c=testAccount.Id,TR1__Consultant__c=testContact.Id);
        insert testTimesheet;

        Date todayDate = system.today();
        Integer numberDaysDue = todayDate.daysBetween(todayDate.addDays(6));
        List<TR1__Timesheet_Detail__c> timesheetdetails = new List<TR1__Timesheet_Detail__c>();
        for (Integer i = 0 ; i <= numberDaysDue; i++) {
            TR1__Timesheet_Detail__c td = new TR1__Timesheet_Detail__c(TR1__Timesheet__c = testTimesheet.Id, TR1__Date__c = todayDate.addDays(i),DayShift__c=true, TR1__Day__c = dayOfDate(todayDate.addDays(i)));
            timesheetdetails.add(td);
        }
        insert timesheetdetails;
        Test.startTest();
        testTimesheet.TR1__Status__c = 'Approved';
        update testTimesheet;
        c.checkAsyncJobStatus();
        c.doTimesheetExport();
        c.checkAsyncJobStatus();
        Test.stopTest();
        }
    }

    public static String dayOfDate(Date d) {
        Datetime dt = DateTime.newInstance(d.year(), d.month(), d.day());
        return dt.format('EEEE'); //returns Sunday or Monday or ..
    }
}