src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_Closing_Report_Created_Date__c</fullName>
        <label>Last Closing Report Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Candidate_Availability__c.object
<CustomObject>
    <description>Object to store the availability of a candidate for a start to end date.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Candidate Availabilities</relationshipLabel>
        <relationshipName>Candidate_Availabilitys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Candidate Availability</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>CA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Closing_Report_Schedule__c.object
<CustomObject>
    <description>A schedule record is created for each day a Candidate is assigned to the Vacancy</description>
    <fields>
        <fullName>Candidate_Availability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Availability</label>
        <referenceTo>Candidate_Availability__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closing_Report__c</fullName>
        <label>Closing Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TR1__Closing_Report__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vacancy_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vacancy Schedule</label>
        <referenceTo>Vacancy_D2D__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Closing Report Schedule</label>
    <nameField>
        <displayFormat>CRS-{0000000}</displayFormat>
        <label>CRS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Assignment_Ended__c</fullName>
        <label>Assignment Ended</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Rate Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Generate_Timesheet__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Generate Timesheet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timesheet_Frequency__c</fullName>
        <label>Timesheet Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                    <default>true</default>
                    <label>Weekly</label>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Vacancies - Qualified</relationshipLabel>
        <relationshipName>Vacancies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>End_date__c</fullName>
        <formula>TR1__Closing_Report__r.TR1__End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <formula>TR1__Closing_Report__r.TR1__Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Closing_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report</label>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Order__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vacancy_D2D__c.object
<CustomObject>
    <fields>
        <fullName>Closing_Report_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report Schedule</label>
        <referenceTo>Closing_Report_Schedule__c</referenceTo>
        <relationshipLabel>Vacancy Schedules</relationshipLabel>
        <relationshipName>Vacancy_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vacancy_Date__c</fullName>
        <inlineHelpText>Date for which this vacancy is applicable</inlineHelpText>
        <label>Vacancy Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vacancy__c</fullName>
        <label>Vacancy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TR1__Job__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Vacancy_D2Ds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vacancy Schedule</label>
    <nameField>
        <displayFormat>D2D-{000000}</displayFormat>
        <label>D2D Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClosingReportTriggerHelper.cls
//  created on 12-16-2015 by Bashetty Naveen to populating closing report details from contact when it saving and update it while contact update 

public class ClosingReportTriggerHelper {
    public static Boolean FromJobboard = False;
    public static Boolean createTimesheetsForPastOrThisWeekFlag = False;
    
    public static void bulkBookingfromJobboard(List <TR1__Closing_Report__c> crlist){
        database.setSavepoint();
        set<ID> PPIds = new set<ID> ();
        set<ID> VACIds = new set<ID> ();
        List<Closing_Report_Schedule__c> crsList = new List<Closing_Report_Schedule__c>();
        List<Candidate_Availability__c> canAvailList = new List<Candidate_Availability__c>();
        Map<Id,Candidate_Availability__c>canVaccAvail = new Map<Id,Candidate_Availability__c>();
        Map<Date,Vacancy_D2D__c>dateJSMap = new Map<Date,Vacancy_D2D__c>();
        // for(TR1__Closing_Report__c cr : crlist){
        //     PPIds.add(cr.TR1__Person_Placed__c);
        //     VACIds.add(cr.TR1__Job__c);
        // }
        List<Vacancy_D2D__c> vacScheduleList= [select Id,Name,Vacancy__c,Vacancy_Date__c,Start_Date_Time__c,End_Date_Time__c from Vacancy_D2D__c where Vacancy__c =:crlist[0].TR1__Job__c and Vacancy_Date__c >= :crlist[0].TR1__Start_Date__c and Vacancy_Date__c <= :crlist[0].TR1__End_Date__c ];
        
        for(Vacancy_D2D__c vacc: vacScheduleList){
            Candidate_Availability__c canAvail = new Candidate_Availability__c();
            canAvail = new Candidate_Availability__c(Candidate__c = crlist[0].TR1__Person_Placed__c, End_Date__c=vacc.Vacancy_Date__c, Start_Date__c=vacc.Vacancy_Date__c, Start_Date_Time__c=vacc.Start_Date_Time__c, End_Date_Time__c=vacc.End_Date_Time__c);
            canAvailList.add(canAvail);
            dateJSMap.put(vacc.Vacancy_Date__c,vacc);
        }
        Database.SaveResult[] srList = database.insert(canAvailList, false) ;
        for(Candidate_Availability__c csd :[select Id,Name,Candidate__c,Start_Date__c,Start_Date_Time__c,End_Date_Time__c from Candidate_Availability__c where Candidate__c =:crlist[0].TR1__Person_Placed__c and Start_Date__c >= :crlist[0].TR1__Start_Date__c and Start_Date__c <= :crlist[0].TR1__End_Date__c]){
            if(dateJSMap.containskey(csd.Start_Date__c) && dateJSMap.get(csd.Start_Date__c).Start_Date_Time__c >= csd.Start_Date_Time__c &&  dateJSMap.get(csd.Start_Date__c).Start_Date_Time__c <= csd.End_Date_Time__c){
                //system.debug('canVaccAvail-->'+canVaccAvail.get(vacc.Id).Id);
                Closing_Report_Schedule__c CRS = new Closing_Report_Schedule__c();
                CRS.Schedule_Date__c = dateJSMap.get(csd.Start_Date__c).Vacancy_Date__c;
                CRS.Closing_Report__c  = crlist[0].Id;
                CRS.Candidate_Availability__c = csd.Id;
                CRS.Vacancy_Schedule__c = dateJSMap.get(csd.Start_Date__c).Id;
                CRS.Status__c  = 'Booked';
                crsList.add(CRS);    
            }
        }
        Database.SaveResult[] srList2 = database.insert(crsList, True) ;
    }
    
    public static void updateCRS(List <TR1__Closing_Report__c> crlist, Map<Id, TR1__Closing_Report__c> crOldMap,Map<Id,TR1__Closing_Report__c> crNewMap){
        set<ID> CRIds = new set<ID> ();

        for(TR1__Closing_Report__c cr : crlist){
            if(cr.Status__c != crOldMap.get(cr.Id).Status__c && cr.Status__c=='Cancelled')
                CRIds.add(cr.Id);
        }
        List<Closing_Report_Schedule__c> crsList = [select Id , Name , Status__c, Closing_Report__c From Closing_Report_Schedule__c where Closing_Report__c IN: CRIds];
        for(Closing_Report_Schedule__c crs: crsList){
            crs.Status__c = 'Cancelled';
            //crs.Reason_for_Cancellation__c = crNewMap.get(crs.Closing_Report__c).Reason_for_Cancelling_the_Job__c;
        }
        update crsList; 
    } 
    
    public static void updateClientStatus(List <TR1__Closing_Report__c> crlist){
        set<ID> CRaccIds = new set<ID> ();

        for(TR1__Closing_Report__c cr : crlist){
            if(cr.TR1__Account__c != null)
                CRaccIds.add(cr.TR1__Account__c);
        }
        List<Account> accList = [select Id, Name, Status__c, Last_Closing_Report_Created_Date__c From Account where Id IN: CRaccIds];
        if(accList.size()>0){
            for(Account acc: accList){
                acc.Status__c = 'Client';
                acc.Last_Closing_Report_Created_Date__c = Date.Today();
                //crs.Reason_for_Cancellation__c = crNewMap.get(crs.Closing_Report__c).Reason_for_Cancelling_the_Job__c;
            }
            update accList; 
        }
        
    } 
    
    public static void createTimesheetsForPastOrThisWeek(List <TR1__Closing_Report__c> recordNewList) {
    	
    	//added by Manmeet to find if Timesheet was already created for the CR
    	Map<String, TR1__Timesheet__c> mapJobMaxTimesheetData = new Map<String, TR1__Timesheet__c>();
    	Set<String> setJobs = new Set<String>();
    	for(TR1__Closing_Report__c cr : [Select Id, TR1__Job__c From TR1__Closing_Report__c where Id in : recordNewList]){
    		setJobs.add(cr.TR1__Job__c);
    	}
    	for(TR1__Job__c job : [Select Id, (Select Id, TR1__Week_Ending__c from TR1__Timesheets__r 
    									order by TR1__Week_Ending__c DESC 
    									limit 1) 
    									From TR1__Job__c where Id in : setJobs]){
			if(job.TR1__Timesheets__r.size() > 0){
				mapJobMaxTimesheetData.put(job.id, job.TR1__Timesheets__r[0]);	
			}
    	}
    	
        for(TR1__Closing_Report__c cr : recordNewList){
            Date nextStartDate;
             if(cr.Timesheet_Frequency__c=='Calendar Monthly'){
            nextStartDate=System.today().toStartOfMonth().addMonths(1);  
            }
            else{
                Date d = System.today();
				Datetime dt = (DateTime)d;
				String dayOfWeek = dt.format('u');
                if(dayOfWeek=='6' || dayOfWeek=='7'){
                     nextStartDate=System.today().toStartOfWeek().addDays(14);
                }
                else{
                     nextStartDate=System.today().toStartOfWeek().addDays(7);
                }
                    
            } 
            
            Id crconsultingId = Schema.SObjectType.TR1__Closing_Report__c.getRecordTypeInfosByName().get('Consulting').getRecordTypeId();
            
            if((cr.TR1__Start_Date__c < nextStartDate || (mapJobMaxTimesheetData.containsKey(cr.TR1__Job__c) && cr.TR1__Start_Date__c <= mapJobMaxTimesheetData.get(cr.TR1__Job__c).TR1__Week_Ending__c)) 
            	&& cr.RecordTypeId == crconsultingId && cr.TR1__Generate_Timesheet__c == true && cr.TR1__Start_Date__c!=null && cr.TR1__End_Date__c!=null && cr.TR1__Assignment_Ended__c=='No'){   
                Date startDate = cr.Timesheet_Frequency__c=='Calendar Monthly'?cr.TR1__Start_Date__c.toStartOfMonth():cr.TR1__Start_Date__c.toStartOfWeek();
                
                    
                Date endDate = cr.TR1__End_Date__c < nextStartDate ? cr.TR1__End_Date__c : nextStartDate.addDays(-1);
                if(cr.TR1__Start_Date__c > nextStartDate){
                	endDate = cr.TR1__End_Date__c < mapJobMaxTimesheetData.get(cr.TR1__Job__c).TR1__Week_Ending__c ? cr.TR1__End_Date__c : mapJobMaxTimesheetData.get(cr.TR1__Job__c).TR1__Week_Ending__c.addDays(-1);
                }
                string str = TimesheetUtility.insertTimesheetDetail(cr,startDate,endDate);
            }
        }
    }
    
    public static void populateSmallestDate( List <TR1__Closing_Report__c> crlist, Map<Id, TR1__Closing_Report__c> OldMap) {
        Map<Id, Contact> contactMap = new Map<Id, Contact>();
        
        for(TR1__Closing_Report__c oCls :crlist){
            if(oCls.TR1__Person_Placed__c != null && (OldMap == null || (OldMap != null && (oCls.TR1__Start_Date__c != oldMap.get(oCls.Id).TR1__Start_Date__c || oCls.TR1__Person_Placed__c != oldMap.get(oCls.Id).TR1__Person_Placed__c )))){
                contactMap.put(oCls.TR1__Person_Placed__c, null);
            }
            if(OldMap != null && oCls.TR1__Person_Placed__c != oldMap.get(oCls.Id).TR1__Person_Placed__c && oldMap.get(oCls.Id).TR1__Person_Placed__c != null){
                contactMap.put(oldMap.get(oCls.Id).TR1__Person_Placed__c, null);
            }
        }
        if(contactMap.size() > 0){
            contactMap = new map<Id, Contact>([Select Id, Placement_Start_Date__c from Contact where Id IN : contactMap.keySet()]);
            for(AggregateResult agr : [Select TR1__Person_Placed__c, MIN(TR1__Start_Date__c) TR1__Start_Date__c From TR1__Closing_Report__c WHERE TR1__Person_Placed__c IN :contactMap.keySet() GROUP BY TR1__Person_Placed__c]){
                Id contactId = (Id)agr.get('TR1__Person_Placed__c');
                Date crStartDate = (Date)agr.get('TR1__Start_Date__c');
                contactMap.get(contactId).Placement_Start_Date__c = crStartDate;
            }
            if(contactMap.size() >0){
                update contactMap.values();
            }
        }
    }
}