src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Pay_Type__c</fullName>
        <label>Pay Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Assignment_Ended__c</fullName>
        <label>Assignment Ended</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Rate Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Bill_Rate__c</fullName>
        <label>Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Generate_Timesheet__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Generate Timesheet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Pay_Rate__c</fullName>
        <label>Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Payroll_Type__c</fullName>
        <label>Payroll Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>W2 - Exempt</fullName>
                </value>
                <value>
                    <fullName>W2 - Non Exempt</fullName>
                </value>
                <value>
                    <fullName>1099</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Closes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Second_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Second Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports (Timesheet Second Approver)</relationshipLabel>
        <relationshipName>SecondApproverCR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timesheet_Frequency__c</fullName>
        <label>Timesheet Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                    <default>true</default>
                    <label>Weekly</label>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Timesheet Approver)</relationshipLabel>
        <relationshipName>Jobs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trained_As__c</fullName>
        <label>Trained As</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cover Supervisor</fullName>
                </value>
                <value>
                    <fullName>Early Years Trained</fullName>
                </value>
                <value>
                    <fullName>EYFS Teacher</fullName>
                </value>
                <value>
                    <fullName>FE/Post 16</fullName>
                </value>
                <value>
                    <fullName>FE/Post 16 QTLS</fullName>
                </value>
                <value>
                    <fullName>HLTA</fullName>
                </value>
                <value>
                    <fullName>Instructor</fullName>
                </value>
                <value>
                    <fullName>Nursery Nurse Level 2</fullName>
                </value>
                <value>
                    <fullName>Nursery Nurse Level 3</fullName>
                </value>
                <value>
                    <fullName>NVQ Assessor</fullName>
                </value>
                <value>
                    <fullName>Overseas Trained (Not QTS)</fullName>
                </value>
                <value>
                    <fullName>Play Therapist</fullName>
                </value>
                <value>
                    <fullName>Primary Teacher</fullName>
                </value>
                <value>
                    <fullName>Secondary Teacher</fullName>
                </value>
                <value>
                    <fullName>SEN TA</fullName>
                </value>
                <value>
                    <fullName>SEN Teacher</fullName>
                </value>
                <value>
                    <fullName>Speech &amp; Language Therapist</fullName>
                </value>
                <value>
                    <fullName>Support Worker</fullName>
                </value>
                <value>
                    <fullName>TA Level 2</fullName>
                </value>
                <value>
                    <fullName>TA Level 3</fullName>
                </value>
                <value>
                    <fullName>Teacher</fullName>
                </value>
                <value>
                    <fullName>TiQ Trainee</fullName>
                </value>
                <value>
                    <fullName>Trainer</fullName>
                </value>
                <value>
                    <fullName>Unqualified Pupil/Class Support</fullName>
                </value>
                <value>
                    <fullName>Vocational Tutor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year_Key_Stage__c</fullName>
        <label>Year/Key Stage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Foundation Stage 3-5yrs</fullName>
                </value>
                <value>
                    <fullName>KS1</fullName>
                </value>
                <value>
                    <fullName>KS2</fullName>
                </value>
                <value>
                    <fullName>KS3/4</fullName>
                </value>
                <value>
                    <fullName>KS3-5</fullName>
                </value>
                <value>
                    <fullName>Post-16</fullName>
                </value>
                <value>
                    <fullName>Nursery 0-5yrs</fullName>
                </value>
                <value>
                    <fullName>Y1(KS1)</fullName>
                </value>
                <value>
                    <fullName>Y2(KS1)</fullName>
                </value>
                <value>
                    <fullName>Y3(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y4(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y5(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y6(KS2)</fullName>
                </value>
                <value>
                    <fullName>Y7(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y8(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y9(KS3)</fullName>
                </value>
                <value>
                    <fullName>Y10(KS4)</fullName>
                </value>
                <value>
                    <fullName>Y11(KS4)</fullName>
                </value>
                <value>
                    <fullName>Y12(KS5)</fullName>
                </value>
                <value>
                    <fullName>Y13(KS5)</fullName>
                </value>
                <value>
                    <fullName>Primary 1-2 -1 Tutor</fullName>
                    <isActive>false</isActive>
                    <label>Primary 1-2 -1 Tutor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestTimeSheets_v1.cls
@isTest(SeeAllData=true)
public class TestTimeSheets_v1{
    public static testMethod void Test1(){

        User testUser = TestDataUtility.createUser(false);
        system.runAs(testUser){
            Account testAccount = TestDataUtility.createAccount(true);

            Contact testContact = TestDataUtility.createContact(testAccount.id,false);
            testContact.Compliance_Owner__c = testUser.Id;
            testContact.Year_Key_Stage__c = 'KS1';
            testContact.Compliance_Status__c = 'Perm';
            testContact.Pay_Type__c = 'Perm';
            testContact.Trained_As__c = 'Instructor';
            testContact.TR1__Candidate_Status__c = 'Prospect';
            testContact.Qualified_Schools_Candidate__c ='YES';
            insert testContact;

            TR1__Job__c testConsutlingJob = TestDataUtility.createJob(TestDataUtility.CONSULTING_RECORDTYPE_JOB,testAccount.id,true);

            TR1__Closing_Report__c testClosingReport = TestDataUtility.createClosingReport(TestDataUtility.CONSULTING_RECORDTYPE_CLOSINGREPORT,testAccount.Id,testConsutlingJob.Id,testContact.Id,testuser.Id,true);

            Date sow = Date.today().toStartOfWeek().addDays(7);
            Date eow = Date.today().toStartOfWeek().addDays(13);
            String sowstring = Datetime.newInstance(sow.year(), sow.month(), sow.day()).format('yyyy-MM-dd');
            String eowstring = Datetime.newInstance(eow.year(), eow.month(), eow.day()).format('yyyy-MM-dd');
            Test.startTest();
            String query = 'SELECT Id,Name,TR1__Start_Date__c,TR1__End_Date__c,TR1__Job__c,TR1__Person_Placed__c,TR1__Account__c,TR1__Timesheet_Approver__c,TR1__Timesheet_Second_Approver__c,TR1__Bill_Rate__c,TR1__Pay_Rate__c, TR1__Payroll_Type__c, Timesheet_Frequency__c FROM TR1__Closing_Report__c WHERE Id = \''+testClosingReport.id+'\' AND TR1__Assignment_Ended__c=\'No\' and Timesheet_Frequency__c =\'weekly\' and  (RecordTypeId = \'';
            query += TestDataUtility.CONSULTING_RECORDTYPE_CLOSINGREPORT + '\') AND TR1__Generate_Timesheet__c = true AND ((TR1__Start_Date__c <= ' + sowstring + ' AND (TR1__End_Date__c >= ' + sowstring + ' OR TR1__End_Date__c = null)) OR (TR1__Start_Date__c >= ' + sowstring + ' AND TR1__Start_Date__c <= ' + eowstring + ' AND (TR1__End_Date__c >= ' + sowstring + ' OR TR1__End_Date__c = null)))';

            ID batchprocessid = Database.executeBatch(new CreateTimesheetsCustomWeekly(query,sow),50);
            Test.stopTest();
        }
    }

    public static testMethod void Test2(){

        User testUser = TestDataUtility.createUser(true);
        system.runAs(testUser){

            Account testAccount = TestDataUtility.createAccount(true);

            Contact testContact = TestDataUtility.createContact(testAccount.id,false);
            testContact.Compliance_Owner__c = testUser.Id;
            testContact.Year_Key_Stage__c = 'KS1';
            testContact.Compliance_Status__c = 'Perm';
            testContact.Pay_Type__c = 'Perm';
            testContact.Trained_As__c = 'Instructor';
            testContact.TR1__Candidate_Status__c = 'Prospect';
            testContact.Qualified_Schools_Candidate__c ='YES';
            insert testContact;

            TR1__Job__c testConsutlingJob = TestDataUtility.createJob(TestDataUtility.CONSULTING_RECORDTYPE_JOB,testAccount.id,true);
            

            TR1__Closing_Report__c testClosingReport = TestDataUtility.createClosingReport(TestDataUtility.CONSULTING_RECORDTYPE_CLOSINGREPORT,testAccount.Id,testConsutlingJob.Id,testContact.Id,testuser.Id,true);

            Date sow = Date.today().toStartOfWeek().addDays(7);
            Date eow = Date.today().toStartOfWeek().addDays(13);
            String sowstring = Datetime.newInstance(sow.year(), sow.month(), sow.day()).format('yyyy-MM-dd');
            String eowstring = Datetime.newInstance(eow.year(), eow.month(), eow.day()).format('yyyy-MM-dd');

            Test.startTest();

            String query = 'SELECT Id,Name,TR1__Start_Date__c,TR1__End_Date__c,TR1__Job__c,TR1__Person_Placed__c,TR1__Account__c,TR1__Timesheet_Approver__c,TR1__Timesheet_Second_Approver__c,TR1__Bill_Rate__c,TR1__Pay_Rate__c, TR1__Payroll_Type__c, Timesheet_Frequency__c FROM TR1__Closing_Report__c WHERE Id = \''+testClosingReport.id+'\' AND TR1__Assignment_Ended__c=\'No\' and Timesheet_Frequency__c =\'weekly\' and  (RecordTypeId = \'';
            query += TestDataUtility.CONSULTING_RECORDTYPE_CLOSINGREPORT + '\') AND TR1__Generate_Timesheet__c = true AND ((TR1__Start_Date__c <= ' + sowstring + ' AND (TR1__End_Date__c >= ' + sowstring + ' OR TR1__End_Date__c = null)) OR (TR1__Start_Date__c >= ' + sowstring + ' AND TR1__Start_Date__c <= ' + eowstring + ' AND (TR1__End_Date__c >= ' + sowstring + ' OR TR1__End_Date__c = null)))';

            ScheduleCreateTimesheetsCustomWeekly sch = New ScheduleCreateTimesheetsCustomWeekly();
            String constr = '0 0 0 3 9 ? 2022';
            system.schedule('CreateTimesheetsCustomWeekly',constr,sch);
            
            // For test coverage for TimesheetUtility class 
            Set<Id> jobIds = New Set<Id> {testConsutlingJob.Id};
            TimesheetUtility.GetHolidaysAgaintsVacancy(jobIds);
            TimesheetUtility.GetHolidaysAgaintsVacancy(jobIds);
            Map<Id, Set<Date>> mapJobAgainstSetOfWeekEndDate = new Map<Id, Set<Date>>();
            Set<Date> dateSet =  new Set<Date>();
            dateSet.add(Date.Today().toStartOfWeek());
            mapJobAgainstSetOfWeekEndDate.put(testClosingReport.TR1__Job__c, dateSet);
            TimesheetUtility.CheckIfCompleteWeekIsHoliday(testClosingReport, Date.Today().toStartOfWeek(), mapJobAgainstSetOfWeekEndDate);


        }
    }
}