src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Half_Day_Charge_Rate__c</fullName>
        <label>Half Day Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Charge_Rate__c</fullName>
        <label>Hour Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Pay_Rate__c</fullName>
        <label>Hour Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Hour_Charge_Rate__c</fullName>
        <label>Maximum Hour Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Pay_Rate__c</fullName>
        <label>Maximum Hour Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Payroll_number__c</fullName>
        <formula>TR1__Consultant__r.Payroll_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payroll number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Closing_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report</label>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Changed By Payroll</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Unsubmitted</fullName>
                    <default>true</default>
                    <label>Unsubmitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Regular_Hours__c</fullName>
        <label>Regular Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>TR1__Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Vacation_Hours__c</fullName>
        <label>Vacation Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Timesheet Detail</label>
    <nameField>
        <displayFormat>TS-{MM}{DD}{YY}-{0}</displayFormat>
        <label>Timesheet Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RC_HolidayAccrualTest.cls
@isTest
private class RC_HolidayAccrualTest {

    private static testMethod void testing() {
        
        TR1__Job__c objJob = RC_UtilityClass.insertJob();
      
        User objUserCommunityContactType2 = RC_UtilityClass.returnCommunityContactTypeUser('c&c', 'testcc');
        system.assertEquals(1, [Select id from User where Id =: objUserCommunityContactType2.Id].size());

        User objUserCommunityContactType = RC_UtilityClass.returnCommunityContactTypeUser('candidate', 'testcand');
    	system.assertEquals(1, [Select id from User where Id =: objUserCommunityContactType.Id].size());

        TR1__Closing_Report__c objClosingReport = RC_UtilityClass.returnClosingReportWithApprover(objUserCommunityContactType2, objUserCommunityContactType);
        objClosingReport.Maximum_Half_Day_Charge_Rate__c = 9;
        objClosingReport.Maximum_Hour_Charge_Rate__c = 8;
        objClosingReport.Maximum_Hour_Pay_Rate__c = 7;
        update objClosingReport;
        Account acc=TestUtility.getAccountDetail();
        Contact objContact = new Contact(Firstname = 'Test', Lastname = 'Conatct1',Payroll_Number__c='12345');
        insert objContact;
            
        Test.startTest();
        TR1__Timesheet__c  objTimesheet = RC_UtilityClass.insertTimeSheet(objJob.Id);
        objTimesheet.TR1__Client__c = acc.Id;
        objTimesheet.TR1__Consultant__c = objContact.Id;
        objTimesheet.TR1__Closing_Report__c = objClosingReport.Id;
        update objTimesheet;
        
        TR1__Timesheet_Detail__c objTimesheetDetail = RC_UtilityClass.insertTimeSheetDetail(objTimesheet.Id);
        objTimesheetDetail.TR1__Vacation_Hours__c = 4;
        objTimesheetDetail.TR1__Regular_Hours__c = 4;
        objTimesheetDetail.TR1__Timesheet__c = objTimesheet.Id;
        update objTimesheetDetail;
        
        objTimesheet.TR1__Status__c = 'Approved';
        update objTimesheet;
          
        objTimesheet.TR1__Status__c = 'Unsubmitted';
        update objTimesheet;
        
        objTimesheet.TR1__Status__c = 'Approved';
        update objTimesheet;
        
        delete objTimesheetDetail;
            Test.stopTest();
        } 

}