src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agreed_D2D_Charge_Rate__c</fullName>
        <label>Standard Day Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Candidate_Availability__c.object
<CustomObject>
    <description>Object to store the availability of a candidate for a start to end date.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Candidate Availabilities</relationshipLabel>
        <relationshipName>Candidate_Availabilitys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                    <default>true</default>
                    <label>Full Day</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Candidate Availability</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>CA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Closing_Report_Schedule__c.object
<CustomObject>
    <description>A schedule record is created for each day a Candidate is assigned to the Vacancy</description>
    <fields>
        <fullName>Candidate_Availability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Availability</label>
        <referenceTo>Candidate_Availability__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closing_Report__c</fullName>
        <label>Closing Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TR1__Closing_Report__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pay_Type__c</fullName>
        <label>Pay Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
                <value>
                    <fullName>Extra Duties</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trial Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vacancy_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vacancy Schedule</label>
        <referenceTo>Vacancy_D2D__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Closing Report Schedule</label>
    <nameField>
        <displayFormat>CRS-{0000000}</displayFormat>
        <label>CRS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pay_Type__c</fullName>
        <label>Pay Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trial_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trial Day?</label>
        <type>Checkbox</type>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Vacancies - Qualified</relationshipLabel>
        <relationshipName>Vacancies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Pay Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Closed_Date__c</fullName>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Timesheet Approver)</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vacancy_D2D__c.object
<CustomObject>
    <fields>
        <fullName>Closing_Report_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report Schedule</label>
        <referenceTo>Closing_Report_Schedule__c</referenceTo>
        <relationshipLabel>Vacancy Schedules</relationshipLabel>
        <relationshipName>Vacancy_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vacancy_Date__c</fullName>
        <inlineHelpText>Date for which this vacancy is applicable</inlineHelpText>
        <label>Vacancy Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vacancy__c</fullName>
        <label>Vacancy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TR1__Job__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Vacancy_D2Ds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vacancy Schedule</label>
    <nameField>
        <displayFormat>D2D-{000000}</displayFormat>
        <label>D2D Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TRS_CreateCRSctrl.cls
public class TRS_CreateCRSctrl {
    Public TR1__Job__c objVacc{get;set;}
    Public TR1__Closing_Report__c objCR{get;set;}
    Public Closing_Report_Schedule__c objCRS{get;set;}
    Public Date selectedDate {get;set;}
    Public String contact1 {get;set;} 
    Public List<Candidate_Availability__c> canAvail {get;set;}
    Public List <Vacancy_D2D__c> vacAvail  {get;set;}
    Public String jsdID ;
    Public String csdID ;
    Public List <TR1__Closing_Report__c> objCRTemp;
    Public Boolean noRecordSelected ;
    Public TRS_CreateCRSctrl(ApexPages.StandardController ctrl) {
        objCRS = new Closing_Report_Schedule__c ();
        objCR= new TR1__Closing_Report__c();
        objCRTemp= new List <TR1__Closing_Report__c>();
        canAvail  = new List<Candidate_Availability__c>();
        vacAvail= new List<Vacancy_D2D__c>();
        if(ctrl == null || ctrl.getId() == null) {
          noRecordSelected = true;
          Utility.AddErrormessage('No Vacancy Selected');
          return;
        }
        else{
          String vaccId = ctrl.getId();
          objVacc = [Select Id,Name,TR1__Account__r.BillingPostalCode,TR1__Account__r.BillingCity,TR1__Account__r.BillingStreet,TR1__Account__c,Timesheet_Approver__c,TR1__Closed_Date__c,TR1__Account__r.Agreed_D2D_Charge_Rate__c,TR1__Account__r.Invoice_Contact__c from TR1__Job__c where Id=:vaccId];
          //objCRS.Closing_Report__c = ctrl.getId();
        }
        //selectedDate  = Date.today();
        jsdID = '';
        csdID = '';
    }
    public PageReference Cancel() {
        return new PageReference('/'+objVacc.Id).setRedirect(true);
    }
    public PageReference RedirectTocalendar() { 
         if(!string.isBlank(objCR.TR1__Person_Placed__c))
            return new PageReference('/apex/TRS_CandidateCalendar?contactId='+objCR.TR1__Person_Placed__c);
        else{
            Utility.AddErrormessage('Please select person placed first.');
            return null;
        }
            
    }
    public PageReference FetchCandidateId() { 
        if(Apexpages.currentPage().getParameters().containsKey('contact1') && ApexPages.currentPage().getParameters().get('contact1 ') != '')
            {
              contact1 = ApexPages.currentPage().getParameters().get('contact1 ');
            }
        return null;
    }
    public PageReference saveClosingReportSch() {
        try{
                // Utility.AddErrormessage('Person placed .'+objCR.TR1__Person_Placed__c);
                // return null;
                List<Closing_Report_Schedule__c> crsList =new List<Closing_Report_Schedule__c>();
                canAvail = [Select Id ,Name, Status__c,Start_Date_Time__c,End_Date_Time__c,Start_Date__c,Candidate__c from Candidate_Availability__c where Start_Date__c= :objCRS.Schedule_Date__c and  Candidate__c = :objCR.TR1__Person_Placed__c];
                vacAvail = [Select Id ,Name, Shift__c,Vacancy_Date__c,Start_Date_Time__c,End_Date_Time__c,Vacancy__c from Vacancy_D2D__c where Vacancy_Date__c= :objCRS.Schedule_Date__c and Vacancy__c = :objVacc.Id  ];
                objCRTemp = [Select Id,Name,TR1__Job__c,TR1__Person_Placed__c,TR1__End_Date__c,Contract_End_Date__c,TR1__Start_Date__c from TR1__Closing_Report__c where TR1__Person_Placed__c =:objCR.TR1__Person_Placed__c AND  TR1__Job__c =:objVacc.Id AND TR1__Start_Date__c<= :objCRS.Schedule_Date__c AND TR1__End_Date__c >= :objCRS.Schedule_Date__c limit 1 ];
                if(objCRTemp.size()>0){
                     if(canAvail.size()>0){
                       if(vacAvail.size()==0){
                            for(Candidate_Availability__c candt: canAvail){                         
                                    Vacancy_D2D__c vacc= new Vacancy_D2D__c(Status__c='Open',Shift__c = 'Hourly',Start_Date_Time__c=candt.Start_Date_Time__c,End_Date_Time__c=candt.End_Date_Time__c,Vacancy__c=objVacc.Id,Vacancy_Date__c=candt.Start_Date__c);
                                    vacAvail.add(vacc);
                             }
                         insert vacAvail;
                        }
                         
                        for(Candidate_Availability__c candt: canAvail){
                            for(Vacancy_D2D__c vcc: vacAvail){
                                if((candt.Start_Date_Time__c <= vcc.Start_Date_Time__c && vcc.End_Date_Time__c <= candt.End_Date_Time__c)&&(candt.Start_Date_Time__c !=Null&& vcc.Start_Date_Time__c!=Null  && vcc.End_Date_Time__c!=Null&&candt.End_Date_Time__c!=Null)){
                                    Closing_Report_Schedule__c crs1= new Closing_Report_Schedule__c();
                                    crs1.Closing_Report__c  =objCRTemp[0].Id;
                                    crs1.Schedule_Date__c = objCRS.Schedule_Date__c;
                                    crs1.Candidate_Availability__c = candt.Id;
                                    crs1.Vacancy_Schedule__c = vcc.Id;
                                    crs1.Status__c  = 'Booked';
                                    crs1.Trial_Day__c = True;
                                    crsList.add(crs1);
                                }else{
                                    Continue;      
                                }
                            }
                        }
                        if(crsList.size()>0)
                        insert crsList;
                        else{
                            Utility.AddErrormessage('No Matching Available slots found for job/candidate on this closing report .');
                                    return null;  
                        }
                        return new PageReference('/'+objCRTemp[0].Id).setRedirect(true);
                    }else{
                        Utility.AddErrormessage('Booking failed as job/Candidate does not have availability on date you selected .');
                        return null;        
                    }     
                }else{
                    TR1__Closing_Report__c closingReport = new TR1__Closing_Report__c();
                    closingReport.TR1__Job__c = objVacc.Id;
                    //closingReport.Pay_Type__c = vacancy.Timesheet_Pay_Type__c;
                    closingReport.TR1__Person_Placed__c = objCR.TR1__Person_Placed__c;
                    closingReport.Invoicing_Person__c = objVacc.TR1__Account__r.Invoice_Contact__c;
                    closingReport.TR1__Start_Date__c = objCRS.Schedule_Date__c;
                    closingReport.TR1__End_Date__c = objCRS.Schedule_Date__c;
                    closingReport.RecordTypeId = Utility.CONSULTING_RTID;
                    closingReport.TR1__Bill_Rate__c = objVacc.TR1__Account__r.Agreed_D2D_Charge_Rate__c;
                    closingReport.TR1__Job_Credit__c = userinfo.getUserId();
                    //closingReport.TR1__Pay_Rate__c = payRate;
                    closingReport.TR1__Job_Percentage__c = 100;
                    closingReport.TR1__Timesheet_Approver__c = objVacc.Timesheet_Approver__c;
                    closingReport.TR1__Account__c = objVacc.TR1__Account__c;
                    closingReport.TR1__Billing_Street__c = objVacc.TR1__Account__r.BillingStreet; 
                    closingReport.TR1__Billing_City__c = objVacc.TR1__Account__r.BillingCity;
                    closingReport.TR1__Billing_Zip_Code__c = objVacc.TR1__Account__r.BillingPostalCode;
                    closingReport.Maximum_Day_Pay_Rate__c = objCR.Maximum_Day_Pay_Rate__c ;
                    closingReport.Maximum_Day_Charge_Rate__c = objCR.Maximum_Day_Charge_Rate__c;
                    closingReport.Maximum_Half_Day_Pay_Rate__c = objCR.Maximum_Half_Day_Pay_Rate__c ;
                    closingReport.Maximum_Half_Day_Charge_Rate__c = objCR.Maximum_Half_Day_Charge_Rate__c;
                    closingReport.Maximum_Hour_Pay_Rate__c = objCR.Maximum_Hour_Pay_Rate__c;
                    closingReport.Maximum_Hour_Charge_Rate__c = objCR.Maximum_Hour_Charge_Rate__c;
                    objCRTemp.add(closingReport);
                    ClosingReportTriggerHelper.FromJobboard = True;
                    insert objCRTemp;
                    if(canAvail.size()>0 ){
                        if(vacAvail.size()==0){
                            for(Candidate_Availability__c candt: canAvail){                         
                                    Vacancy_D2D__c vacc= new Vacancy_D2D__c(Status__c='Open',Shift__c = 'Hourly',Start_Date_Time__c=candt.Start_Date_Time__c,End_Date_Time__c=candt.End_Date_Time__c,Vacancy__c=objVacc.Id,Vacancy_Date__c=candt.Start_Date__c);
                                    vacAvail.add(vacc);
                             }
                         insert vacAvail;
                        }
                        for(Candidate_Availability__c candt: canAvail){
                            for(Vacancy_D2D__c vcc: vacAvail){
                                if((candt.Start_Date_Time__c <= vcc.Start_Date_Time__c && vcc.End_Date_Time__c <= candt.End_Date_Time__c)&&(candt.Start_Date_Time__c !=Null&& vcc.Start_Date_Time__c!=Null  && vcc.End_Date_Time__c!=Null&&candt.End_Date_Time__c!=Null)){
                                    Closing_Report_Schedule__c crs1= new Closing_Report_Schedule__c();
                                    crs1.Closing_Report__c  = objCRTemp[0].Id;
                                    crs1.Schedule_Date__c = objCRS.Schedule_Date__c;
                                    crs1.Candidate_Availability__c = candt.Id;
                                    crs1.Vacancy_Schedule__c = vcc.Id;
                                    crs1.Status__c  = 'Booked';
                                    crs1.Trial_Day__c = True;
                                    crsList.add(crs1);
                                }else{
                                    Continue;      
                                }
                            }
                        }
                        if(crsList.size()>0)
                        insert crsList;
                        else{
                            Utility.AddErrormessage('No Matching Available slots found for job/candidate on this closing report .');
                                    return null;  
                        }
                        //objCRS.Schedule_Date__c = selectedDate;
                        
                        return new PageReference('/'+objCRTemp[0].Id).setRedirect(true);
                    }else{
                        Utility.AddErrormessage('Booking failed as job/Candidate does not have availability on date you selected .');
                        return null;        
                    }
                }
               
                
        }catch(Exception ex){
            Utility.AddErrormessage('Exception occured '+ex.getmessage()+'Line Number '+ex.getLinenumber());
            return null;
        }
    }

}