src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Google_Map_API__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>Google MAP API</description>
        <inlineHelpText>Google MAP API</inlineHelpText>
        <label>API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isExecuteAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Execute for Account?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isExecuteContact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Execute for Contact?</label>
        <type>Checkbox</type>
    </fields>
    <label>Google Map API</label>
</CustomObject>

src/classes/GeoLocationAccountTriggerTest.cls
@isTest
private class GeoLocationAccountTriggerTest {
    
    public static testmethod void unitTest(){
        Google_Map_API__c gApi = Google_Map_API__c.getInstance();
        gApi.isExecuteAccount__c = true;
        gApi.isExecuteContact__c = true;
        gApi.API_Key__c = 'TestClassOnly';
        upsert gApi;
        
        Test.startTest();
        Account acc = new Account(Name='CVP', BillingStreet  ='123', BillingCity ='test city', BillingState ='test county', BillingPostalCode  = '234345', BillingCountry  = 'test Country',
                                  shippingStreet = '1233',shippingCity='Test City',ShippingState='Test State',shippingPostalCode='564533',shippingCountry='Test Country');
        
        insert acc;
        
        acc.BillingStreet='Test1';
        acc.BillingCity='Test1';
        acc.BillingState='London';
        acc.BillingCountry='United Kingdom';
        acc.BillingPostalCode='EC2R 8DM';
        update acc;
        
        Test.stopTest();
        
    }
}