src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Total_Days_Worked__c</fullName>
        <label>Total Days Worked</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Sector1__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Children&apos;s Centre</fullName>
                </value>
                <value>
                    <fullName>College (6th)</fullName>
                </value>
                <value>
                    <fullName>Further Education</fullName>
                </value>
                <value>
                    <fullName>HMP Prison</fullName>
                </value>
                <value>
                    <fullName>Infant</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>Overseas Client</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Private Nursery</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Special Needs</fullName>
                </value>
                <value>
                    <fullName>Tech College</fullName>
                </value>
                <value>
                    <fullName>Through School</fullName>
                </value>
                <value>
                    <fullName>Virtual School</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Timesheets (Timesheet Approver)</relationshipLabel>
        <relationshipName>Timesheets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Approvers_Notes__c</fullName>
        <inlineHelpText>Visible to approver and payroll.</inlineHelpText>
        <label>Approver Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TR1__Assignment_Continuing__c</fullName>
        <label>Assignment Continuing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Client_Name__c</fullName>
        <formula>TR1__Client__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Closing_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report</label>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Consultant_Name__c</fullName>
        <formula>TR1__Consultant__r.LastName &amp; &quot;, &quot; &amp;  TR1__Consultant__r.FirstName</formula>
        <label>Consultant Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Consultants_Notes__c</fullName>
        <inlineHelpText>Visible to everyone.</inlineHelpText>
        <label>Consultant Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Order__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Recruiter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recruiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Changed By Payroll</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Unsubmitted</fullName>
                    <default>true</default>
                    <label>Unsubmitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Total_Days_Worked__c</fullName>
        <label>Total Days Worked</label>
        <summaryFilterItems>
            <field>TR1__Timesheet_Detail__c.TR1__Regular_Hours__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TR1__Total_Double_Time_Hours__c</fullName>
        <label>Total Double Time Hours</label>
        <summarizedField>TR1__Timesheet_Detail__c.TR1__Double_Time_Hours__c</summarizedField>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TR1__Total_Hours__c</fullName>
        <formula>TR1__Total_Regular_Hours__c + TR1__Total_Overtime_Hours__c + TR1__Total_Double_Time_Hours__c + TR1__Total_Vacation_Hours__c + TR1__Total_Sick_Time_Hours__c + TR1__Total_Holiday_Hours__c + TR1__Total_Travel_Hours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Total_Overtime_Hours__c</fullName>
        <label>Total Overtime Hours</label>
        <summarizedField>TR1__Timesheet_Detail__c.TR1__Overtime_Hours__c</summarizedField>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TR1__Total_Regular_Hours__c</fullName>
        <label>Total Regular Hours</label>
        <summarizedField>TR1__Timesheet_Detail__c.TR1__Regular_Hours__c</summarizedField>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TR1__Total_Sick_Time_Hours__c</fullName>
        <label>Total Sick Time Hours</label>
        <summarizedField>TR1__Timesheet_Detail__c.TR1__Sick_Time_Hours__c</summarizedField>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TR1__Total_Vacation_Hours__c</fullName>
        <label>Total Vacation Hours</label>
        <summarizedField>TR1__Timesheet_Detail__c.TR1__Vacation_Hours__c</summarizedField>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timesheet_Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timesheet_Approved_Date_Time__c</fullName>
        <label>Timesheet Approved Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>TR1__Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Timesheet Detail</label>
    <nameField>
        <displayFormat>TS-{MM}{DD}{YY}-{0}</displayFormat>
        <label>Timesheet Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimesheetPrintController_v1.cls
public  class TimesheetPrintController_v1 {
  
  
    public String[] timesheetIds                           {get;set;}  
    public transient List<TR1__Timesheet__c> timesheetList                      {get;set;}
    public transient List<TimesheetPrintWrapper> TimesheetPrintWrapperList          {get;set;}
    public integer LastPdf {get;set;}
    
    public integer getPageCount(){
        return TimesheetPrintWrapperList.size();
    } 
  
    public TimesheetPrintController_v1() {
    
        TimesheetPrintWrapperList = new List<TimesheetPrintWrapper> ();
        system.debug('TimesheetList: '+System.currentPageReference().getParameters().get('timesheetIds'));
        String[] timesheetIds = ((String)System.currentPageReference().getParameters().get('timesheetIds')).split(';');
     
        timesheetList = [Select t.TR1__Consultant_Name__c, t.TR1__Consultants_Notes__c,  t.TR1__Status__c, t.TR1__Week_Ending__c, t.TR1__Assignment_Continuing__c, 
                            t.TR1__Recruiter__c, TR1__Total_Hours__c, TR1__Total_Regular_Hours__c, TR1__Total_Overtime_Hours__c, TR1__Total_Double_Time_Hours__c, 
                            TR1__Total_Sick_Time_Hours__c, TR1__Total_Vacation_Hours__c,TR1__Approver__c, t.TR1__Approvers_Notes__c, t.Id, t.TR1__Job_Order__c,
                            Timesheet_Approved_Date_Time__c, Timesheet_Approved_By__c, Name, TR1__Total_Days_Worked__c,
                            t.TR1__Client_Name__c,t.TR1__Client__r.BillingPostalCode ,
                            t.TR1__Job_Order__r.name,t.TR1__Job_Order__r.TR1__Job_Title__c,t.TR1__Job_Order__r.Sector1__c ,t.TR1__Closing_Report__r.TR1__Job__r.TR1__Account__r.RecordType.Name,
                            t.TR1__Closing_Report__c,t.TR1__Closing_Report__r.TR1__Job_Credit__c,t.TR1__Closing_Report__r.TR1__Job_Credit__r.name,t.TR1__Closing_Report__r.TR1__PO_Number__c,
                            TR1__Approver__r.name, Timesheet_Approved_By__r.Name,(Select TR1__Date__c, TR1__Day__c, TR1__Double_Time_Hours__c, Id,
                            TR1__Overtime_Hours__c, TR1__Regular_Hours__c, TR1__Sick_Time_Hours__c,TR1__Timesheet__c, TR1__Vacation_Hours__c, TR1__Expenses__c,
                            Start_Time__c,End_Time__c
                            From TR1__Timecards__r where Closing_Report_Schedule__c != null order by TR1__date__c asc) from TR1__Timesheet__c t where id in : timesheetIds];       

        
        calculatehours();
    }
  
    public void calculatehours(){
        integer lstCount = 0;              
        for(TR1__Timesheet__c timesheet : timesheetList) {
            TimesheetPrintWrapper wrapper = new TimesheetPrintWrapper(timesheet , ++lstCount)  ;
            for(TR1__Timesheet_Detail__c td : timesheet.TR1__Timecards__r){
                if(td.TR1__Double_Time_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Double_Time_Hours__c;
                if(td.TR1__Expenses__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Expenses__c;
                if(td.TR1__Overtime_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Overtime_Hours__c;
                if(td.TR1__Regular_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Regular_Hours__c;
                if(td.TR1__Sick_Time_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Sick_Time_Hours__c;
                if(td.TR1__Vacation_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Vacation_Hours__c;         
            }
            TimesheetPrintWrapperList.add(wrapper);
        }        
        LastPdf = TimesheetPrintWrapperList.size(); 
    }  
  
    public class TimesheetPrintWrapper {
    
        public Double totalHours               {get;set;}
        public integer index                 {get;set;} 
        public TR1__Timesheet__c timesheet      {get;set;}
     
        public TimesheetPrintWrapper(TR1__Timesheet__c timesheet,integer index) {
            this.timesheet =  timesheet;
            totalHours = 0;
            this.index = index;
       
        }
    }
}