src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Barred_List_Date_Checked__c</fullName>
        <label>Barred List Date Checked</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clear_DBS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clear DBS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DBS_Checked_Online__c</fullName>
        <label>DBS Last Checked Online</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DBS_Date_of_Issue__c</fullName>
        <label>DBS Date of Issue (Old)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DBS_Disclosure_ID_Number__c</fullName>
        <label>DBS Disclosure ID Number</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_1_ID_Type__c</fullName>
        <label>Group 1 ID Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Passport</fullName>
                </value>
                <value>
                    <fullName>Current DL (Full/ Prov.) - Photocard</fullName>
                </value>
                <value>
                    <fullName>Original Birth Cert. issued within 12 months of birth</fullName>
                </value>
                <value>
                    <fullName>Biometric Residence Permit</fullName>
                </value>
                <value>
                    <fullName>Adoption Certificate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Letter_of_Good_Conduct_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Letter of Good Conduct Received</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NCTL_Checked_Date__c</fullName>
        <label>NCTL Checked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NCTL_Number__c</fullName>
        <label>NCTL Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NQT_Induction_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NQT Induction Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Overseas_Police_Check__c</fullName>
        <label>Overseas Police Check</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>With Police</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QTLS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QTLS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QTS_Awarded_Date__c</fullName>
        <inlineHelpText>Candidate must complete induction within 5 years of QTS Awarded Date.</inlineHelpText>
        <label>QTS Awarded Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SET_Checked_Date__c</fullName>
        <label>SET Checked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <recordTypes>
        <fullName>Photo</fullName>
        <active>false</active>
        <label>Photo</label>
    </recordTypes>
    <recordTypes>
        <fullName>Qualifications</fullName>
        <active>false</active>
        <label>Qualifications</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <formula>TR1__Job__r.TR1__Contact__r.FirstName &amp; &quot; &quot; &amp;  TR1__Job__r.TR1__Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestConfirmationPageController.cls
public with sharing class TestConfirmationPageController {
    
    public Id crId {get;set;}
    public String group1Id {get;set;}
    public date barredListDateChecked {get;set;}
    public date dbsIssueDate {get;set;}
    public String dbsDisclosureIdnumber {get;set;}
    public date dbsCheckedOnlineDate {get;set;}
    public boolean clearDbs {get;set;}
    public String nameOfcandidate {get;set;}
    public String nameOfclient {get;set;}
    public String prohibitionFromTeachingCheck {get;set;}
    public String nctlNumber {get;set;}
    public date nctlCheckedDate {get;set;}
    public date qtsAwardedDate {get;set;}
    public boolean nqtInductionComplete {get;set;}
    public date setCheckedDate {get;set;}
    public boolean qtls {get;set;}
    public String overseasChecksTab {get;set;}
    public String overseasPoliceCheck {get;set;}
    public boolean letterOfGoodConductReceived {get;set;}
    public String qualificationStatusActive {get;set;} // Enter YES if Qualification --Status = Active
    public String disqualification {get;set;}//[Yes/No] Disqualification by association check
    public Attachment personPlacedPhoto {get; set;}
    public String photoImgUrl {get; set;}
    
    public String Testval {get; set;}
    public String recordId {get; set;}

    public TestConfirmationPageController(ApexPages.StandardController sc){   
        try{ 
        
            // Testval = 'Page Loadedvaluepopopo';

            System.debug('recordId=>'+recordId);

    
        // url='https://' + headerdata+ urlvalue;

        crId = ApexPages.currentPage().getParameters().get('id');
        System.debug('crId==>'+crId);
        
        Map<string,TR1__Associated_Qualification__c> aqMap = new Map<string,TR1__Associated_Qualification__c>();
        
        if(String.isBlank(crId)){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'Closing Report Id not found.'));
            return;
        }
        
        List<TR1__Closing_Report__c> crList = [SELECT Id, Name, TR1__Person_Placed__c, TR1__Account__r.Name FROM TR1__Closing_Report__c WHERE Id =:crId];
        
        if(crList.size()==0){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'Closing Report record not found.'));
            return;
        }
        
        List<contact> contactList = [SELECT Id, Name  FROM Contact WHERE Id= :crList[0].TR1__Person_Placed__c];
        
        if(contactList.size()==0){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'Contact record for person placed not found.'));
            return;
        }
        
        List<TR1__Associated_Qualification__c> aqList = [SELECT Id, Name, TR1__Contact__c,TR1__Qualification__r.Name, Group_1_ID_Type__c, Barred_List_Date_Checked__c, DBS_Date_of_Issue__c, DBS_Disclosure_ID_Number__c, 
                                                                DBS_Checked_Online__c, Clear_DBS__c, NCTL_Number__c, NCTL_Checked_Date__c, QTS_Awarded_Date__c, NQT_Induction_Complete__c, SET_Checked_Date__c,
                                                                QTLS__c, Overseas_Police_Check__c, Letter_of_Good_Conduct_Received__c,TR1__Status__c 
                                                         FROM TR1__Associated_Qualification__c WHERE TR1__Contact__c = :contactList[0].Id]; 
        Id photoQualificationId = null;
        for(TR1__Associated_Qualification__c a : aqList ){
            AqMap.put(a.TR1__Qualification__r.Name,a );
            // to get photo qualification Id
            if(a.TR1__Qualification__r.Name == 'Photo' && a.TR1__Status__c != null  && a.TR1__Status__c != 'Requested')
                photoQualificationId = a.Id;
        }
        
        system.debug('========photoQualificationId========'+photoQualificationId);
        if(photoQualificationId != null ){
            
            ID personPlacedPhotoIdd = [SELECT Id,Name,parentId FROM Attachment WHERE parentId =: photoQualificationId LIMIT 1].Id;
            if(personPlacedPhotoIdd != null)
                photoImgUrl = '/servlet/servlet.FileDownload?file='+personPlacedPhotoIdd;
            else
                photoImgUrl = '';
        }
        else
            photoImgUrl = '';
            
        
        group1Id = aqMap.containsKey('DBS') ? aqMap.get('DBS').Group_1_ID_Type__c : '';      
        barredListDateChecked = aqMap.containsKey('Barred List') ? aqMap.get('Barred List').Barred_List_Date_Checked__c: date.TODAY();
        //dbsIssueDate= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').DBS_Date_of_Issue__c : date.TODAY();
        dbsDisclosureIdnumber= aqMap.containsKey('DBS') ? aqMap.get('DBS').DBS_Disclosure_ID_Number__c : '';
        //dbsCheckedOnlineDate= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').DBS_Checked_Online__c : date.TODAY();
        //clearDbs= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').Clear_DBS__c : False;
        nameOfcandidate= contactList.size()>0 ? contactList[0].Name : '';
        nameOfclient= crList.size()>0 ? crList[0].TR1__Account__r.Name : '';
        //prohibitionFromTeachingCheck= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').Overseas_Police_Check__c : ''; 
        nctlNumber= aqMap.containsKey('Overseas Teacher Qualifications') ? aqMap.get('Overseas Teacher Qualifications').NCTL_Number__c : '';
        //nctlCheckedDate= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').NCTL_Checked_Date__c : date.TODAY();
        qtsAwardedDate= aqMap.containsKey('Overseas Teacher Qualifications') ? aqMap.get('Overseas Teacher Qualifications').QTS_Awarded_Date__c : date.TODAY();
        //nqtInductionComplete= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').NQT_Induction_Complete__c : False;
        //setCheckedDate= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').SET_Checked_Date__c : date.TODAY();
        qtls= aqMap.containsKey('perm Qualification') ? aqMap.get('perm Qualification').QTLS__c : false;  
        //overseasChecksTab= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').Overseas_Police_Check__c : '';  
        overseasPoliceCheck= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').Overseas_Police_Check__c : '';
        letterOfGoodConductReceived= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').Letter_of_Good_Conduct_Received__c : false;
        //qualificationStatusActive= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').Overseas_Police_Check__c : '';
        //disqualification= aqMap.containsKey('Overseas Police Check') ? aqMap.get('Overseas Police Check').Overseas_Police_Check__c : '';
        }
        Catch(Exception e){
            system.debug('==================Exception==='+e.getMessage());
        }
    }
}