src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Candidate_Availability__c.object
<CustomObject>
    <description>Object to store the availability of a candidate for a start to end date.</description>
    <fields>
        <fullName>Applicable_Days__c</fullName>
        <label>Applicable Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Candidate Availabilities</relationshipLabel>
        <relationshipName>Candidate_Availabilitys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
                <value>
                    <fullName>Interview</fullName>
                </value>
                <value>
                    <fullName>Working for Another Agency</fullName>
                </value>
                <value>
                    <fullName>Sick</fullName>
                </value>
                <value>
                    <fullName>Holiday</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Candidate Availability</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>CA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Type__c</fullName>
        <label>Booking Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                    <default>true</default>
                    <label>Daily</label>
                </value>
                <value>
                    <fullName>Long Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Bill_Rate__c</fullName>
        <label>Bill Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Pay_Rate__c</fullName>
        <label>Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_Days__c</fullName>
        <label>Applicable Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Booking_Type__c</fullName>
        <label>Booking Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Perm</fullName>
                </value>
                <value>
                    <fullName>Promotional Day</fullName>
                </value>
                <value>
                    <fullName>Long Term</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                    <default>true</default>
                    <label>Daily</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Vacancies - Qualified</relationshipLabel>
        <relationshipName>Vacancies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Friday_s_Shift__c</fullName>
        <label>Friday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Monday_s_Shift__c</fullName>
        <label>Monday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Saturday_s_Shift__c</fullName>
        <label>Saturday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sunday_s_Shift__c</fullName>
        <label>Sunday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Estimated_End_Date__c</fullName>
        <label>Estimated End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Estimated_Start_Date__c</fullName>
        <label>Estimated Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Thursday_s_Shift__c</fullName>
        <label>Thursday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tuesday_s_Shift__c</fullName>
        <label>Tuesday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wednesday_s_Shift__c</fullName>
        <label>Wednesday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_VacancyHelper.cls
@isTest
private class Test_VacancyHelper {
                     @TestSetup
static void initData()
{
   User u1=TestUtility.getUserDetail();
}
    
    @isTest static void test_method_one() {
         User u1=[Select Id,Name,Email from User where email='pb@ff1.com' Limit 1];
       System.runAs(u1){
        // Create Test Data
        Account[] accList = TestUtility.accList; 
        Contact[] conList = TestUtility.con;
        List<Candidate_Availability__c> candidateAvailabilityList=new List<Candidate_Availability__c>();
      candidateAvailabilityList=[Select Id, Name, Start_Date_Time__c, End_Date_Time__c from Candidate_Availability__c where Start_Date_Time__c != null and End_Date_Time__c != null]; 
        Test.startTest();

        TR1__Job__c jobRec = TestUtility.job;

        TRS_VacancyHelper.EXECUTED_UPDATE_D2D_VACANCY = false;
        
       
     Candidate_Availability__c ca=    new Candidate_Availability__c(Start_Date__c=System.Today().addDays(-40),End_Date__c=System.Today().addDays(-40), Candidate__c = conList[0].Id, Applicable_Days__c = 'Monday', Type__c = 'Available');
     ca.Start_Date_Time__c=TestUtility.formatDateTimefromDate(ca.Start_Date__c,'15:45'); 
        ca.End_Date_Time__c=TestUtility.formatDateTimefromDate(ca.End_Date__c,'23:30');
        insert ca;
        /*
        RecordType consulting = [Select Id from RecordType where SObjectType = 'TR1__Closing_Report__c' and Name = 'Consulting'];
        
        TR1__Closing_Report__c closingRep = new TR1__Closing_Report__c();
        closingRep.RecordTypeId = consulting.id;
        closingRep.TR1__Start_Date__c = System.Today().addDays(-60);
        closingRep.TR1__End_Date__c = System.Today();
        closingRep.TR1__Person_Placed__c = conList[0].Id;
        closingRep.TR1__Job__c = jobRec.Id;
        closingRep.TR1__Pay_Rate__c = 100.0;
        closingRep.TR1__Bill_Rate__c = 100.0;
        closingRep.Booking_Type__c = 'LT';
        insert closingRep;
        */
         
        // Update Vacancy Dates
        jobRec.TR1__Estimated_Start_Date__c = System.today().addDays(15);
        jobRec.TR1__Estimated_End_Date__c = System.today().addDays(30);
        update jobRec;

        TRS_VacancyHelper.EXECUTED_UPDATE_D2D_VACANCY = false;

        jobRec.TR1__Estimated_Start_Date__c = System.today().addDays(-10);
        jobRec.TR1__Estimated_End_Date__c = System.today().addDays(40);
        update jobRec;

        TRS_VacancyHelper.EXECUTED_UPDATE_D2D_VACANCY = false;

        jobRec.TR1__Estimated_End_Date__c = System.today().addDays(-5);
        jobRec.TR1__Estimated_End_Date__c = System.today().addDays(5);
        update jobRec;

        TRS_VacancyHelper.EXECUTED_UPDATE_D2D_VACANCY = false;

        jobRec.TR1__Estimated_End_Date__c = System.today().addDays(-50);
        jobRec.TR1__Estimated_End_Date__c = System.today().addDays(-30);
        update jobRec;

        TRS_VacancyHelper.EXECUTED_UPDATE_D2D_VACANCY = false;

        jobRec.TR1__Estimated_End_Date__c = System.today().addDays(10);
        jobRec.TR1__Estimated_End_Date__c = System.today().addDays(30);
        
        jobRec.Monday_s_Shift__c = 'AM';
        jobRec.Tuesday_s_Shift__c = 'AM';
        jobRec.Wednesday_s_Shift__c = 'AM';
        jobRec.Friday_s_Shift__c = 'AM';
        jobRec.Saturday_s_Shift__c = 'AM';
        jobRec.Sunday_s_Shift__c = 'AM';
        jobRec.Thursday_s_Shift__c = 'AM';
        

        update jobRec;

        Test.stopTest();
    }
    }
}