src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Lapsed</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <description>This is used to create any new client at Supply Desk.</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Holiday__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Holiday</relationshipLabel>
        <relationshipName>Holiday</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Holiday</label>
    <nameField>
        <label>Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holiday</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_Days__c</fullName>
        <label>Applicable Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Booking_Type__c</fullName>
        <label>Booking Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Perm</fullName>
                </value>
                <value>
                    <fullName>Promotional Day</fullName>
                </value>
                <value>
                    <fullName>Long Term</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                    <default>true</default>
                    <label>Daily</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Friday_s_Shift__c</fullName>
        <label>Friday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Monday_s_Shift__c</fullName>
        <label>Monday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Saturday_s_Shift__c</fullName>
        <label>Saturday&apos;s Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Client_Description__c</fullName>
        <label>Client Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TR1__Division__c</fullName>
        <label>Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Education_Requirements__c</fullName>
        <label>Education Requirements</label>
        <length>8000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TR1__Estimated_End_Date__c</fullName>
        <label>Estimated End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Estimated_Start_Date__c</fullName>
        <label>Estimated Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Experience_Requirements__c</fullName>
        <label>Experience Requirements</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TR1__Primary_Background__c</fullName>
        <label>Primary Background</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TR1__Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PM - Project Manager - Technical - Technology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Regional_Area__c</fullName>
        <label>Regional Area</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TR1__State_Area__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alsace</fullName>
                </value>
                <value>
                    <fullName>Altai Krai</fullName>
                </value>
                <value>
                    <fullName>Altai Republic</fullName>
                </value>
                <value>
                    <fullName>Amur Oblast</fullName>
                </value>
                <value>
                    <fullName>Andalusia</fullName>
                </value>
                <value>
                    <fullName>Aosta Valley</fullName>
                </value>
                <value>
                    <fullName>Apulia</fullName>
                </value>
                <value>
                    <fullName>Aquitaine</fullName>
                </value>
                <value>
                    <fullName>Aragon</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Arkhangelsk Oblast</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Arnsberg</fullName>
                </value>
                <value>
                    <fullName>Astrakhan Oblast</fullName>
                </value>
                <value>
                    <fullName>Asturias</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Auvergne</fullName>
                </value>
                <value>
                    <fullName>Avon</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Balearic Islands</fullName>
                </value>
                <value>
                    <fullName>Barking</fullName>
                </value>
                <value>
                    <fullName>Barking and Dagenham</fullName>
                </value>
                <value>
                    <fullName>Barnet</fullName>
                </value>
                <value>
                    <fullName>Barnsley</fullName>
                </value>
                <value>
                    <fullName>Bashkortostan</fullName>
                </value>
                <value>
                    <fullName>Basilicata</fullName>
                </value>
                <value>
                    <fullName>Basque Country</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Responsibilities__c</fullName>
        <label>Responsibilities</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TR1__State_Area__c</fullName>
        <label>State/Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Norway</fullName>
                </value>
                <value>
                    <fullName>Poland</fullName>
                </value>
                <value>
                    <fullName>Portugal</fullName>
                </value>
                <value>
                    <fullName>Romania</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                </value>
                <value>
                    <fullName>Spain</fullName>
                </value>
                <value>
                    <fullName>Sweden</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_Holiday_Helper.cls
@isTest(SeeAllData = false)
public with sharing class Test_Holiday_Helper {

    static testmethod void test_method_one() {
        
        // Create Test Data
        
        List<Account> acc = TestUtility.accList;
        List<Contact> conList = TestUtility.con;

        TR1__Job__c job =  new TR1__Job__c(TR1__Account__c = acc[0].id,
                                        TR1__Status__c = 'Open',
                                        TR1__Client_Description__c ='test',
                                        TR1__Education_Requirements__c='aaa',
                                        TR1__Experience_Requirements__c='bbb',
                                        TR1__Responsibilities__c='ccc',
                                        TR1__State_Area__c='test',
                                        TR1__Regional_Area__c='test',
                                        Booking_Type__c='test',
                                        TR1__Division__c='test',
                                        TR1__Primary_Background__c='test',
                                        TR1__Estimated_Start_Date__c = System.today().addDays(-10),
                                        TR1__Estimated_End_Date__c = System.today().addDays(10),  
                                        Applicable_Days__c = 'Monday' , RecordtypeId = TRS_vacancyhelper.CONSULTING_RTID,
                                        Friday_s_Shift__c = 'Full Day',
                                        Monday_s_Shift__c = 'Full Day',
                                        Saturday_s_Shift__c = 'Full Day',
                                        Sunday_s_Shift__c = 'Full Day',
                                        Thursday_s_Shift__c = 'Full Day',
                                        Tuesday_s_Shift__c = 'Full Day',
                                        Wednesday_s_Shift__c = 'Full Day');
        insert job;
        
        Vacancy_D2D__c testVacD2D = new Vacancy_D2D__c(Vacancy__c = job.Id, Vacancy_Date__c  = date.today() );
                     
        Holiday__c holiday = new Holiday__c(Account__c = acc[0].id , Start_Date__c = System.today() , End_Date__c = System.today().addDays(1));
        Holiday__c holid = new Holiday__c(Vacancy__c = job.id , Start_Date__c = System.today().addDays(5) , End_Date__c = System.today().addDays(6));
        // Start Test
        Test.startTest();        
        insert holiday;
        
        insert testVacD2d;               
        holiday.Start_Date__c = System.today().addDays(2);
        holiday.End_Date__c = System.today().addDays(2);        
        update holiday;
        
        
        insert holid; 
        
        Holiday__c holidayrec = [Select id from Holiday__c where id = :holiday.id];
        delete holidayrec;
        
         
        // Stop Test
        Test.stopTest();                                
                
    }
}