src/objects/Candidate_Availability__c.object
<CustomObject>
    <description>Object to store the availability of a candidate for a start to end date.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Candidate Availabilities</relationshipLabel>
        <relationshipName>Candidate_Availabilitys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Candidate Availability</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>CA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Availabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Closing_Report_Schedule__c.object
<CustomObject>
    <description>A schedule record is created for each day a Candidate is assigned to the Vacancy</description>
    <fields>
        <fullName>Candidate_Availability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Availability</label>
        <referenceTo>Candidate_Availability__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report Schedule</label>
    <nameField>
        <displayFormat>CRS-{0000000}</displayFormat>
        <label>CRS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CandidateAvailabilityTriggerHandler.cls
public with sharing class CandidateAvailabilityTriggerHandler {
    
    List<Candidate_Availability__c> recordNewList = new List<Candidate_Availability__c>();
    List<Candidate_Availability__c> recordOldList = new List<Candidate_Availability__c>();
    Map<Id,Candidate_Availability__c> recordNewMap = new Map<Id,Candidate_Availability__c>();
    Map<Id,Candidate_Availability__c> recordOldMap = new Map<Id,Candidate_Availability__c>();
    
    public CandidateAvailabilityTriggerHandler(List<Candidate_Availability__c> recordNewList,List<Candidate_Availability__c> recordOldList,Map<Id,Candidate_Availability__c> recordNewMap,Map<Id,Candidate_Availability__c> recordOldMap){
        this.recordNewList = recordNewList;
        this.recordOldList = recordOldList;
        this.recordNewMap = recordNewMap;
        this.recordOldMap = recordOldMap;
    }
    
    
    public void onBeforeInsertEvents(){
        preventTimeOverlapingOnCandidateAvailability(); 
    }
    
    public void onBeforeUpdateEvents(){
        preventTimeOverlapingOnCandidateAvailability();
    }
    
    public void onBeforeDeleteEvents(){
        preventDeletionOfCandidateAvailability();
    }
    
    public void preventTimeOverlapingOnCandidateAvailability(){
        Set<Id> contactIds = new Set<Id>();
        Set<Id> candidateAvailabilityIds = new Set<Id>();
        
        for(Candidate_Availability__c ca: recordNewList) {
            contactIds.add(ca.Candidate__c);
            candidateAvailabilityIds.add(ca.Id);
        }
        
        Map<Id,Contact> contactMap = new Map<Id,Contact>([select Id, (Select Id, Name, Start_Date_Time__c, End_Date_Time__c from Candidate_Availabilitys__r where Start_Date_Time__c != null and End_Date_Time__c != null) from Contact where Id IN: contactIds]);                
        if(contactMap.isEmpty()) return;
        
        for(Candidate_Availability__c ca: recordNewList) {
            if(contactMap.get(ca.Candidate__c)==null) continue;
            for(Candidate_Availability__c caInner: contactMap.get(ca.Candidate__c).Candidate_Availabilitys__r){
                if(caInner.Id==ca.Id) continue;
                
                if(ca.Start_Date_Time__c <= caInner.Start_Date_Time__c){
                    if(ca.End_Date_Time__c <= caInner.Start_Date_Time__c){
                        continue;
                    }
                    else{
                        ca.addError('Overlapping Candidate Availability cannot be created. Existing Candidate Availability: '+caInner.Name);
                    }
                }
                else{
                    if(ca.Start_Date_Time__c >= caInner.End_Date_Time__c){
                        continue;
                    }
                    else{
                        ca.addError('Overlapping Candidate Availability cannot be created. Existing Candidate Availability: '+caInner.Name);
                    }
                }
            }
        }
    }
    
    public void preventDeletionOfCandidateAvailability(){
        
        Map<Id,Closing_Report_Schedule__c> candidateAvailityIdToCRSMap = new Map<Id,Closing_Report_Schedule__c>();
        
        for(Closing_Report_Schedule__c crs : [Select Id,Candidate_Availability__c,Name from Closing_Report_Schedule__c WHERE Status__c = 'Booked' AND Candidate_Availability__c IN :recordOldMap.keySet()]){
            candidateAvailityIdToCRSMap.put(crs.Candidate_Availability__c,crs);
        }
        
        for(Candidate_Availability__c ca : recordOldList){
            if(candidateAvailityIdToCRSMap.containsKey(recordOldMap.get(ca.id).id)){
                ca.addError('Candidate Availability cannot be deleted as there exist booking '+candidateAvailityIdToCRSMap.get(recordOldMap.get(ca.id).id).Name+' for it. Please delete Booking first');
            }
        }
    }
}