src/objects/Candidate_Community__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It will have details for Candidate Community settings.</description>
    <fields>
        <fullName>Include_Stages__c</fullName>
        <description>Candidates to be shown belong to these values in status</description>
        <label>Include Stages</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Talent Rover Candidate Registration</label>
</CustomObject>

src/objects/TR1__Application__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Job_Reporting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Reporting</label>
        <referenceTo>TR1__Job_Reporting__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Stage__c</fullName>
        <formula>TEXT(TR1__Job_Reporting__r.TR1__Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hiring Manager for Jobs</relationshipLabel>
        <relationshipName>Jobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Job_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>TR1__Application__c</referenceTo>
        <relationshipLabel>Job Reporting</relationshipLabel>
        <relationshipName>Job_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Reporting</relationshipLabel>
        <relationshipName>Job_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipLabel>Job Reporting</relationshipLabel>
        <relationshipName>Job_Reporting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Applicaton</fullName>
                </value>
                <value>
                    <fullName>Submittal</fullName>
                </value>
                <value>
                    <fullName>Send Out</fullName>
                </value>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Closing Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Reporting</label>
    <nameField>
        <displayFormat>JR-{000000}</displayFormat>
        <label>Job Reporting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Reporting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RC_Test_ViewCandidate.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class RC_Test_ViewCandidate
{

    static testMethod void RC_Test_ViewCandidate()  
    {
        Candidate_Community__c setting = new Candidate_Community__c();
        setting.Name = 'RegistrationDetail';
        setting.Include_Stages__c = 'Shortlist:Client Interview:Submittal:Send Out:Sendout:Offer:Closing Report';
        insert setting;
        
        User objUser = RC_UtilityClass.returnCommunityUser();
        Id candidateId = [Select contactId from User where id =: objUser.Id].contactId;
        system.debug('strId ' + candidateId);
        
        TR1__Job__c objJob = RC_UtilityClass.insertJob();
        objJob.TR1__Hiring_Manager__c = candidateId;
        objJob.TR1__Contact__c = candidateId;
        update objJob;
        
        TR1__Application__c objApplication = new TR1__Application__c();
        objApplication.TR1__Job__c = objJob.Id;
        insert objApplication;
        
        TR1__Job_Reporting__c jobReport = new TR1__Job_Reporting__c();
        jobReport.TR1__Job__c = objJob.Id;
        jobReport.TR1__Contact__c = candidateId;
        jobReport.TR1__Stage__c = 'Submittal';
        jobReport.TR1__Application__c = objApplication.Id;
        insert jobReport;
        
        System.debug('objJob ' + objJob);
        System.debug('jobReport ' + jobReport);
        
        system.runAs(objUser)
        {
            Apexpages.currentPage().getParameters().put('id', candidateId); 
            Apexpages.currentPage().getParameters().put('JobId', objJob.Id); 
            Apexpages.currentPage().getParameters().put('rating', '4'); 
            RC_ViewCandidate objCandidate = new RC_ViewCandidate();

            objCandidate.redirectUnAuthenticatedUser(); // run all logic
            System.assertNotEquals(null, objCandidate.smallPhotoUrl);
            
         
        }
         
    }
    
}