src/objects/Closing_Report_Schedule__c.object
<CustomObject>
    <description>A schedule record is created for each day a Candidate is assigned to the Vacancy</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vacancy_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vacancy Schedule</label>
        <referenceTo>Vacancy_D2D__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Closing Report Schedule</label>
    <nameField>
        <displayFormat>CRS-{0000000}</displayFormat>
        <label>CRS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vacancy_D2D__c.object
<CustomObject>
    <fields>
        <fullName>Closing_Report_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report Schedule</label>
        <referenceTo>Closing_Report_Schedule__c</referenceTo>
        <relationshipLabel>Vacancy Schedules</relationshipLabel>
        <relationshipName>Vacancy_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vacancy__c</fullName>
        <label>Vacancy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TR1__Job__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Vacancy_D2Ds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vacancy Schedule</label>
    <nameField>
        <displayFormat>D2D-{000000}</displayFormat>
        <label>D2D Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancy Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VacancyD2DTriggerHandler.cls
public with sharing class VacancyD2DTriggerHandler {
    
    List<Vacancy_D2D__c> recordNewList = new List<Vacancy_D2D__c>();
    List<Vacancy_D2D__c> recordOldList = new List<Vacancy_D2D__c>();
    Map<Id,Vacancy_D2D__c> recordNewMap = new Map<Id,Vacancy_D2D__c>();
    Map<Id,Vacancy_D2D__c> recordOldMap = new Map<Id,Vacancy_D2D__c>();
    
    public VacancyD2DTriggerHandler(List<Vacancy_D2D__c> recordNewList,List<Vacancy_D2D__c> recordOldList,Map<Id,Vacancy_D2D__c> recordNewMap,Map<Id,Vacancy_D2D__c> recordOldMap){
        this.recordNewList = recordNewList;
        this.recordOldList = recordOldList;
        this.recordNewMap = recordNewMap;
        this.recordOldMap = recordOldMap;
    }
    
    public void onBeforeInsertEvents(){
        
        preventTimeOverlapingOnVacancySchedule();
    }
    
    public void onBeforeUpdateEvents(){
        
        preventTimeOverlapingOnVacancySchedule();
    }
    
    public void onBeforeDeleteEvents(){
        preventDeletionOfVacancySchedule();
    }
    
    
    
    public void preventTimeOverlapingOnVacancySchedule(){
        Set<Id> vacancyIds = new Set<Id>();
        
        for(Vacancy_D2D__c vs: recordNewList) {
            vacancyIds.add(vs.Vacancy__c);
            
        }
        
        Map<Id,TR1__Job__c> contactMap = new Map<Id,TR1__Job__c>([select Id, (Select Id, Name, Start_Date_Time__c, End_Date_Time__c from Vacancy_D2Ds__r where Start_Date_Time__c != null and End_Date_Time__c != null) from TR1__Job__c where Id IN: vacancyIds]);                
        if(contactMap.isEmpty()) return;
        
        for(Vacancy_D2D__c vs: recordNewList) {
            for(Vacancy_D2D__c vsExisting: contactMap.get(vs.Vacancy__c).Vacancy_D2Ds__r){
                if(vsExisting.Id==vs.Id) continue;
                
                if(vs.Start_Date_Time__c <= vsExisting.Start_Date_Time__c){
                    if(vs.End_Date_Time__c <= vsExisting.Start_Date_Time__c){
                        continue;
                    }
                    else{
                        vs.addError('Overlapping Vacancy Schedule cannot be created. Existing Vacancy Schedule: '+vsExisting.Name);
                    }
                }
                else{
                    if(vs.Start_Date_Time__c > vsExisting.End_Date_Time__c){
                        continue;
                    }
                    else{
                        vs.addError('Overlapping Vacancy Schedule cannot be created. Existing Vacancy Schedule: '+vsExisting.Name);
                    }
                }
            }
        }
    }
    
    public void preventDeletionOfVacancySchedule(){
        
        Map<Id,Closing_Report_Schedule__c> vacancyD2DIdToCRSMap = new Map<Id,Closing_Report_Schedule__c>();
        
        for(Closing_Report_Schedule__c crs : [Select Id,Vacancy_Schedule__c,Name from Closing_Report_Schedule__c WHERE Status__c = 'Booked' AND Vacancy_Schedule__c IN :recordOldMap.keySet()]){
            vacancyD2DIdToCRSMap.put(crs.Vacancy_Schedule__c,crs);
        }
        
        for(Vacancy_D2D__c vs : recordOldList){
            if(vacancyD2DIdToCRSMap.containsKey(recordOldMap.get(vs.id).id)){
                vs.addError('Vacancy Schedule cannot be deleted as there exist booking '+vacancyD2DIdToCRSMap.get(recordOldMap.get(vs.id).id).Name+' for it. Please delete Booking first');
            }
        }
    }
}