src/objects/Closing_Report_Schedule__c.object
<CustomObject>
    <description>A schedule record is created for each day a Candidate is assigned to the Vacancy</description>
    <fields>
        <fullName>CSD_End_Time__c</fullName>
        <formula>Candidate_Availability__r.End_Date_Time__c</formula>
        <label>CSD End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CSD_Start_Time__c</fullName>
        <formula>Candidate_Availability__r.Start_Date_Time__c</formula>
        <label>CSD Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Closing_Report__c</fullName>
        <label>Closing Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TR1__Closing_Report__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pay_Type__c</fullName>
        <label>Pay Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Placed__c</fullName>
        <formula>Closing_Report__r.TR1__Person_Placed__r.FirstName &amp; &quot; &quot; &amp;  Closing_Report__r.TR1__Person_Placed__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Person Placed</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Past_Contract_End_Date__c</fullName>
        <description>If the schedule date is greater than closing report contract end date , it evaluates to true</description>
        <formula>IF(Schedule_Date__c &gt; Closing_Report__r.Contract_End_Date__c  , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Schedule Past Contract End Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full Day</fullName>
                </value>
                <value>
                    <fullName>Extra Duties</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vacancy_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vacancy Schedule</label>
        <referenceTo>Vacancy_D2D__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vacancy_Shift_Type__c</fullName>
        <formula>Text( Vacancy_Schedule__r.Shift__c )</formula>
        <label>Vacancy Shift Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeekEndDate__c</fullName>
        <formula>Schedule_Date__c - (CASE(MOD( Schedule_Date__c - DATE(1900, 1, 6), 7), 0, 
5, 1, 
6, 2, 
0, 3, 
1, 4, 
2, 5, 
3, 6, 
4,7)) + 6</formula>
        <label>WeekEndDate</label>
        <type>Date</type>
    </fields>
    <label>Closing Report Schedule</label>
    <nameField>
        <displayFormat>CRS-{0000000}</displayFormat>
        <label>CRS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Pay_Type__c</fullName>
        <label>Pay Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Shift</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Closing_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report</label>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Name__c</fullName>
        <label>CRS Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closing_Report_Id__c</fullName>
        <formula>CASESAFEID(TR1__Timesheet__r.TR1__Closing_Report__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closing Report Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closing_Report_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report Schedule</label>
        <referenceTo>Closing_Report_Schedule__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timesheet_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DayShift__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Half_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Half Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Populated_By__c</fullName>
        <label>Populated By</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Day__c</fullName>
        <label>Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Regular_Hours__c</fullName>
        <label>Regular Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>TR1__Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Timesheet Detail</label>
    <nameField>
        <displayFormat>TS-{MM}{DD}{YY}-{0}</displayFormat>
        <label>Timesheet Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimesheetDetailTriggerHandler.cls
public with sharing class TimesheetDetailTriggerHandler {
    public Static boolean TimesheetDetailTriggerRecurssion = false;

    public void onBeforeInsert(List < TR1__Timesheet_Detail__c > triggernew) {
        TimesheetDetailTriggerRecurssion = true;
        updateTimesheetDetailWithCRS(triggernew,true);
    }

    public void onBeforeUpdate(List < TR1__Timesheet_Detail__c > triggernew, map < Id, TR1__Timesheet_Detail__c > triggerOldMap) {
        TimesheetDetailTriggerRecurssion = true;
        updateTimesheetDetailWithCRS(triggernew,false);
    }

    public void updateTimesheetDetailWithCRS(List < TR1__Timesheet_Detail__c > triggernew, Boolean isInsert) {
        set < Id > setClosingReportId = new set < Id > ();
        map < Id, map < date, List<Closing_Report_Schedule__c> >> mapCRtoMapWeekEndToCRS = new map < Id, map < date, List<Closing_Report_Schedule__c> >> ();
        Map <Id, Closing_Report_Schedule__c> crsIdToCRSMap = new Map <Id, Closing_Report_Schedule__c>();
        List<TR1__Timesheet_Detail__c> tdToBeInserted = new List<TR1__Timesheet_Detail__c>();

        for (TR1__Timesheet_Detail__c td: triggernew) {
            if ((isInsert && td.Closing_Report_Schedule__c == null && td.Closing_Report_Id__c != null) || (!isInsert && td.Closing_Report_Id__c != null)) {
                setClosingReportId.add(td.Closing_Report_Id__c);
            }
        }
        if (!setClosingReportId.isEmpty()) {
            for (TR1__Closing_Report__c cr: [Select TR1__Start_Date__c, TR1__End_Date__c,Pay_Type__c, Name, Id, (Select Id, Name, Closing_Report__c, Schedule_Date__c, Shift__c,CSD_End_Time__c,CSD_Start_Time__c,
                        Person_Placed__c, Schedule_Past_Contract_End_Date__c, WeekEndDate__c,Vacancy_Shift_Type__c,Vacancy_Schedule__c From Closing_Report_Schedules__r where Status__c != 'Cancelled')
                    From TR1__Closing_Report__c where Id in : setClosingReportId
                ]) {
                map < Date, List<Closing_Report_Schedule__c> > mapDateToCRS = new map < Date, List<Closing_Report_Schedule__c> > ();
                for (Closing_Report_Schedule__c crs: cr.Closing_Report_Schedules__r) {
                    crsIdToCRSMap.put(crs.Id,crs);
                    if(!mapDateToCRS.containsKey(crs.Schedule_Date__c)){
                        mapDateToCRS.put(crs.Schedule_Date__c, New List <Closing_Report_Schedule__c> { crs } );
                    }
                    else{
                        mapDateToCRS.get(crs.Schedule_Date__c).add(crs);
                    }
                }
                 System.debug('mapDateToCRS>>> '+mapDateToCRS);
                mapCRtoMapWeekEndToCRS.put(cr.Id, mapDateToCRS);
            }

            system.debug('===mapCRtoMapWeekEndToCRS:' + mapCRtoMapWeekEndToCRS);
            system.debug('===isInsert:' + isInsert);
            if (!mapCRtoMapWeekEndToCRS.isEmpty()) {
                for (TR1__Timesheet_Detail__c td: triggernew) {
                    if(isInsert) {
                        if (mapCRtoMapWeekEndToCRS.get(td.Closing_Report_Id__c) != null && mapCRtoMapWeekEndToCRS.get(td.Closing_Report_Id__c).get(td.TR1__Date__c)!=null) {
                            List<Closing_Report_Schedule__c> crsTempList = mapCRtoMapWeekEndToCRS.get(td.Closing_Report_Id__c).get(td.TR1__Date__c);
                            if (!crsTempList.isEmpty()) {
                                for(Integer i=0;i<crsTempList.size();i++){
                                    if(i==0){
                                        td.Populated_By__c = 'Update : TimesheetDetailTriggerHandler';
                                        setTimesheetData(crsTempList[i],td,isInsert);
                                        System.debug('===td=after set Data=='+td);
                                    }
                                    else{
                                        TR1__Timesheet_Detail__c tempTD = new TR1__Timesheet_Detail__c();
                                        tempTD.Populated_By__c = 'Insert : TimesheetDetailTriggerHandler';
                                        setTimesheetData(crsTempList[i],tempTD, isInsert);
                                        tempTD.TR1__Date__c=crsTempList[i].Schedule_Date__c;
                                        tempTD.TR1__Day__c=TimesheetUtility.dayOfDate(crsTempList[i].Schedule_Date__c);
                                        tempTD.TR1__Timesheet__c = td.TR1__Timesheet__c;
                                        tdToBeInserted.add(tempTD);
                                    }
                                }
                            }
                        }
                    }
                    else {
                      system.debug('===isNotInsert:' + isInsert);
                        if(String.isBlank(td.Closing_Report_Schedule__c)) {
                          system.debug('CRS Not Found');
                            td.Populated_By__c = 'Emptied CRS : TimesheetDetailTriggerHandler';
                            td.crs_name__c = null;
                            td.Half_Day__c = false;
                            //Test for W-4222976
                            td.DayShift__c = false;
                            td.TR1__Regular_Hours__c = td.TR1__Regular_Hours__c;
                        }
                        else if(crsIdToCRSMap.containsKey(td.Closing_Report_Schedule__c)) {
                          system.debug('td>>>0 '+ td);
                            setTimesheetData(crsIdToCRSMap.get(td.Closing_Report_Schedule__c),td,isInsert);
                            system.debug('td>>>1 '+ td);
                        }
                    }
                }// end for trigger.new
                System.debug('===tdToBeInserted==='+tdToBeInserted);
                if(!tdToBeInserted.isEmpty()){
                    Database.insert(tdToBeInserted,false);
                }
            }
        }
    }
    private void setTimesheetData(Closing_Report_Schedule__c crsTemp,TR1__Timesheet_Detail__c td, Boolean isInsert){
        td.Closing_Report_Schedule__c = crsTemp.Id;
        td.crs_name__c = crsTemp.Name;
        td.Half_Day__c = false;
        //Test for W-4222976
        td.DayShift__c = false;
        //td.TR1__Regular_Hours__c = null;
        system.debug('Shift Type --'+crsTemp.Vacancy_Shift_Type__c);
        if( crsTemp.Vacancy_Schedule__c!=null && (crsTemp.Vacancy_Shift_Type__c == 'AM' || crsTemp.Vacancy_Shift_Type__c == 'PM')){
            td.Half_Day__c = True;
        }
        else if( crsTemp.Vacancy_Schedule__c!=null && crsTemp.Vacancy_Shift_Type__c == 'Hourly'){
            Closing_Report_Schedule__c tempCRS = crsTemp;
            if(tempCRS.CSD_End_Time__c!=null &&  tempCRS.CSD_Start_Time__c!=null ){
                Long dt1Long = tempCRS.CSD_End_Time__c.getTime();
                Long dt2Long = tempCRS.CSD_Start_Time__c.getTime();
                system.debug('dt1Long--'+dt1Long+'dt2Long--'+dt2Long);
                Long milliseconds = dt1Long - dt2Long ;
                Long seconds = milliseconds / 1000;
                Long minutes = seconds / 60;
                Double divBy60 = 60;
                Double hours = minutes / divBy60;
                if(isInsert)
                  td.TR1__Regular_Hours__c = hours;
                 system.debug('td>>>2 '+ td);
            }else {
                td.AddError('Start time and End time are not present on candidate availablitily record ');
            }
        }else if( crsTemp.Vacancy_Schedule__c!=null && crsTemp.Vacancy_Shift_Type__c == 'Daily'){
            //Test for W-4222976
            td.DayShift__c = True;
        }
    }
}