src/objects/Closing_Report_Schedule__c.object
<CustomObject>
    <description>A schedule record is created for each day a Candidate is assigned to the Vacancy</description>
    <fields>
        <fullName>Candidate_Availability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate Availability</label>
        <referenceTo>Candidate_Availability__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closing_Report__c</fullName>
        <label>Closing Report</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TR1__Closing_Report__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Consulting</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vacancy_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vacancy Schedule</label>
        <referenceTo>Vacancy_D2D__c</referenceTo>
        <relationshipLabel>Closing Report Schedules</relationshipLabel>
        <relationshipName>Closing_Report_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Closing Report Schedule</label>
    <nameField>
        <displayFormat>CRS-{0000000}</displayFormat>
        <label>CRS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Report Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maximum_Day_Charge_Rate__c</fullName>
        <label>Day Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Day_Pay_Rate__c</fullName>
        <label>Day Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Half_Day_Charge_Rate__c</fullName>
        <label>Half Day Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Half_Day_Pay_Rate__c</fullName>
        <label>Half Day Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Charge_Rate__c</fullName>
        <label>Hour Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Pay_Rate__c</fullName>
        <label>Hour Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Old_Day_Charge_Rate__c</fullName>
        <label>Old Day Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Old_Day_Pay_Rate__c</fullName>
        <label>Old Day Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Old_Half_Day_Charge_Rate__c</fullName>
        <label>Old Half Day Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Old_Half_Day_Pay_Rate__c</fullName>
        <label>Old Half Day Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Old_Hour_Charge_Rate__c</fullName>
        <label>Old Hour Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Old_Hour_Pay_Rate__c</fullName>
        <label>Old Hour Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Assignment_Ended__c</fullName>
        <label>Assignment Ended</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Rate Change</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Booking_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Declared date – vacancy closed as agreed/won</inlineHelpText>
        <label>Booking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Candidate_Percentage__c</fullName>
        <label>Candidate Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Conversion_Date__c</fullName>
        <label>Conversion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Generate_Timesheet__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Generate Timesheet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Percentage__c</fullName>
        <label>Job Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Marketing_Percentage__c</fullName>
        <label>Marketing Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Other2_Percentage__c</fullName>
        <label>Other2 Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Other_Percentage__c</fullName>
        <label>Other Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Rate_Change_Effective_Date__c</fullName>
        <label>Rate Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Receive_Timesheet_Email_Alerts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Receive Timesheet Email Alerts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Type__c</fullName>
        <label>Timesheet Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Online</fullName>
                    <default>true</default>
                    <label>Online</label>
                </value>
                <value>
                    <fullName>3rd Party</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Hour_Charge_Rate__c</fullName>
        <label>Maximum Hour Charge Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Hour_Pay_Rate__c</fullName>
        <label>Maximum Hour Pay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Closing_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report</label>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Type__c</fullName>
        <formula>TEXT ( TR1__Closing_Report__r.TR1__Timesheet_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Timesheet Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timesheet_Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timesheet_Approved_Date_Time__c</fullName>
        <label>Timesheet Approved Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Closing_Report_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report Schedule</label>
        <referenceTo>Closing_Report_Schedule__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timesheet_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>TR1__Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Timesheet Detail</label>
    <nameField>
        <displayFormat>TS-{MM}{DD}{YY}-{0}</displayFormat>
        <label>Timesheet Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RateChangeButtonClosingReportController.cls
public with sharing class RateChangeButtonClosingReportController{
    public TR1__Closing_Report__c currentcr{get;set;}
    public TR1__Closing_Report__c newcr{get;set;}
    public Boolean isSuccess{get;set;}
    private Set<String> accessibleNames = new Set<String>();
    
    //Constructor
    public RateChangeButtonClosingReportController(ApexPages.StandardController controller){
        
        Map<String, Schema.SobjectField> fields = Schema.SobjectType.TR1__Closing_Report__c.fields.getMap();
        for (String s : fields.keySet()) {           
            if (fields.get(s).getDescribe().isAccessible()){
                accessibleNames.add(s);
            }            
        }
        
        if(!Test.isrunningtest()){
            controller.addFields(new List<String>(accessibleNames));
            this.currentcr = (TR1__Closing_Report__c)controller.getRecord();
        }
        else{
            Id recordId = controller.getRecord().Id;
            this.currentcr = [
                              SELECT Id, TR1__Job__c, TR1__Account__c, TR1__Person_Placed__c, Maximum_Day_Charge_Rate__c, Maximum_Day_Pay_Rate__c, Maximum_Half_Day_Charge_Rate__c, Maximum_Half_Day_Pay_Rate__c,
                                     Maximum_Hour_Charge_Rate__c, Maximum_Hour_Pay_Rate__c, TR1__Generate_Timesheet__c, TR1__Receive_Timesheet_Email_Alerts__c, TR1__Conversion_Date__c, TR1__Job_Percentage__c,
                                     TR1__Candidate_Percentage__c, TR1__Marketing_Percentage__c, TR1__Other_Percentage__c, TR1__Other2_Percentage__c, TR1__Assignment_Ended__c, TR1__End_Date__c,
                                     TR1__Rate_Change_Effective_Date__c, TR1__Salary__c, RecordTypeId, TR1__Start_Date__c
                              FROM TR1__Closing_Report__c
                              WHERE Id = :recordId
                             ];
        }
        
        this.newcr = currentcr.clone();
        this.newcr.TR1__Start_Date__c = null;
        this.newcr.TR1__Booking_Date__c = null;
        this.isSuccess = false;
    }
    
    public void SaveRateChange(){
        
        if(newcr.TR1__Rate_Change_Effective_Date__c < currentcr.TR1__Start_Date__c ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Rate Change Effective Date should be greater than Closing Report Start Date.'));
            return;
        }
        
        if(newcr.TR1__Rate_Change_Effective_Date__c > currentcr.TR1__End_Date__c ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Rate Change Effective Date should be less than Closing Report End Date.'));
            return;
        }
        
        if(newcr.Maximum_Day_Charge_Rate__c < newcr.Maximum_Day_Pay_Rate__c ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Day Pay Rate cannot be greater than Day Charge Rate.'));
            return;
        }
        
        if(newcr.Maximum_Half_Day_Charge_Rate__c < newcr.Maximum_Half_Day_Pay_Rate__c ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Half Day Pay Rate cannot be greater than Half Day Pay Rate.'));
            return;
        }
        
        if(newcr.Maximum_Hour_Charge_Rate__c < newcr.Maximum_Hour_Pay_Rate__c ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Hour Pay Rate cannot be greater than Hour Charge Rate.'));
            return ;
        }
        
        Savepoint sp = Database.setSavepoint();
        try{
            
            Date newEndDate = newcr.TR1__Rate_Change_Effective_Date__c.addDays(-1);
            
            newcr.Old_Hour_Charge_Rate__c =  currentcr.Maximum_Hour_Charge_Rate__c ;
            newcr.Old_Hour_Pay_Rate__c = currentcr.Maximum_Hour_Pay_Rate__c ;
            newcr.Old_Half_Day_Charge_Rate__c = currentcr.Maximum_Half_Day_Charge_Rate__c ;
            newcr.Old_Half_Day_Pay_Rate__c  = currentcr.Maximum_Half_Day_Pay_Rate__c ;
            newcr.Old_Day_Charge_Rate__c= currentcr.Maximum_Day_Charge_Rate__c ;
            newcr.Old_Day_Pay_Rate__c =  currentcr.Maximum_Day_Pay_Rate__c ;
            newcr.TR1__Assignment_Ended__c = 'No';
            newcr.TR1__Start_Date__c = newcr.TR1__Rate_Change_Effective_Date__c;
            
            currentcr.TR1__Generate_Timesheet__c = false;
            currentcr.TR1__Receive_Timesheet_Email_Alerts__c = false;
            currentcr.TR1__Assignment_Ended__c = 'Yes';
            currentcr.TR1__Assignment_Ended__c = 'Rate Change';
            currentcr.TR1__End_Date__c = newEndDate;
            currentcr.Contract_End_Date__c = newEndDate;
            
            if(currentcr!=null){
                update currentcr;
            }
            
            //Insert New CR
            if(newcr!= null){
                ClosingReportTriggerHelper.FromJobboard = True ;
                ClosingReportTriggerHelper.createTimesheetsForPastOrThisWeekFlag = true;
                SendConfirmationLetter.sendConfirmationLetterFlag = true;
                insert newcr;
            }
            
            //CRS reparenting
            list<Closing_Report_Schedule__c> closingReportScheduleToBeReparented = [
                                                                                    SELECT Name, Id,Closing_Report__r.Name,Candidate_Availability__c,Vacancy_Schedule__c 
                                                                                    FROM Closing_Report_Schedule__c 
                                                                                    WHERE Closing_Report__c =:currentcr.id AND Schedule_Date__c	> :newEndDate
                                                                                   ];
                                                                                   
            for(Closing_Report_Schedule__c crs : closingReportScheduleToBeReparented){
                crs.Closing_Report__c = newCR.id;
            }
            
            if(closingReportScheduleToBeReparented.size()>0){
                update closingReportScheduleToBeReparented;
            }
            
            //Query timesheets whose week ending is greater than rate change date selected 
            List<TR1__Timesheet__c> timesheetList = [
                                                  SELECT Id, Timesheet_Approved_Date_Time__c, Timesheet_Approved_By__c, TR1__Week_Ending__c, TR1__Timesheet_Type__c, TR1__Timesheet_Second_Approver__c, TR1__Status__c, TR1__Recruiter__c,
                                                         TR1__Payroll_Note__c, TR1__Consultant__c, TR1__Pay_Week_Ending__c, TR1__Closing_Report__c, TR1__Client__c, TR1__Job_Order__c
                                                  FROM TR1__Timesheet__c
                                                  WHERE TR1__Closing_Report__c = :currentcr.Id AND TR1__Week_Ending__c >= :newcr.TR1__Rate_Change_Effective_Date__c
                                                 ];
            
            List<TR1__Timesheet__c> timesheetToBeReparented = new List<TR1__Timesheet__c>();
            List<TR1__Timesheet__c> timesheetToCloned = new List<TR1__Timesheet__c>();
            for(TR1__Timesheet__c ts : timesheetList){
                if(ts.TR1__Week_Ending__c >= newcr.TR1__Rate_Change_Effective_Date__c.addDays(6)){
                    timesheetToBeReparented.add(ts);
                }
                else{
                    timesheetToCloned.add(ts);
                }
            }
            
            //Reparent Timesheets
            if(timesheetToBeReparented.size()>0){
                for(TR1__Timesheet__c ts : timesheetToBeReparented){
                    ts.TR1__Closing_Report__c = newCR.id;
                }
                update timesheetToBeReparented;
            }
            
            //Clone Timesheets & Reparent Timesheet Detail
            if(timesheetToCloned.size()>0){
                
                Set<Id> timesheetIdSet = (new Map<Id,TR1__Timesheet__c>(timesheetToCloned)).keySet();
                List<TR1__Timesheet_Detail__c> timesheetDetailToBeReparentedList = [SELECT Id, TR1__Day__c, TR1__Date__c, TR1__Timesheet__c FROM TR1__Timesheet_Detail__c WHERE TR1__Timesheet__c IN :timesheetIdSet AND TR1__Date__c >= :newcr.TR1__Rate_Change_Effective_Date__c]; 
                Map<Id,TR1__Timesheet__c> oldTimesheetToNewTimesheetMap = new Map<Id,TR1__Timesheet__c>();
                
                for(TR1__Timesheet__c ts : timesheetToCloned){
                    TR1__Timesheet__c tempTimesheet = ts.clone();
                    tempTimesheet.TR1__Closing_Report__c = newCR.id;
                    oldTimesheetToNewTimesheetMap.put(ts.id,tempTimesheet);
                }
                insert oldTimesheetToNewTimesheetMap.values();
                
                for(TR1__Timesheet_Detail__c tsd : timesheetDetailToBeReparentedList){
                    if(tsd.TR1__Date__c >= newcr.TR1__Rate_Change_Effective_Date__c){
                        if(oldTimesheetToNewTimesheetMap.containsKey(tsd.TR1__Timesheet__c)){
                            tsd.TR1__Timesheet__c = oldTimesheetToNewTimesheetMap.get(tsd.TR1__Timesheet__c).id;
                        }
                    }
                }
                
                TimesheetDetailTriggerHandler.TimesheetDetailTriggerRecurssion = false;
                update timesheetDetailToBeReparentedList;
            }
            
            this.isSuccess = true;  
        }
        catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,ex.getMessage()));
            Database.rollback(sp);
        }
    }
}