src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/echosign_dev1__Agreement_Template__c.object
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <description>Agreement Templates allow you to predefine default settings and options for your agreements which can save you time and help minimize errors.</description>
    <fields>
        <fullName>echosign_dev1__Message__c</fullName>
        <description>Enter a message that will be sent to the recipients.</description>
        <inlineHelpText>Enter a message that will be sent to the recipients.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Name__c</fullName>
        <defaultValue>&quot;Adobe Sign Agreement&quot;</defaultValue>
        <description>Enter a name for the agreement.</description>
        <inlineHelpText>Enter a name for the agreement.</inlineHelpText>
        <label>Agreement Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Agreement Template</label>
    <nameField>
        <label>Agreement Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreement Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/echosign_dev1__SIGN_Agreement__c.object
<CustomObject>
    <customHelpPage>echosign_dev1__EchoSignUserGuide</customHelpPage>
    <fields>
        <fullName>echosign_dev1__Message__c</fullName>
        <defaultValue>&quot;Please review and sign this document.&quot;</defaultValue>
        <description>Specify a message to the recipients.</description>
        <inlineHelpText>Specify a message to the recipients.</inlineHelpText>
        <label>Message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Name__c</fullName>
        <description>Agreement name can have up to 255 characters.</description>
        <inlineHelpText>Agreement name can have up to 255 characters.</inlineHelpText>
        <label>Agreement Name(Long Version))</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Recipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>R00N70000001hM2OEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>echosign_dev1__Status__c</fullName>
        <label>Agreement Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pre-Send</fullName>
                </value>
                <value>
                    <fullName>Send in Progress</fullName>
                </value>
                <value>
                    <fullName>Cancelled / Declined</fullName>
                    <label>Canceled / Declined</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Out for Signature</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Signature</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Out for Approval</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Out for Form-Filling</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Form-Filling</fullName>
                </value>
                <value>
                    <fullName>Form-Filled</fullName>
                </value>
                <value>
                    <fullName>Out for Acceptance</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Acceptance</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Out for Delivery</fullName>
                </value>
                <value>
                    <fullName>Waiting for Counter-Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Waiting for my Delegation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>CV</fullName>
        <active>false</active>
        <label>CV</label>
    </recordTypes>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <recordTypes>
        <fullName>References</fullName>
        <active>false</active>
        <label>References</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_AgreementTrigger.cls
@isTest
public class Test_AgreementTrigger {
    @isTest
    public static void adobeSignAgreementTest1(){
        Contact testContact = new Contact(FirstName = 'Test', LastName='Candidate', Email='testcandidate@suppldesk.com');
        insert testContact;

        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the');
        ContentVersion cv = new Contentversion();
        cv.title='Supply Desk Terms of Engagement Supply Teacher - signed.pdf';
        cv.PathOnClient ='Supply Desk Terms of Engagement Supply Teacher - signed.pdf';	
        cv.VersionData = bodyBlob;
        insert cv;

        echosign_dev1__Agreement_Template__c agTemplate = new echosign_dev1__Agreement_Template__c();
        agTemplate.Name = 'Supply Desk Terms of Engagement Supply Teacher';
        agTemplate.echosign_dev1__Name__c = 'Testing Agreement';
        insert agTemplate;

        echosign_dev1__SIGN_Agreement__c agSign = new echosign_dev1__SIGN_Agreement__c();
        agSign.Name = 'Testing Agreement';
        agSign.echosign_dev1__Recipient__c = testContact.Id;
        insert agSign;

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = agSign.Id;
        contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;

        Test.startTest();
            agSign.echosign_dev1__Status__c = 'Out for Signature';
            update agSign;
        Test.stopTest();
    }
    
    @isTest
    public static void adobeSignAgreementTest1_1(){
        Contact testContact = new Contact(FirstName = 'Test', LastName='Candidate', Email='testcandidate@suppldesk.com', Registration_Agreement_Names__c = 'Supply Desk Terms of Engagement');
        insert testContact;

        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the');
        ContentVersion cv = new Contentversion();
        cv.title='Supply Desk Terms of Engagement Supply Teacher - signed.pdf';
        cv.PathOnClient ='Supply Desk Terms of Engagement Supply Teacher - signed.pdf';	
        cv.VersionData = bodyBlob;
        insert cv;

        echosign_dev1__Agreement_Template__c agTemplate = new echosign_dev1__Agreement_Template__c();
        agTemplate.Name = 'Supply Desk Terms of Engagement Supply Teacher';
        agTemplate.echosign_dev1__Name__c = 'Testing Agreement';
        insert agTemplate;

        echosign_dev1__SIGN_Agreement__c agSign = new echosign_dev1__SIGN_Agreement__c();
        agSign.Name = 'Testing Agreement';
        agSign.echosign_dev1__Recipient__c = testContact.Id;
        insert agSign;

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = agSign.Id;
        contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;

        Test.startTest();
            agSign.echosign_dev1__Status__c = 'Out for Signature';
            update agSign;
        Test.stopTest();
    }

    @isTest
    public static void adobeSignAgreementTest2(){
        Contact testContact = new Contact(FirstName = 'Test', LastName='Candidate', Email='testcandidate@suppldesk.com');
        insert testContact;

        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the functionality.');
        ContentVersion cv = new Contentversion();
        cv.title='Supply Desk Terms of Engagement Supply Teacher - signed.pdf';
        cv.PathOnClient ='Supply Desk Terms of Engagement Supply Teacher - signed.pdf';	
        cv.VersionData = bodyBlob;
        insert cv;

        echosign_dev1__Agreement_Template__c agTemplate = new echosign_dev1__Agreement_Template__c();
        agTemplate.Name = 'Supply Desk Terms of Engagement Supply Teacher';
        agTemplate.echosign_dev1__Name__c = 'Testing Agreement';
        insert agTemplate;

        echosign_dev1__SIGN_Agreement__c agSign = new echosign_dev1__SIGN_Agreement__c();
        agSign.Name = 'Testing Agreement';
        agSign.echosign_dev1__Recipient__c = testContact.Id;
        insert agSign;

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = agSign.Id;
        contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;

        TR1__Qualification__c qual = new TR1__Qualification__c();
        qual.Name = 'Terms and Registration Forms';
        insert qual;
        TR1__Associated_Qualification__c associatQual = new TR1__Associated_Qualification__c();
        associatQual.TR1__Contact__c = testContact.Id;
        associatQual.TR1__Qualification__c = qual.Id;
        insert associatQual;

        Test.startTest();
            agSign.echosign_dev1__Status__c = 'Signed';
            update agSign;
        Test.stopTest();
    }

    @isTest
    public static void adobeSignAgreementTest3(){
        Contact testContact = new Contact(FirstName = 'Test', LastName='Candidate', Email='testcandidate@suppldesk.com');
        insert testContact;

        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the functionality.');
        ContentVersion cv = new Contentversion();
        cv.title='Referee Consent Form - signed.pdf';
        cv.PathOnClient ='Referee Consent Form - signed.pdf';	
        cv.VersionData = bodyBlob;
        insert cv;

        echosign_dev1__Agreement_Template__c agTemplate = new echosign_dev1__Agreement_Template__c();
        agTemplate.Name = 'Referee Consent Form';
        agTemplate.echosign_dev1__Name__c = 'Testing Agreement';
        insert agTemplate;

        echosign_dev1__SIGN_Agreement__c agSign = new echosign_dev1__SIGN_Agreement__c();
        agSign.Name = 'Testing Agreement';
        agSign.echosign_dev1__Recipient__c = testContact.Id;
        insert agSign;

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = agSign.Id;
        contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;

        TR1__Qualification__c qual1 = new TR1__Qualification__c();
        qual1.Name = 'References';
        insert qual1;
        TR1__Associated_Qualification__c associatQual1 = new TR1__Associated_Qualification__c();
        associatQual1.TR1__Contact__c = testContact.Id;
        associatQual1.TR1__Qualification__c = qual1.Id;
        insert associatQual1;

        Test.startTest();
            agSign.echosign_dev1__Status__c = 'Signed';
            update agSign;
        Test.stopTest();
    }

    @isTest
    public static void adobeSignAgreementTest4(){
        Contact testContact = new Contact(FirstName = 'Test', LastName='Candidate', Email='testcandidate@suppldesk.com');
        insert testContact;

        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the functionality.');
        ContentVersion cv = new Contentversion();
        cv.title='Supply Desk DBS Terms of Service - signed.pdf';
        cv.PathOnClient ='Supply Desk DBS Terms of Service - signed.pdf';	
        cv.VersionData = bodyBlob;
        insert cv;

        echosign_dev1__Agreement_Template__c agTemplate = new echosign_dev1__Agreement_Template__c();
        agTemplate.Name = 'Supply Desk DBS Terms of Service';
        agTemplate.echosign_dev1__Name__c = 'Testing Agreement';
        insert agTemplate;

        echosign_dev1__SIGN_Agreement__c agSign = new echosign_dev1__SIGN_Agreement__c();
        agSign.Name = 'Testing Agreement';
        agSign.echosign_dev1__Recipient__c = testContact.Id;
        insert agSign;

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = agSign.Id;
        contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;

        TR1__Qualification__c qual2 = new TR1__Qualification__c();
        qual2.Name = 'DBS';
        insert qual2;
        TR1__Associated_Qualification__c associatQual2 = new TR1__Associated_Qualification__c();
        associatQual2.TR1__Contact__c = testContact.Id;
        associatQual2.TR1__Qualification__c = qual2.Id;
        insert associatQual2;
        
        Test.startTest();
            agSign.echosign_dev1__Status__c = 'Signed';
            update agSign;
        Test.stopTest();
    }

    @isTest
    public static void adobeSignAgreementTest5(){
        Contact testContact = new Contact(FirstName = 'Test', LastName='Candidate', Email='testcandidate@suppldesk.com');
        insert testContact;

        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the functionality.');
        ContentVersion cv = new Contentversion();
        cv.title='Supply Desk DBS Terms of Service - signed.pdf';
        cv.PathOnClient ='Supply Desk DBS Terms of Service - signed.pdf';	
        cv.VersionData = bodyBlob;
        insert cv;

        echosign_dev1__Agreement_Template__c agTemplate = new echosign_dev1__Agreement_Template__c();
        agTemplate.Name = 'Supply Desk DBS Terms of Service';
        agTemplate.echosign_dev1__Name__c = 'Testing Agreement';
        insert agTemplate;

        echosign_dev1__SIGN_Agreement__c agSign = new echosign_dev1__SIGN_Agreement__c();
        agSign.Name = 'Testing Agreement';
        agSign.echosign_dev1__Recipient__c = testContact.Id;
        insert agSign;

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = agSign.Id;
        contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;

        TR1__Qualification__c qual2 = new TR1__Qualification__c();
        qual2.Name = 'DBS';
        insert qual2;
        TR1__Associated_Qualification__c associatQual2 = new TR1__Associated_Qualification__c();
        associatQual2.TR1__Contact__c = testContact.Id;
        associatQual2.TR1__Qualification__c = qual2.Id;
        insert associatQual2;
        
        Test.startTest();
            agSign.echosign_dev1__Status__c = 'Draft';
            agSign.echosign_dev1__Message__c = null;
            update agSign;
        Test.stopTest();
    }

    @isTest
    public static void adobeSignAgreementTest6(){
        Contact testContact = new Contact(FirstName = 'Test', LastName='Candidate', Email='testcandidate@suppldesk.com');
        insert testContact;

        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body to be insert in test class for testing the functionality.');
        ContentVersion cv = new Contentversion();
        cv.title='SD/Teach in Teacher Registration Pack Overseas - signed.pdf';
        cv.PathOnClient ='SD/Teach in Teacher Registration Pack Overseas - signed.pdf';	
        cv.VersionData = bodyBlob;
        insert cv;

        echosign_dev1__Agreement_Template__c agTemplate = new echosign_dev1__Agreement_Template__c();
        agTemplate.Name = 'SD/Teach in Teacher Registration Pack';
        agTemplate.echosign_dev1__Name__c = 'SD/Teach in Teacher Registration Pack';
        insert agTemplate;

        echosign_dev1__SIGN_Agreement__c agSign = new echosign_dev1__SIGN_Agreement__c();
        agSign.Name = 'SD/Teach in Teacher Registration Pack';
        agSign.echosign_dev1__Recipient__c = testContact.Id;
        insert agSign;

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = agSign.Id;
        contentlink.contentdocumentid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;

        TR1__Qualification__c qual2 = new TR1__Qualification__c();
        qual2.Name = 'DBS';
        insert qual2;
        TR1__Associated_Qualification__c associatQual2 = new TR1__Associated_Qualification__c();
        associatQual2.TR1__Contact__c = testContact.Id;
        associatQual2.TR1__Qualification__c = qual2.Id;
        insert associatQual2;
        
        Test.startTest();
            agSign.echosign_dev1__Status__c = 'Draft';
            agSign.echosign_dev1__Message__c = null;
            update agSign;
        Test.stopTest();
    }
}