src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Inactive_Compliance_Result__c</fullName>
        <label>Inactive Compliance Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non Workable</fullName>
                </value>
                <value>
                    <fullName>Non Payable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Associated_Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Associated Qualification</label>
        <referenceTo>TR1__Associated_Qualification__c</referenceTo>
        <relationshipLabel>Compliance Documents (Source Associated Qualification)</relationshipLabel>
        <relationshipName>Source_Compliance_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Package</label>
        <referenceTo>TR1__Qualification_Package__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Field_Set_ID__c</fullName>
        <label>Field Set ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Qualification_Package__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Qualification Packages</relationshipLabel>
        <relationshipName>Qualification_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualification Package</label>
    <nameField>
        <displayFormat>QP{YY}{MM}-{0000}</displayFormat>
        <label>Qualification Package</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RC_ContactAssociatedQualifications_Test.cls
@isTest
private class RC_ContactAssociatedQualifications_Test {

	private static testMethod void testCreateAssoicatedQualification() {
	    
	    Test.startTest();
	    
	    TR1__Qualification__c objQual = new TR1__Qualification__c(Name = 'Passport', TR1__Field_Set_ID__c = '321534');
	    insert objQual;
	    TR1__Qualification__c objQual1 =  new TR1__Qualification__c(Name = 'Resume', TR1__Field_Set_ID__c = '321534');
	    insert objQual1;
	    
	    TR1__Qualification_Package__c objQualPkg  = new TR1__Qualification_Package__c(TR1__Name__c = 'OTT');
        insert objQualPkg;

	    Id contactRecordType = schema.SObjectType.contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();
        Contact objContact = new Contact(recordTypeId = contactRecordType, LastName = 'TestLastName_AssoQual', Tax_Method__c = 'PAYE', email ='test@test328435634567294.com', phone  ='342336364', Subject__c  = 'Art', Year_Key_Stage__c ='KS1');
	    insert objContact;
	    
	    TR1__Associated_Qualification__c objAssoQual = new TR1__Associated_Qualification__c(TR1__Qualification__c =objQual.Id, TR1__Qualification_Package__c = objQualPkg.Id); 
	    //objAssoQual.Inactive_Compliance_Result__c = 'Non Workable';
	    insert objAssoQual;
	    
	    TR1__Associated_Qualification__c objAssoQual1 = new TR1__Associated_Qualification__c(TR1__Qualification__c =objQual1.Id, TR1__Qualification_Package__c = objQualPkg.Id); 
        //objAssoQual1.Inactive_Compliance_Result__c = 'Non Payable';
        insert objAssoQual1;
      
        
        objContact = [select Name, Id,Pay_Type__c from Contact where id= : objContact.Id limit 1 ];
        objContact.Pay_Type__c = 'OTT';
        update objContact;
        
	    
	    List<TR1__Associated_Qualification__c> lstAQ = [Select TR1__Status__c from TR1__Associated_Qualification__c where TR1__Contact__c =:objContact.Id];
	    if(!lstAQ.isEmpty()){
    	    lstAQ[0].TR1__Status__c = 'Active';
    	    lstAQ[1].TR1__Status__c = 'Active';
    	    update lstAQ;
	    }
	       
        Contact objContact1 = new Contact(LastName = 'TestLastName_AssoQual - 1',email ='tes1414t@test32847294.com', phone  ='34234', Subject__c  = 'Art', Year_Key_Stage__c ='KS1');//, Pay_Type__c = 'Permanent');
	    insert objContact1;
        
        TR1__Associated_Qualification__c objAssoQual2 = new TR1__Associated_Qualification__c(TR1__Qualification__c =objQual.Id, TR1__Contact__c = objContact1.Id, TR1__Qualification_Package__c = objQualPkg.Id); 
        //objAssoQual2.Source_Associated_Qualification__c = objAssoQual1.Id;
        objAssoQual2.TR1__Status__c = 'Active';
        insert objAssoQual2;
      
        
	    
	    Test.stopTest();

	}

}