src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>DBS_Form_Number__c</fullName>
        <label>DBS Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Address__c</fullName>
        <label>Emergency Contact Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Home_Phone__c</fullName>
        <label>Emergency Contact Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Mobile_Phone__c</fullName>
        <label>Emergency Contact Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Name__c</fullName>
        <label>Emergency Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Work_Phone__c</fullName>
        <label>Emergency Contact Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>On_Update_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If DBS is issued within 19 days, advise the candidate they can register on update service</inlineHelpText>
        <label>On Update Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QTLS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QTLS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Qualification_Type2__c</fullName>
        <label>Qualification Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Overseas Qualifications - Aus/NZ</fullName>
                </value>
                <value>
                    <fullName>Overseas Qualifications - Canada</fullName>
                </value>
                <value>
                    <fullName>Overseas Qualifications - USA</fullName>
                </value>
                <value>
                    <fullName>Overseas Qualifications - Other</fullName>
                </value>
                <value>
                    <fullName>Teacher Qualification</fullName>
                </value>
                <value>
                    <fullName>Support Qualifications</fullName>
                </value>
                <value>
                    <fullName>Post 16 Qualifications</fullName>
                </value>
                <value>
                    <fullName>Early Years Qualifications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <label>Qualifications</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Qualification_Type2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>B.Ed + State Teaching Certification</fullName>
                </value>
                <value>
                    <fullName>BA + Teacher Training</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Arts / Bachelor of Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Arts/ Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Early Childhood Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education/ Bachelor of Science (Secondary)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education (Primary)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education (Special Education)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Health, Sport and Physical Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Primary Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Science and Education in Secondary Teaching</fullName>
                </value>
                <value>
                    <fullName>Bachelors Degree</fullName>
                </value>
                <value>
                    <fullName>BA or BSc + Teacher Training</fullName>
                </value>
                <value>
                    <fullName>BA with QTS</fullName>
                </value>
                <value>
                    <fullName>B ED</fullName>
                </value>
                <value>
                    <fullName>BED with QTS</fullName>
                </value>
                <value>
                    <fullName>BSC with QTS</fullName>
                </value>
                <value>
                    <fullName>BTEC</fullName>
                </value>
                <value>
                    <fullName>CACHE L1</fullName>
                </value>
                <value>
                    <fullName>CACHE L2</fullName>
                </value>
                <value>
                    <fullName>CACHE L3</fullName>
                </value>
                <value>
                    <fullName>CERT ED FE</fullName>
                </value>
                <value>
                    <fullName>City and Guilds 7307</fullName>
                </value>
                <value>
                    <fullName>CTLLS</fullName>
                </value>
                <value>
                    <fullName>Degree</fullName>
                </value>
                <value>
                    <fullName>Degree in Curriculum Subject</fullName>
                </value>
                <value>
                    <fullName>Dip In Childcare and Education</fullName>
                </value>
                <value>
                    <fullName>Dip In Play Work</fullName>
                </value>
                <value>
                    <fullName>Dip in Support Work in Schools</fullName>
                </value>
                <value>
                    <fullName>Diploma in Education &amp; Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_to_You__c</fullName>
        <label>Relationship to You</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SET_Expiry_Date__c</fullName>
        <label>SET Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SET_Registration_Number__c</fullName>
        <label>SET Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Safeguarding_Date_Completed__c</fullName>
        <label>Safeguarding Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update_Service_Status_Check__c</fullName>
        <label>Update Service Status Check</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current No Info</fullName>
                </value>
                <value>
                    <fullName>Current Info Held</fullName>
                </value>
                <value>
                    <fullName>No Longer Current</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>qualificationName__c</fullName>
        <formula>TR1__Qualification__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>qualificationName</label>
        <type>Text</type>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <recordTypes>
        <fullName>Qualifications</fullName>
        <active>false</active>
        <label>Qualifications</label>
    </recordTypes>
    <recordTypes>
        <fullName>Safeguarding</fullName>
        <active>false</active>
        <label>Safeguarding</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ts_earlyyearqualification.cls
public without sharing class ts_earlyyearqualification {
    
    @AuraEnabled
    public static String getContactId(){

        System.debug('In getContactId');

        User u  = [SELECT Id,ContactId from User where Id=:UserInfo.getUserId()];
        if(String.isNotBlank(u.contactId)){
            return u.ContactId;
        }
        else{
            return 'Id null';
        }
        
    }

    @AuraEnabled(cacheable=false)
    public static void editQuali(Id conId,String qfname,TR1__Associated_Qualification__c qual){
        System.debug('qual>>'+qual);
        TR1__Associated_Qualification__c qualList = [SELECT Id,Update_Service_Status_Check__c,QTLS__c,SET_Expiry_Date__c,Qualification_Type2__c,SET_Registration_Number__c,Relationship_to_You__c,Emergency_Contact_Address__c,Emergency_Contact_Home_Phone__c,Emergency_Contact_Work_Phone__c,Emergency_Contact_Mobile_Phone__c,Emergency_Contact_Name__c,DBS_Form_Number__c,On_Update_Service__c,Qualification_Type__c FROM TR1__Associated_Qualification__c WHERE TR1__Contact__c=:conId AND qualificationName__c =: qfname LIMIT 1];
        

        if(qual.qualificationName__c == 'Perm DBS'){
            System.debug('Inside Perm DBS');
            qualList.DBS_Form_Number__c = qual.DBS_Form_Number__c;  //Early Years Qualifications
            qualList.On_Update_Service__c = qual.On_Update_Service__c;
        }else if(qual.qualificationName__c == 'Safeguarding'){
            System.debug('Inside safeguarding');
            qualList.Safeguarding_Date_Completed__c = qual.Safeguarding_Date_Completed__c; //this is the date field
        }else if(qual.qualificationName__c == 'Emergency Contact'){
            System.debug('inside emergency contact');
            qualList.Relationship_to_You__c = qual.Relationship_to_You__c;
            qualList.Emergency_Contact_Address__c = qual.Emergency_Contact_Address__c;
            qualList.Emergency_Contact_Home_Phone__c = qual.Emergency_Contact_Home_Phone__c;
            qualList.Emergency_Contact_Mobile_Phone__c = qual.Emergency_Contact_Mobile_Phone__c;
            qualList.Emergency_Contact_Work_Phone__c = qual.Emergency_Contact_Work_Phone__c;
            qualList.Emergency_Contact_Name__c = qual.Emergency_Contact_Name__c;
        }else if(qual.qualificationName__c == 'DBS'){
            System.debug('Inside DBS');
            qualList.DBS_Form_Number__c = qual.DBS_Form_Number__c;          //this is dbs number
            qualList.Update_Service_Status_Check__c = qual.Update_Service_Status_Check__c;      //this is picklist for four options
        }else if(qual.qualificationName__c == 'Post 16 Qualifications'){
            System.debug('inside post 16 qualifications');
            qualList.SET_Registration_Number__c = qual.SET_Registration_Number__c;          //this is type string
            qualList.Qualification_Type2__c = qual.Qualification_Type2__c;
            qualList.SET_Expiry_Date__c = qual.SET_Expiry_Date__c;
            qualList.QTLS__c = qual.QTLS__c;
            qualList.Qualification_Type__c =  qual.Qualification_Type__c;           //this is restricted multi picklist 
        }

        System.debug('qualList>>>'+qualList);
        update qualList;
        System.debug('In editQualification');
    }
}