src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Candidate_Percentage__c</fullName>
        <label>Candidate Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Credit</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Closes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Percentage__c</fullName>
        <label>Job Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Marketing_Percentage__c</fullName>
        <label>Marketing Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Other2_Percentage__c</fullName>
        <label>Other2 Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Other_Percentage__c</fullName>
        <label>Other Percentage</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Closes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Expense_Report__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Closing_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report</label>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Expense Reports</relationshipLabel>
        <relationshipName>Expense_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expense Reports</relationshipLabel>
        <relationshipName>Expense_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unsubmitted</fullName>
                    <default>true</default>
                    <label>Unsubmitted</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense Report</label>
    <nameField>
        <displayFormat>EXP-{0000}</displayFormat>
        <label>Expense Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Timesheet Approver)</relationshipLabel>
        <relationshipName>Jobs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RC_ExpenseReportsTest.cls
@isTest
private class RC_ExpenseReportsTest 
{
	private static testMethod void test()  
	{
	    User u = RC_UtilityClass.returnCommunityContactTypeUser('c&c', 'testcc');
        User candidateUser = RC_UtilityClass.returnCommunityContactTypeUser('candidate', 'testcand');
        RC_ExpenseReports objExpenseReport = new RC_ExpenseReports();
        PageReference pg = objExpenseReport.redirectUnAuthenticatedUser();
        
        /* Create test data */
        TR1__Job__c objJob = RC_UtilityClass.insertJob();
        TR1__Closing_Report__c objClosingReport = new TR1__Closing_Report__c();
        objClosingReport.TR1__Job_Percentage__c = 20;
        objClosingReport.TR1__Candidate_Percentage__c  = 20;
        objClosingReport.TR1__Marketing_Percentage__c  = 20; 
        objClosingReport.TR1__Other_Percentage__c  = 20;
        objClosingReport.TR1__Other2_Percentage__c = 20; 
        objClosingReport.TR1__Job__c = objJob.id; 
        objClosingReport.TR1__Timesheet_Approver__c = u.ContactId;
        objClosingReport.TR1__Job_Credit__c = objJob.OwnerId;
        objClosingReport.TR1__Person_Placed__c = candidateUser.ContactId;
        insert objClosingReport;
        
        TR1__Expense_Report__c objExp = RC_UtilityClass.returnExpenseReport();
        objExp.TR1__Closing_Report__c = objClosingReport.id; 
        RC_AccessController.updateRecord(objExp);
        /* Create test data */
        
        
        System.assertEquals('/Signin',pg.getUrl());
        
        /*TR1__Expense_Report__c objExpRep = RC_UtilityClass.returnExpenseReport();*/
        objExp.TR1__Consultant__c = candidateUser.contactId;
        RC_AccessController.updateRecord(objExp);
        
        System.runAs(u)
        {
            objExpenseReport = new RC_ExpenseReports();
            pg = objExpenseReport.redirectUnAuthenticatedUser();
            System.assertEquals(null,pg);
            
            objExp = (TR1__Expense_Report__c)RC_AccessController.query('SELECT id, TR1__Status__c FROM TR1__Expense_Report__c LIMIT 1')[0];  
            System.assertEquals('Submitted',objExp.TR1__Status__c);
            
            objExpenseReport.idExp = objExp.id;
            objExpenseReport.approveExp();
            objExp = (TR1__Expense_Report__c)RC_AccessController.query('SELECT id, TR1__Status__c FROM TR1__Expense_Report__c LIMIT 1')[0]; 
            System.assertEquals('Approved',objExp.TR1__Status__c);
            
            objExp.TR1__Status__c = 'Submitted';
            RC_AccessController.updateRecord(objExp);
            objExpenseReport.strComment = 'Test'; 
            objExpenseReport.rejectExp(); 
            objExp = (TR1__Expense_Report__c)RC_AccessController.query('SELECT id, TR1__Status__c FROM TR1__Expense_Report__c LIMIT 1')[0]; 
        
            System.assertEquals('Rejected',objExp.TR1__Status__c);  
            
            
        } 
	}

}