src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>CV_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CV Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Documents__c</fullName>
        <label>Documents</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Permanent_Right_to_Work_in_UK__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UK Passport</fullName>
                </value>
                <value>
                    <fullName>EEA or Swiss Passport/ National Identity Card</fullName>
                </value>
                <value>
                    <fullName>Perm Residence Registration Certificate EEA or Swiss</fullName>
                </value>
                <value>
                    <fullName>Perm Residence Card</fullName>
                </value>
                <value>
                    <fullName>Current Biometric Immigration Doc (Resident Permit)</fullName>
                </value>
                <value>
                    <fullName>Passport with Indefinite Right to Remain</fullName>
                </value>
                <value>
                    <fullName>Current H.O. Immigration Status Doc + Perm NI No. Doc</fullName>
                </value>
                <value>
                    <fullName>Full UK Birth or Adoption Certificate + National Insurance Doc</fullName>
                </value>
                <value>
                    <fullName>Birth/Adopt Cert (Iss: Chanel Isle/ Isle of Man/ Ireland) + NI Doc</fullName>
                </value>
                <value>
                    <fullName>Cert of Registration/ Naturalisation as a British Citizen + NI Doc</fullName>
                </value>
                <value>
                    <fullName>Current Passport Showing Holder Can Stay in UK &amp; Do the Work in Qu</fullName>
                </value>
                <value>
                    <fullName>Current Residence Card</fullName>
                </value>
                <value>
                    <fullName>Current Immigration Status Doc + National Insurance Doc</fullName>
                </value>
                <value>
                    <fullName>Positive Verification Notice + Certificate of Application</fullName>
                </value>
                <value>
                    <fullName>Application Registration Card + Positive Verification notice</fullName>
                </value>
                <value>
                    <fullName>Positive Verification Notice</fullName>
                </value>
                <value>
                    <fullName>Small UK Birth or Adoption Certificate + National Insurance Doc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gaps_Explanation__c</fullName>
        <label>Gaps Explanation</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NCTL_Number__c</fullName>
        <label>NCTL Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_Right_to_Work_in_UK__c</fullName>
        <label>Permanent Right to Work in UK</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>UK Passport</fullName>
                </value>
                <value>
                    <fullName>EEA or Swiss passport/ National identity card</fullName>
                </value>
                <value>
                    <fullName>Perm residence Registration certificate EEA or Swiss</fullName>
                </value>
                <value>
                    <fullName>Perm residence card</fullName>
                </value>
                <value>
                    <fullName>Current biometric immigration doc (Resident permit)</fullName>
                </value>
                <value>
                    <fullName>Passport with indefinate right to remain</fullName>
                </value>
                <value>
                    <fullName>Current Home office immigration status document + Perm national insurance number doc</fullName>
                </value>
                <value>
                    <fullName>Full UK birth or adoption certificate + national insurance doc</fullName>
                </value>
                <value>
                    <fullName>Birth or adoption certificate issued in the Chanel Isle, Isle of Man or Ireland + National insurance doc</fullName>
                </value>
                <value>
                    <fullName>Certificate of registration or naturalisation as a British citizen + national insurance doc</fullName>
                </value>
                <value>
                    <fullName>Current passport showing the holder can stay in the UK and do the work in question</fullName>
                </value>
                <value>
                    <fullName>Current residence card</fullName>
                </value>
                <value>
                    <fullName>Current immigration status doc + National insurance doc</fullName>
                </value>
                <value>
                    <fullName>Positive Verification notice + certificate of application</fullName>
                </value>
                <value>
                    <fullName>Application registration card + positive verification notice</fullName>
                </value>
                <value>
                    <fullName>Positive verification notice</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Small UK Birth or Adoption Certificate + National Insurance Doc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QTLS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QTLS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SET_Registration_Number__c</fullName>
        <label>SET Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>qualificationName__c</fullName>
        <formula>TR1__Qualification__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>qualificationName</label>
        <type>Text</type>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>CV</fullName>
        <active>false</active>
        <label>CV</label>
    </recordTypes>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ts_MyQualificationDetailController.cls
public without sharing class ts_MyQualificationDetailController {


    @AuraEnabled
    public static String getContactId(){

        System.debug('In getContactId');

        User u  = [SELECT Id,ContactId from User where Id=:UserInfo.getUserId()];
        if(String.isNotBlank(u.contactId)){
            return u.ContactId;
        }
        else{
            return 'Id null';
        }
        
    }

    @AuraEnabled(cacheable=false)
    public static void editQuali(Id conId,String qfname,TR1__Associated_Qualification__c qual){
        System.debug('qual>>'+qual);
        TR1__Associated_Qualification__c qualList = [SELECT Id,Gaps_Explanation__c,CV_Submitted__c FROM TR1__Associated_Qualification__c WHERE TR1__Contact__c=:conId AND qualificationName__c =: qfname LIMIT 1];
        if(qual.qualificationName__c == 'CV'){
            qualList.Gaps_Explanation__c = qual.Gaps_Explanation__c;
            qualList.CV_Submitted__c = qual.CV_Submitted__c;
        }
        else if(qual.qualificationName__c == 'Perm Qualification'){
            System.debug('Perm');
            qualList.NCTL_Number__c = qual.NCTL_Number__c;
            qualList.SET_Registration_Number__c = qual.SET_Registration_Number__c;
            qualList.QTLS__c = qual.QTLS__c;
        }
        else if(qual.qualificationName__c == 'Right to Work'){
            System.debug('Perm');
            qualList.Permanent_Right_to_Work_in_UK__c = qual.Permanent_Right_to_Work_in_UK__c;
            qualList.Documents__c = qual.Documents__c;
        }
        System.debug('qualList>>>'+qualList);
        update qualList;
        System.debug('In editQualification');
    }
}