src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ts_MyQualificationsController.cls
public with sharing class ts_MyQualificationsController {


    @AuraEnabled
    public static List<TR1__Associated_Qualification__c> getQualification(){

        List<Schema.FieldSetMember> lstFieldSet = new List<Schema.FieldSetMember>(); 
        Contact con = [SELECT Id FROM Contact WHERE Id = '0030C00000SPlMiQAL']; //Added for test
        System.debug('test');
        List<TR1__Associated_Qualification__c> qualiList = new List<TR1__Associated_Qualification__c>();
        String fieldNames ='';
        String strQuery = 'Select Id'; 
        lstFieldSet = SObjectType.TR1__Associated_Qualification__c.FieldSets.getMap().get('RC_QualificationInfo').getFields(); 
        
        for(Schema.FieldSetMember field : lstFieldSet){
            fieldNames += ', ' + field.getFieldPath();
        }
        
        strQuery  += fieldNames + ' from TR1__Associated_Qualification__c where TR1__Contact__c = \'' + con.Id + '\' ORDER BY Name ASC' ;      
        qualiList = Database.query(strQuery);
        return qualiList;

    }
}