src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Qualification_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Package</label>
        <referenceTo>TR1__Qualification_Package__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>CV</fullName>
        <active>false</active>
        <label>CV</label>
    </recordTypes>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Field_Set_ID__c</fullName>
        <label>Field Set ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Qualification_Package__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualification Package</label>
    <nameField>
        <displayFormat>QP{YY}{MM}-{0000}</displayFormat>
        <label>Qualification Package</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssociatedQualificationDetailCtrlTest.cls
@isTest
public class AssociatedQualificationDetailCtrlTest {
    
    public static testmethod void testMethod1(){
        
        TR1__Qualification__c objQual = new TR1__Qualification__c(Name = 'Passport', TR1__Field_Set_ID__c = '321534');
        insert objQual;
        TR1__Qualification__c objQual1 =  new TR1__Qualification__c(Name = 'Resume', TR1__Field_Set_ID__c = '321534');
        insert objQual1;
        
        TR1__Qualification_Package__c objQualPkg  = new TR1__Qualification_Package__c(TR1__Name__c = 'OTT');
        insert objQualPkg;
        
        Id contactRecordType = schema.SObjectType.contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();
        Contact objContact = new Contact(recordTypeId = contactRecordType, LastName = 'TestLastName_AssoQual', Tax_Method__c = 'PAYE', email ='test@test328435634567294.com', phone  ='342336364', Subject__c  = 'Art', Year_Key_Stage__c ='KS1');
        insert objContact;
        
        TR1__Associated_Qualification__c objAssoQual = new TR1__Associated_Qualification__c(TR1__Qualification__c =objQual.Id, TR1__Qualification_Package__c = objQualPkg.Id); 
        insert objAssoQual;
        
        TR1__Associated_Qualification__c objAssoQual1 = new TR1__Associated_Qualification__c(TR1__Qualification__c =objQual1.Id, TR1__Qualification_Package__c = objQualPkg.Id); 
        insert objAssoQual1;
        
        PageReference pageRef = Page.AssociatedQualificationDetailPage;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(objAssoQual.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(objAssoQual);
        AssociatedQualificationDetailCtrl testAccPlan = new AssociatedQualificationDetailCtrl(sc);
        testAccPlan.goToStandardPage();
        testAccPlan.backToContact();
        testAccPlan.clickAddNote();
        testAccPlan.createNote();
        testAccPlan.backToCurrentRecord();
        
    }
    
    public static testmethod void testMethod2(){
        
        TR1__Qualification__c objQual = new TR1__Qualification__c(Name = 'Passport',TR1__Field_Set_ID__c = 'CV');
        insert objQual;
        TR1__Qualification__c objQual1 =  new TR1__Qualification__c(Name = 'Resume', TR1__Field_Set_ID__c = '321534');
        insert objQual1;
        
        TR1__Qualification_Package__c objQualPkg  = new TR1__Qualification_Package__c(TR1__Name__c = 'OTT');
        insert objQualPkg;
        
        Id contactRecordType = schema.SObjectType.contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();
        Contact objContact = new Contact(recordTypeId = contactRecordType, LastName = 'TestLastName_AssoQual', Tax_Method__c = 'PAYE', email ='test@test328435634567294.com', phone  ='342336364', Subject__c  = 'Art', Year_Key_Stage__c ='KS1');
        insert objContact;
        
        TR1__Associated_Qualification__c objAssoQual = new TR1__Associated_Qualification__c(TR1__Qualification__c =objQual.Id, TR1__Qualification_Package__c = objQualPkg.Id); 
        insert objAssoQual;
        
        TR1__Associated_Qualification__c objAssoQual1 = new TR1__Associated_Qualification__c(TR1__Qualification__c =objQual1.Id, TR1__Qualification_Package__c = objQualPkg.Id); 
        insert objAssoQual1;
        
        Note n = new Note();
        n.Title ='test';
        n.Body ='test';
        n.IsPrivate = true;
        n.ParentId =objAssoQual.id;
        insert n;
        
        PageReference pageRef = Page.AssociatedQualificationDetailPage;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', String.valueOf(objAssoQual.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(objAssoQual);
        AssociatedQualificationDetailCtrl testAccPlan = new AssociatedQualificationDetailCtrl(sc);
        testAccPlan.goToStandardPage();
        testAccPlan.backToContact();
        testAccPlan.clickAddNote();
        testAccPlan.createNote();
        testAccPlan.backToCurrentRecord();
        
    }
}