src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Clear_DBS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clear DBS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DBS_Disclosure_Notes__c</fullName>
        <label>DBS Disclosure Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Type2__c</fullName>
        <label>Qualification Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Overseas Qualifications - Aus/NZ</fullName>
                </value>
                <value>
                    <fullName>Overseas Qualifications - Canada</fullName>
                </value>
                <value>
                    <fullName>Overseas Qualifications - USA</fullName>
                </value>
                <value>
                    <fullName>Overseas Qualifications - Other</fullName>
                </value>
                <value>
                    <fullName>Teacher Qualification</fullName>
                </value>
                <value>
                    <fullName>Support Qualifications</fullName>
                </value>
                <value>
                    <fullName>Post 16 Qualifications</fullName>
                </value>
                <value>
                    <fullName>Early Years Qualifications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <label>Qualifications</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Qualification_Type2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>B.Ed + State Teaching Certification</fullName>
                </value>
                <value>
                    <fullName>BA + Teacher Training</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Arts / Bachelor of Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Arts/ Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Early Childhood Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education/ Bachelor of Science (Secondary)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education (Primary)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education (Special Education)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Health, Sport and Physical Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Primary Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Science and Education in Secondary Teaching</fullName>
                </value>
                <value>
                    <fullName>Bachelors Degree</fullName>
                </value>
                <value>
                    <fullName>BA or BSc + Teacher Training</fullName>
                </value>
                <value>
                    <fullName>BA with QTS</fullName>
                </value>
                <value>
                    <fullName>B ED</fullName>
                </value>
                <value>
                    <fullName>BED with QTS</fullName>
                </value>
                <value>
                    <fullName>BSC with QTS</fullName>
                </value>
                <value>
                    <fullName>BTEC</fullName>
                </value>
                <value>
                    <fullName>CACHE L1</fullName>
                </value>
                <value>
                    <fullName>CACHE L2</fullName>
                </value>
                <value>
                    <fullName>CACHE L3</fullName>
                </value>
                <value>
                    <fullName>CERT ED FE</fullName>
                </value>
                <value>
                    <fullName>City and Guilds 7307</fullName>
                </value>
                <value>
                    <fullName>CTLLS</fullName>
                </value>
                <value>
                    <fullName>Degree</fullName>
                </value>
                <value>
                    <fullName>Degree in Curriculum Subject</fullName>
                </value>
                <value>
                    <fullName>Dip In Childcare and Education</fullName>
                </value>
                <value>
                    <fullName>Dip In Play Work</fullName>
                </value>
                <value>
                    <fullName>Dip in Support Work in Schools</fullName>
                </value>
                <value>
                    <fullName>Diploma in Education &amp; Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Package</label>
        <referenceTo>TR1__Qualification_Package__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>CV</fullName>
        <active>false</active>
        <label>CV</label>
    </recordTypes>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <recordTypes>
        <fullName>Medical</fullName>
        <active>false</active>
        <label>Medical</label>
    </recordTypes>
    <recordTypes>
        <fullName>Qualifications</fullName>
        <active>false</active>
        <label>Qualifications</label>
    </recordTypes>
    <recordTypes>
        <fullName>References</fullName>
        <active>false</active>
        <label>References</label>
    </recordTypes>
    <recordTypes>
        <fullName>Safeguarding</fullName>
        <active>false</active>
        <label>Safeguarding</label>
    </recordTypes>
    <recordTypes>
        <fullName>TOE</fullName>
        <active>false</active>
        <label>TOE</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Field_Set_ID__c</fullName>
        <label>Field Set ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Qualification_Package__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Qualification Packages</relationshipLabel>
        <relationshipName>Qualification_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualification Package</label>
    <nameField>
        <displayFormat>QP{YY}{MM}-{0000}</displayFormat>
        <label>Qualification Package</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FB_AQReportCtrTest.cls
@isTest
public class FB_AQReportCtrTest {
    static testMethod void unitTes(){
        List<TR1__Qualification__c> qualificationList = New List<TR1__Qualification__c>();
        List<String> qualiLIst = New List<String> {'DBS','Perm Qualification','ID','Teacher Qualification','Medical','References', 
            'Disqualification by Association','TOE','Right to Work', 'Overseas Police Check','Overseas Teacher Qualifications','Early Years Qualifications',
            'Support Qualifications','Post 16 Qualifications','Overseas DBS Check','CV' ,'Safeguarding'   };
                
                for(String s : qualiLIst) {
                    TR1__Qualification__c objQual = new TR1__Qualification__c(Name = s, TR1__Field_Set_ID__c = '321534', Abbreviation__c = s);
                    qualificationList.add(objQual);
                }   
        
        insert qualificationList;
        
        List<TR1__Qualification__c> objQualification = [SELECT Id, Name, Abbreviation__c FROM TR1__Qualification__c WHERE Name IN : qualiLIst ];
        
        Id contactRecordType = schema.SObjectType.contact.getRecordTypeInfosByName().get('Candidate').getRecordTypeId();
        Contact con = new Contact(RecordTypeId = contactRecordType,LastName='test Contact123',Email='test@test32525.com',Phone='2343423',MobilePhone='1223343433',Subject__c ='Business Studies',Preferred_LEA__c='Blackpool',Tax_Method__c = 'PAYE');
        insert con;
        Id conId = con.Id; 
        
        ID qualiId = objQualification[0].Id;
        
        TR1__Qualification_Package__c objQualPkg  = new TR1__Qualification_Package__c(TR1__Name__c = 'OTT');
        insert objQualPkg;
        
        TR1__Associated_Qualification__c objAssoQual = new TR1__Associated_Qualification__c(TR1__Qualification__c =qualiId, TR1__Contact__c = conId, TR1__Qualification_Package__c = objQualPkg.Id,Clear_DBS__c=true,TR1__Status__c='Submitted',DBS_Disclosure_Notes__c='test',Qualification_Type2__c='Teacher Qualification',Qualification_Type__c='Bachelor of Arts/ Education');
        insert objAssoQual;
        
        Integer index = 200;
        PageReference pageRef = Page.FB_AQReport;
        pageRef.getParameters().put('iStart', String.valueOf(index));
        Test.setCurrentPage(pageRef);

        FB_AQReportCtr oFBAQReportCtr = new FB_AQReportCtr();
        FB_AQReportCtr.AQWrapper at = new FB_AQReportCtr.AQWrapper(con, objQualification);
        oFBAQReportCtr.doGenerate();
    }
}