src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ComplianceDetailPageControllerTest.cls
@isTest
public class ComplianceDetailPageControllerTest {
    
    public static testMethod void maintest(){
        
        test.startTest();
            Contact newcon = new Contact(lastname = 'test', email = 'test@test522525.com', phone = '34234234');
            insert newcon;        
            List< TR1__Qualification__c > listqlfns = new List< TR1__Qualification__c >();
            for(Integer i=0;i<5;i++){
                TR1__Qualification__c qualfn = new TR1__Qualification__c(Name='testqual'+i,Description__c='testdesc'+i);
                listqlfns.add(qualfn);
            }
            insert listqlfns;
            List< TR1__Associated_Qualification__c > listasqlfns = new List< TR1__Associated_Qualification__c >();
            for(Integer i=0;i<4;i++){
                TR1__Associated_Qualification__c qualfn = new TR1__Associated_Qualification__c(TR1__Qualification__c=listqlfns[i].Id,TR1__Contact__c=newcon.Id);
                listasqlfns.add(qualfn);
            }
            insert listasqlfns;
            pageReference pr = new pageReference('/apex/ComplianceDetailPage');
            test.setCurrentPageReference(pr);
            ApexPages.currentPage().getParameters().put('id',newcon.Id);
            ApexPages.StandardController str = new ApexPages.StandardController(newcon);
            ComplianceDetailPageController compdetobj = new ComplianceDetailPageController(str);
            compdetobj.redirectToCompliance();
        test.stopTest();
    }
}