src/objects/TR1__Timesheet__c.object
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Double_Time_Hours__c</fullName>
        <label>Double Time Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Expenses__c</fullName>
        <label>Expenses</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Overtime_Hours__c</fullName>
        <label>Overtime Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Regular_Hours__c</fullName>
        <label>Regular Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Sick_Time_Hours__c</fullName>
        <label>Sick Time Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>TR1__Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Vacation_Hours__c</fullName>
        <label>Vacation Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Timesheet Detail</label>
    <nameField>
        <displayFormat>TS-{MM}{DD}{YY}-{0}</displayFormat>
        <label>Timesheet Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimesheetPrintController_v2.cls
public with sharing class TimesheetPrintController_v2 {


    public String[] timesheetIds                           {get;set;}
    public transient List<TR1__Timesheet__c> timesheetList                      {get;set;}
    public transient List<TimesheetPrintWrapper> TimesheetPrintWrapperList          {get;set;}
    public integer LastPdf {get;set;}
    public Boolean isClient {get;set;}
    public User loggedInUser ;
    public Contact objContactPage {get;set; }

    // public integer getPageCount(){
    //     return TimesheetPrintWrapperList.size();
    // }

    public TimesheetPrintController_v2() {

        TimesheetPrintWrapperList = new List<TimesheetPrintWrapper> ();
        system.debug('TimesheetList: '+System.currentPageReference().getParameters().get('timesheetIds'));
        String[] timesheetIds = ((String)System.currentPageReference().getParameters().get('timesheetIds')).split(';');
        loggedInUser = [Select ContactId from User where Id =: UserInfo.getUserId() limit 1];
        if(!test.isrunningtest()){
            objContactPage = [Select Community_Contact_Type__c,Name from Contact where Id =:loggedInUser.ContactId limit 1];


            if(objContactPage.Community_Contact_Type__c == 'Candidate' || objContactPage.Community_Contact_Type__c == 'C And C'  ){
                isClient = false;
            }else if(objContactPage.Community_Contact_Type__c == 'Client'){
                isClient = true;
            }
        }

        timesheetList = RC_AccessController.getTimesheetsByIds(timesheetIds);
        
        calculatehours();
    }

    public void calculatehours(){
        integer lstCount = 0;
        for(TR1__Timesheet__c timesheet : timesheetList) {
            TimesheetPrintWrapper wrapper = new TimesheetPrintWrapper(timesheet , ++lstCount)  ;
            for(TR1__Timesheet_Detail__c td : timesheet.TR1__Timecards__r){
                if(td.TR1__Double_Time_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Double_Time_Hours__c;
                if(td.TR1__Expenses__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Expenses__c;
                if(td.TR1__Overtime_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Overtime_Hours__c;
                if(td.TR1__Regular_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Regular_Hours__c;
                if(td.TR1__Sick_Time_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Sick_Time_Hours__c;
                if(td.TR1__Vacation_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Vacation_Hours__c;
            }
            TimesheetPrintWrapperList.add(wrapper);
        }
        LastPdf = TimesheetPrintWrapperList.size();
    }

    public class TimesheetPrintWrapper {

        public Double totalHours               {get;set;}
        public integer index                 {get;set;}
        public TR1__Timesheet__c timesheet      {get;set;}

        public TimesheetPrintWrapper(TR1__Timesheet__c timesheet,integer index) {
            this.timesheet =  timesheet;
            totalHours = 0;
            this.index = index;

        }
    }
}