src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <recordTypes>
        <fullName>Photo</fullName>
        <active>false</active>
        <label>Photo</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_ViewAttachmentController.cls
@isTest
public class Test_ViewAttachmentController {
	@isTest
    static void testInsertAccount(){
                
        Contact con = new Contact();
        con.LastName = 'Demo';
        con.Compliance_Owner__c = UserInfo.getUserId();
        insert con;
        TR1__Qualification__c qul = new TR1__Qualification__c();
        qul.Name='Photo';
        insert qul;
        
        TR1__Associated_Qualification__c asst= new TR1__Associated_Qualification__c();
        asst.TR1__Status__c='Requested';
        asst.TR1__Contact__c = con.Id;
        asst.TR1__Qualification__c = qul.Id;
        Insert asst;
        
        Attachment attach=new Attachment();   	
    	attach.Name='Unit Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=asst.id;
        insert attach;
        
      	ViewAttachmentController.getContents(con.Id);
    }
}