src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Source_Associated_Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Associated Qualification</label>
        <referenceTo>TR1__Associated_Qualification__c</referenceTo>
        <relationshipLabel>Compliance Documents (Source Associated Qualification)</relationshipLabel>
        <relationshipName>Source_Compliance_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Require_Documents__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Require Documents</label>
        <type>Checkbox</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewAssociatedQualification_Test.cls
@isTest
public class ViewAssociatedQualification_Test {
    static testMethod void testViewAssociateQualification() {
        Test.startTest();
        Contact objContact = new Contact(LastName = 'TestContact', phone = '231233', mobilePhone = '3432423', email = 'test@test.com', Subject__c = 'Art', Year_Key_Stage__c = 'KS1');
        insert objContact;
        TR1__Qualification__c objQualifiation = H_Utility_Test.createQualification('Graduation');
        TR1__Associated_Qualification__c objSourceAQ = H_Utility_Test.createAssociateQualification(objQualifiation.Id, null, null);

        TR1__Associated_Qualification__c objAQ = H_Utility_Test.createAssociateQualification(objQualifiation.Id, objContact.Id, null);
        objAQ.Source_Associated_Qualification__c = objSourceAQ.Id;
        update objAQ;

        PageReference pref;
        pref = Page.ViewAssociatedQualification;
        pref.getParameters().put('id', objAQ.id);
        pref.getParameters().put('retURL', objContact.id);
        Test.setCurrentPage(pref);

        ApexPages.StandardController sc = new ApexPages.StandardController(objAQ);
        ViewAssociatedQualification objViewAQ = new ViewAssociatedQualification(sc);
        objViewAQ.goToStandardPage();
        objViewAQ.doCancelAQ();

        TR1__Associated_Qualification__c objAQ1 = H_Utility_Test.createAssociateQualification(objQualifiation.Id, null, null);
        sc = new ApexPages.StandardController(objAQ1);
        objViewAQ = new ViewAssociatedQualification(sc);
        objViewAQ.goToStandardPage();
        objQualifiation.Require_Documents__c = true;
        update objQualifiation;
        objViewAQ.saveAQ();
        objAQ1.TR1__Status__c = 'Active';
        sc = new ApexPages.StandardController(objAQ1);
        objViewAQ = new ViewAssociatedQualification(sc);
        objViewAQ.goToStandardPage();
        objQualifiation.Require_Documents__c = false;
        update objQualifiation;
        delete objAQ1;
        objViewAQ.saveAQ();
        Test.stopTest();
    }

    static testMethod void testAssociateQualificationDetail() {
        Test.startTest();
        Contact objContact = new Contact(LastName = 'TestContact', phone = '231233', mobilePhone = '3432423', email = 'test@test.com', Subject__c = 'Art', Year_Key_Stage__c = 'KS1');
        insert objContact;
        TR1__Qualification__c objQualifiation = H_Utility_Test.createQualification('Graduation');
        ViewAssociatedQualification.AddInfoMessage('Test value');
        ViewAssociatedQualification.AddWarningMessage('Test value');
        ViewAssociatedQualification.AddConfirmMessage('Test value');
        ViewAssociatedQualification.AddErrorMessage('Test value');
        ViewAssociatedQualification.AddFatalMessage('Test value');
        Test.stopTest();
    }
}