src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Booking Confirmed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Confirmed__c</fullName>
        <formula>TR1__Closing_Report__r.Booking_Confirmed__c</formula>
        <label>Booking Confirmed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_account_number__c</fullName>
        <formula>TR1__Client__r.Account_Code_S__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client account number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payroll_number__c</fullName>
        <formula>TR1__Consultant__r.Payroll_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payroll number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Closing_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report</label>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Changed By Payroll</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Unsubmitted</fullName>
                    <default>true</default>
                    <label>Unsubmitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Total_Bill_Override__c</fullName>
        <label>Total Bill (Override)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Total_Pay_Override__c</fullName>
        <label>Total Pay (Override)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/autoSubmitTimesheetsBatch.cls
public class autoSubmitTimesheetsBatch implements Database.Batchable < TR1__Timesheet__c >,Database.Stateful {
    public Map<Id,String> entityToErrorMessageMap;
    public List<String> toAddressList;
    public Set<Id> successList;
    
    public autoSubmitTimesheetsBatch(){
        entityToErrorMessageMap = new Map<Id,String>();
        toAddressList = new List<String>();
        successList = new Set<Id>();
        //Populate Email Recepient List
        Set<String> toAddressesSet = new Set<String>();
        toAddressesSet.add(UserInfo.getUserEmail());
        if(String.isNotBlank(Label.SubmitTimesheet_EmailNotificationList)){
            toAddressesSet.addAll(Label.SubmitTimesheet_EmailNotificationList.split(','));
        }
        toAddressList.addAll(toAddressesSet);        
    }
    
    public Iterable < TR1__Timesheet__c > start(Database.BatchableContext BC) {
        date currWeekStart = date.today().toStartofWeek();
        String currStartWeekDay = TimesheetUtility.dayOfDate(currWeekStart);
        Date upcomingSundayDate;
        if (currStartWeekDay == 'Monday')
            upcomingSundayDate = currWeekStart.addDays(6);
        else if (currStartWeekDay == 'Sunday')
            upcomingSundayDate = currWeekStart.addDays(7);
        System.debug('===================upcomingSundayDate==================' + upcomingSundayDate);
        String query = '';
        
        if(!Test.isRunningTest()){
            query = 'SELECT Id, TR1__Status__c FROM TR1__Timesheet__c WHERE TR1__Status__c = \'Unsubmitted\' AND TR1__Week_Ending__c != null AND Client_account_number__c != null AND Payroll_number__c != null AND TR1__Total_Bill_Override__c != 0 AND TR1__Total_Pay_Override__c != 0 ';
            query += ' AND TR1__Closing_Report__r.Booking_Confirmed__c = true AND TR1__Week_Ending__c <=: upcomingSundayDate';
        }
        else
        {
            query = 'SELECT Id, TR1__Status__c FROM TR1__Timesheet__c WHERE TR1__Status__c = \'Unsubmitted\' ';
        }
        
        List < TR1__Timesheet__c > timesheetLIst =  Database.query(query);
        system.debug('=================================timesheetLIst===='+timesheetLIst);
        return timesheetLIst;  
    }

    public void execute(Database.BatchableContext BC, List < TR1__Timesheet__c > scopeTimesheetList) {
        List < TR1__Timesheet__c > updateTimesheetList = New List < TR1__Timesheet__c > ();
        for (TR1__Timesheet__c t: scopeTimesheetList) {
            t.TR1__Status__c = 'Submitted';
            updateTimesheetList.add(t);
        } // end for 
        system.debug('==========================updateTimesheetList====' + updateTimesheetList);
        if (updateTimesheetList.size() > 0) {
            List < Database.SaveResult > srList = Database.update(updateTimesheetList, false);
            for (Database.SaveResult sr : srList){
                if (!sr.isSuccess()) {
                    entityToErrorMessageMap.put(sr.getId(),sr.getErrors()[0].getMessage());
                }
                else {
                    successList.add(sr.getId());
                }
            }            
        }
    }

    public void finish(Database.BatchableContext context) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddressList);
        mail.setSubject('Auto Submit Timesheet : Completed : '+context.getJobId());
        String htmlBody = 'The "Auto Submit Timesheet" Apex job # '+context.getJobId()+' finished update of timesheets with ' + successList.size() +' success and '+ entityToErrorMessageMap.size() + ' errors.<br/><br/>';
        
        if(successList.size()>0) {
            htmlBody += '****************Success List*************************<br/><br/>'; 
            for(String s : successList) {
                htmlBody += s+'<br/>'; 
            }
        }
        
        if(entityToErrorMessageMap.size()>0) {
            htmlBody += '****************Error List***************************<br/><br/>'; 
            Integer i = 1;
            for(String id : entityToErrorMessageMap.keyset()){
                htmlBody += (i++)+' :: Entity Id : '+ id +' :: Error : '+entityToErrorMessageMap.get(id) + '<br/><br/>';
            }
        }
        
        mail.setHTMLBody(htmlBody);
        if(!Test.isRunningTest() && toAddressList.size()>0){ //Send email if they have specified atleat 1 email address
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }        
    }
}