src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Closing_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Closes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Second_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Second Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports (Timesheet Second Approver)</relationshipLabel>
        <relationshipName>SecondApproverCR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timesheet_Frequency__c</fullName>
        <label>Timesheet Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                    <default>true</default>
                    <label>Weekly</label>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Timesheet Approver)</relationshipLabel>
        <relationshipName>Jobs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Timesheets (Timesheet Approver)</relationshipLabel>
        <relationshipName>Timesheets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Closing_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Closing Report</label>
        <referenceTo>TR1__Closing_Report__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Order__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Pay_Week_Ending__c</fullName>
        <label>Pay Week Ending</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Changed By Payroll</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Unsubmitted</fullName>
                    <default>true</default>
                    <label>Unsubmitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Timesheet_Second_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Second Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Timesheets (Timesheet Second Approver)</relationshipLabel>
        <relationshipName>SecondApprover</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Day__c</fullName>
        <label>Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>TR1__Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Timesheet Detail</label>
    <nameField>
        <displayFormat>TS-{MM}{DD}{YY}-{0}</displayFormat>
        <label>Timesheet Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimesheetUtility_v1.cls
//*********************************//
// Description: Timesheet Utility Class to hold some common function which can be used from anywhere.
// Created By: Chirag Mehta 
//*********************************//
public class TimesheetUtility_v1 {        
    public static String dayOfDate(Date d) {
        Datetime dt = DateTime.newInstance(d.year(), d.month(), d.day());
        return dt.format('EEEE'); //returns Sunday or Monday or .. 
    }
        
    /**        
        Added below logic to calculate start and end date based on timsheet type ie weekly or bi-weekly etc
     **/    
    public static date calculateStartDateBasedOnTimesheetType(Date selectedDate, String TimesheetType){
        Date returndate; 
        if(TimesheetType == 'Weekly')
            returndate = SelectedDate.toStartOfWeek();
        else if(TimesheetType == 'Calendar Monthly')
            returndate = SelectedDate.toStartOfMonth();
        else //default to Weekly
            returndate = SelectedDate.toStartOfWeek();        
        return returndate;
    }

    public static date calculateEndDateBasedOnTimesheetType(Date selectedDate, String TimesheetType){
        Date returndate;
        if(TimesheetType == 'Weekly')
            returndate = SelectedDate.toStartOfWeek().addDays(6);
        else if(TimesheetType == 'Calendar Monthly')
            returndate = SelectedDate.toStartOfMonth().addMonths(1)-1;
        else //default to Weekly
            returndate = SelectedDate.toStartOfWeek().addDays(6);
        return returndate;
    }
    
    public static String insertTimesheetDetail(List<TR1__Closing_Report__c> CRList,Date runDate){
        List < TR1__Timesheet__c > timesheets = new List < TR1__Timesheet__c > ();
        List < TR1__Timesheet_Detail__c > timesheetdetails = new List < TR1__Timesheet_Detail__c > ();
        Map<Id,Id> closingReportToTimesheetIdMap = new Map<Id,Id> ();
        for(TR1__Closing_Report__c cr : CRList){
            if(cr.TR1__End_Date__c==null || cr.TR1__Start_Date__c==null) continue;
            Date weekenddate = calculateEndDateBasedOnTimesheetType(runDate,cr.Timesheet_Frequency__c);
            weekenddate = weekenddate < cr.TR1__End_Date__c ? weekenddate : cr.TR1__End_Date__c;
            TR1__Timesheet__c ts = new TR1__Timesheet__c();
            ts.TR1__Status__c = 'Unsubmitted';
            ts.TR1__Closing_Report__c = cr.Id;
            ts.TR1__Consultant__c = cr.TR1__Person_Placed__c;
            ts.TR1__Job_Order__c = cr.TR1__Job__c;
            ts.TR1__Approver__c = cr.TR1__Timesheet_Approver__c;
            ts.TR1__Client__c = cr.TR1__Account__c;
            ts.TR1__Week_Ending__c = weekenddate;
            ts.TR1__Pay_Week_Ending__c = getPayWeekendingDate(ts.TR1__Week_Ending__c);//Hardik@10May2016 : Updated logic to set 7th Day of Week i.e. Sunday even if closing report has end date in between week.
            timesheets.add(ts);             
        }
        try{
            if(timesheets.size()>0) {
                insert timesheets;
                for(TR1__Timesheet__c ts : timesheets){
                    closingReportToTimesheetIdMap.put(ts.TR1__Closing_Report__c,ts.Id);
                }
            }
            system.debug('\n@@@@@@ no error while inserting Timesheet details'); 
        }catch (DMLException ex) {
            system.debug('\n@@@@@@ error while inserting Timesheet details'); 
        }
        for(TR1__Closing_Report__c cr : CRList){
            if(cr.TR1__End_Date__c==null || cr.TR1__Start_Date__c==null) continue;
            
            Date StartOfWeek = calculateStartDateBasedOnTimesheetType(runDate , cr.Timesheet_Frequency__c);
            StartOfWeek = (StartOfWeek >= cr.TR1__Start_Date__c) ? StartOfWeek : cr.TR1__Start_Date__c;
            
            Date EndOfWeek = calculateEndDateBasedOnTimesheetType(runDate , cr.Timesheet_Frequency__c);
            EndOfWeek = (EndOfWeek <= cr.TR1__End_Date__c) ? EndOfWeek : cr.TR1__End_Date__c;

            Integer numberDaysDue = StartOfWeek.daysBetween(EndOfWeek);
            for (Integer i = 0 ; i <= numberDaysDue; i++) {
                TR1__Timesheet_Detail__c td = new TR1__Timesheet_Detail__c(TR1__Timesheet__c = closingReportToTimesheetIdMap.get(cr.Id), TR1__Date__c = StartOfWeek.addDays(i), TR1__Day__c = dayOfDate(StartOfWeek.addDays(i)));
                timesheetdetails.add(td);
            }
        }
        try{
            if(timesheetdetails.size()>0) {
                insert timesheetdetails;
            }
            String msg = String.valueOf(timesheets[0].Id);            
            return msg;                
        }catch (Exception ex) {
            String msg = 'Timesheet cannot be created due to the following Reasons:<br/>'+Label.TimesheetCreation_ErrorMessage+'<br/>Error Details:'+ex.getMessage();
            return msg;
        }        
    }  
    
    public static String insertTimesheetDetail(TR1__Closing_Report__c cr,Date startDate,Date endDate){
        if(cr.TR1__End_Date__c==null || cr.TR1__Start_Date__c==null) return null;

        List < TR1__Timesheet__c > timesheets = new List < TR1__Timesheet__c > ();        
        List < TR1__Timesheet_Detail__c > timesheetdetails = new List < TR1__Timesheet_Detail__c > ();
        
        for(Date runDate=startDate;runDate<=endDate;){
            Date weekenddate = calculateEndDateBasedOnTimesheetType(runDate,cr.Timesheet_Frequency__c);
            weekenddate = weekenddate < cr.TR1__End_Date__c ? weekenddate : cr.TR1__End_Date__c;
            TR1__Timesheet__c ts = new TR1__Timesheet__c();
            ts.TR1__Status__c = 'Unsubmitted';
            ts.TR1__Closing_Report__c = cr.Id;
            ts.TR1__Consultant__c = cr.TR1__Person_Placed__c;
            ts.TR1__Job_Order__c = cr.TR1__Job__c;
            ts.TR1__Approver__c = cr.TR1__Timesheet_Approver__c;
            ts.TR1__Timesheet_Second_Approver__c = cr.TR1__Timesheet_Second_Approver__c;
            ts.TR1__Client__c = cr.TR1__Account__c;
            ts.TR1__Week_Ending__c = weekenddate;
            ts.TR1__Pay_Week_Ending__c = getPayWeekendingDate(ts.TR1__Week_Ending__c);//Hardik@10May2016 : Updated logic to set 7th Day of Week i.e. Sunday even if closing report has end date in between week.
            timesheets.add(ts);  
            runDate = cr.Timesheet_Frequency__c=='Calendar Monthly'?runDate.addMonths(1):runDate.addDays(7);           
        }
        try{
            if(timesheets.size()>0) {
                insert timesheets;
                //Start Timesheet Detail Creation
                for(TR1__Timesheet__c t : timesheets){
                    Date runDate =  t.TR1__Week_Ending__c;   
                    Date StartOfWeek = calculateStartDateBasedOnTimesheetType(runDate,cr.Timesheet_Frequency__c);
                    StartOfWeek = (StartOfWeek >= cr.TR1__Start_Date__c) ? StartOfWeek : cr.TR1__Start_Date__c;
                    
                    Date EndOfWeek = calculateEndDateBasedOnTimesheetType(runDate,cr.Timesheet_Frequency__c);
                    EndOfWeek = (EndOfWeek <= cr.TR1__End_Date__c) ? EndOfWeek : cr.TR1__End_Date__c;
        
                    Integer numberDaysDue = StartOfWeek.daysBetween(EndOfWeek);
                    for (Integer i = 0 ; i <= numberDaysDue; i++) {
                        TR1__Timesheet_Detail__c td = new TR1__Timesheet_Detail__c(TR1__Timesheet__c = t.Id, TR1__Date__c = StartOfWeek.addDays(i), TR1__Day__c = dayOfDate(StartOfWeek.addDays(i)));
                        timesheetdetails.add(td);
                    }
                }
                if(timesheetdetails.size()>0) {
                    insert timesheetdetails;
                    return String.valueOf(timesheets[0].Id);            
                }                
            }
        }catch (DMLException ex) {
            system.debug('\n@@@@@@ error while inserting Timesheet details'); 
            return 'Timesheet cannot be created due to the following Reasons:<br/>'+Label.TimesheetCreation_ErrorMessage+'<br/>Error Details:'+ex.getMessage();
        }  
        return 'Timesheet cannot be created due to the following Reasons:<br/>'+Label.TimesheetCreation_ErrorMessage;
    }
    
    public static Date getPayWeekendingDate(Date weekendingDate){//Hardik@10May2016 : Updated logic to set 7th Day of Week i.e. Sunday even if closing report has end date in between week.
        if(dayOfDate(weekendingDate) == 'Sunday'){
            return weekendingDate;
        }
        else{
            return weekendingDate.toStartOfWeek().addDays(6);
        }
    }
}