src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isBatch_updated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isBatch updated</label>
        <type>Checkbox</type>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_AssociateQualificationsBatch.cls
@isTest
private class Test_AssociateQualificationsBatch {

	private static testMethod void batchQualification() {
        Contact con = new Contact();
        con.LastName = 'Demo';
        con.Compliance_Owner__c = UserInfo.getUserId();
        insert con;
        
        List<TR1__Qualification__c> quaList = new List<TR1__Qualification__c>();
        
        for(Integer i=0; i<10; i++){
            quaList.add(new TR1__Qualification__c(Name = 'Barred List'+i));
        }
        
    
        insert quaList;
    
        List<TR1__Associated_Qualification__c> assQuaList = new List<TR1__Associated_Qualification__c>();
        
        for(Integer i=0; i<10; i++){
           assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[i].Id));
        }
        
        insert assQuaList;
        
        Test.startTest();
            AssociateQualificationsBatch bq = new AssociateQualificationsBatch('SELECT Id, isBatch_updated__c FROM TR1__Associated_Qualification__c');
            Database.executeBatch(bq,200);
            AssociateQualificationsBatch bq1 = new AssociateQualificationsBatch('SELECT Id FROM TR1__Qualification__c');
            Database.executeBatch(bq1,200);
        Test.stopTest();
	}

}