src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>ComplianceStatus__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + Id+&apos;/e&apos;,


CASE(TEXT( TR1__Status__c ),
&apos;Requested&apos;, IMAGE(&apos;/resource/ComplianceImages/No.png&apos;, TEXT( TR1__Status__c ), 20, 70) ,
&apos;Active&apos;, IMAGE(&apos;/resource/ComplianceImages/Yes.png&apos;, &apos;Approved&apos;, 20, 70) ,
&apos;Submitted&apos;, IMAGE(&apos;/resource/ComplianceImages/RV.png&apos;, &apos;Requires Verification&apos;, 20, 70),
&apos;In Progress&apos;, IMAGE(&apos;/resource/ComplianceImages/MR.png&apos;, &apos;More Required&apos;, 20, 70),
&apos;Rejected&apos;, IMAGE(&apos;/resource/ComplianceImages/No.png&apos;, TEXT( TR1__Status__c ), 20, 70),
&apos;Expired&apos;, IMAGE(&apos;/resource/ComplianceImages/RV.png&apos;, &apos;Requires Verification&apos;, 20, 70)
,IMAGE(&apos;/resource/ComplianceImages/No.png&apos;, &apos;None&apos;, 20, 70))


,&apos;_parent&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Visual (Status)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Registered</fullName>
                </value>
                <value>
                    <fullName>Vet Complete</fullName>
                </value>
                <value>
                    <fullName>Vet Perm</fullName>
                </value>
                <value>
                    <fullName>Vet FLTP</fullName>
                </value>
                <value>
                    <fullName>Interview Complete</fullName>
                </value>
                <value>
                    <fullName>Not Clear</fullName>
                </value>
                <value>
                    <fullName>Clearance Pending</fullName>
                </value>
                <value>
                    <fullName>Cleared</fullName>
                </value>
                <value>
                    <fullName>Not Compliant</fullName>
                </value>
                <value>
                    <fullName>Stopped</fullName>
                </value>
                <value>
                    <fullName>Interview Complete Missing Docs</fullName>
                </value>
                <value>
                    <fullName>Interview Complete - Overseas</fullName>
                </value>
                <value>
                    <fullName>Cleared Pending Docs</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Candidate Submission (Requires Verification)</fullName>
                    <isActive>false</isActive>
                    <label>Candidate Submission (Requires Verification)</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                    <isActive>false</isActive>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>More Required</fullName>
                    <isActive>false</isActive>
                    <label>More Required</label>
                </value>
                <value>
                    <fullName>No</fullName>
                    <isActive>false</isActive>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Non-Applicable</fullName>
                    <isActive>false</isActive>
                    <label>Non-Applicable</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Contact_Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Qualification</label>
        <referenceTo>TR1__Associated_Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Package</label>
        <referenceTo>TR1__Qualification_Package__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Qualification_Package__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Qualification Packages</relationshipLabel>
        <relationshipName>Qualification_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualification Package</label>
    <nameField>
        <displayFormat>QP{YY}{MM}-{0000}</displayFormat>
        <label>Qualification Package</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualification Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ComplianceDetailPageController.cls
public without sharing class ComplianceDetailPageController {
    public String conid {set;get;} 
    public List<WrapClass> listqualifications{set;get;}
    public Map<String,TR1__Associated_Qualification__c> mapasscs {set;get;}
    public Map<String,TR1__Qualification__c> qualificationsMap = New Map<String,TR1__Qualification__c>();
    public ComplianceDetailPageController(ApexPages.StandardController controller) {
    listqualifications = new List<WrapClass>();
        conid = (String)controller.getId();
          Contact objContact = new Contact();
        if(!Test.isRunningTest()){
        controller.addFields(new List<String>{'Pay_Type__c'});
        objContact = (Contact)controller.getRecord();
        }else{
            objContact = [select Pay_Type__c from contact where Id =:conid];
        }
        
        List< TR1__Qualification__c > listqlfns = [Select Id,Name, Description__c from TR1__Qualification__c order by Name ASC NUllS LAST ];
       // map pf qualification name to qualification
       for(TR1__Qualification__c q : listqlfns){
           if(!qualificationsMap.containskey(q.Name))
                qualificationsMap.put(q.Name,q);
       }
       
        List< TR1__Associated_Qualification__c > listasqlfns = [Select Id,Name, TR1__Status__c, TR1__Qualification__c, TR1__Qualification__r.Name, ComplianceStatus__c, Compliance_Status__c, TR1__Contact__c, TR1__Contact_Qualification__c,TR1__Contact_Qualification__r.Name,TR1__Qualification_Package__c from TR1__Associated_Qualification__c where TR1__Contact__c=:conid AND TR1__Qualification_Package__r.TR1__Name__c =: objContact.Pay_Type__c Order By Name ASC]; 

        mapasscs = new Map<String,TR1__Associated_Qualification__c>();
        if(listasqlfns.size()>0){
            for(TR1__Associated_Qualification__c eachassc : listasqlfns){
                mapasscs.put(eachassc.TR1__Qualification__r.Name,eachassc);
            }
        }
        for(TR1__Qualification__c eachqlfn : qualificationsMap.values()){
            if(mapasscs.containsKey(eachqlfn.Name)){
                listqualifications.add(new WrapClass(eachqlfn,mapasscs.get(eachqlfn.Name)));
            }/*else{
                listqualifications.add(new WrapClass(eachqlfn,new TR1__Associated_Qualification__c(TR1__Status__c='')));
            }*/
        }
        //system.debug('=====================listqualifications===='+listqualifications);
        
    }
    public class WrapClass{
        public TR1__Qualification__c qualfcn{set;get;}
        public TR1__Associated_Qualification__c asscqualfcn{set;get;}
        public WrapClass(TR1__Qualification__c qualfcn1,TR1__Associated_Qualification__c asscqualfcn1){
            qualfcn = qualfcn1;
            asscqualfcn = asscqualfcn1;
       }
    }
    
    public PageReference redirectToCompliance(){
        PageReference pr = null;
        if(conid!=null){
           pr = new PageReference('/apex/CompliancePage3?id='+conid); 
        }
        return pr;
    }
}