src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>All_Approver__c</fullName>
        <formula>TR1__Approver__c+&apos;;&apos;+TR1__Timesheet_Second_Approver__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>All Approver</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_Rate_1__c</fullName>
        <formula>TR1__Closing_Report__r.Maximum_Day_Charge_Rate__c</formula>
        <label>Charge Rate 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Rate_2__c</fullName>
        <formula>TR1__Closing_Report__r.Maximum_Half_Day_Charge_Rate__c</formula>
        <label>Charge Rate 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Rate_3__c</fullName>
        <formula>TR1__Closing_Report__r.Maximum_Hour_Charge_Rate__c</formula>
        <label>Charge Rate 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pay_Rate_1__c</fullName>
        <formula>TR1__Closing_Report__r.Maximum_Day_Pay_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pay Rate 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pay_Rate_2__c</fullName>
        <formula>TR1__Closing_Report__r.Maximum_Half_Day_Pay_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pay Rate 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Request_Quality_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Quality Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Approver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Timesheets (Timesheet Approver)</relationshipLabel>
        <relationshipName>Timesheets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Approvers_Notes__c</fullName>
        <inlineHelpText>Visible to approver and payroll.</inlineHelpText>
        <label>Approver Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TR1__Client_Name__c</fullName>
        <formula>TR1__Client__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Consultant_Name__c</fullName>
        <formula>TR1__Consultant__r.LastName &amp; &quot;, &quot; &amp;  TR1__Consultant__r.FirstName</formula>
        <label>Consultant Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Job_Order__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Changed By Payroll</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Unsubmitted</fullName>
                    <default>true</default>
                    <label>Unsubmitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Total_Hours__c</fullName>
        <formula>TR1__Total_Regular_Hours__c + TR1__Total_Overtime_Hours__c + TR1__Total_Double_Time_Hours__c + TR1__Total_Vacation_Hours__c + TR1__Total_Sick_Time_Hours__c + TR1__Total_Holiday_Hours__c + TR1__Total_Travel_Hours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Total_Regular_Hours__c</fullName>
        <label>Total Regular Hours</label>
        <summarizedField>TR1__Timesheet_Detail__c.TR1__Regular_Hours__c</summarizedField>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TR1__Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Teacher_Rating__c</fullName>
        <label>Weekly Teacher Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Excellent</fullName>
                </value>
                <value>
                    <fullName>Outstanding</fullName>
                </value>
                <value>
                    <fullName>Very Good</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Requires Improvement</fullName>
                </value>
                <value>
                    <fullName>Unsatisfactory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timesheet_Week__c</fullName>
        <description>IF(TR1__Week_Ending__c&gt;DATE(YEAR(TR1__Week_Ending__c),3,27), 
(TR1__Week_Ending__c-DATE(YEAR(TR1__Week_Ending__c),3,27))/7, 
37+(DATE(YEAR(TR1__</description>
        <formula>IF((CEILING(((TR1__Pay_Week_Ending__c-DATE(YEAR(TR1__Pay_Week_Ending__c),3,27)))/7))&lt;1,
53+(CEILING(((TR1__Pay_Week_Ending__c-DATE(YEAR(TR1__Pay_Week_Ending__c),3,27)))/7)),
(CEILING(((TR1__Pay_Week_Ending__c-DATE(YEAR(TR1__Pay_Week_Ending__c),3,27)))/7))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Timesheet Week</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Days__c</fullName>
        <label>Total Days</label>
        <summaryFilterItems>
            <field>TR1__Timesheet_Detail__c.DayShift__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Half_Days__c</fullName>
        <label>Total Half Days</label>
        <summaryFilterItems>
            <field>TR1__Timesheet_Detail__c.Half_Day__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>TR1__Timesheet_Detail__c.TR1__Timesheet__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YYYY}{MM}-{0}</displayFormat>
        <label>Timesheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Timesheet_Detail__c.object
<CustomObject>
    <fields>
        <fullName>DayShift__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Half_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Half Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TR1__Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TR1__Day__c</fullName>
        <label>Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
                <value>
                    <fullName>Sunday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Double_Time_Hours__c</fullName>
        <label>Double Time Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Expenses__c</fullName>
        <label>Expenses</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TR1__Overtime_Hours__c</fullName>
        <label>Overtime Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Regular_Hours__c</fullName>
        <label>Regular Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Sick_Time_Hours__c</fullName>
        <label>Sick Time Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TR1__Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>TR1__Timesheet__c</referenceTo>
        <relationshipLabel>Timesheet Details</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Vacation_Hours__c</fullName>
        <label>Vacation Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Timesheet Detail</label>
    <nameField>
        <displayFormat>TS-{MM}{DD}{YY}-{0}</displayFormat>
        <label>Timesheet Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ts_TimesheetPrintPdfController.cls
public without sharing class ts_TimesheetPrintPdfController {


    public String[] timesheetIds                           {get;set;}
    public transient List<TR1__Timesheet__c> timesheetList                      {get;set;}
    public transient List<TimesheetPrintWrapper> TimesheetPrintWrapperList          {get;set;}
    public integer LastPdf {get;set;}
    public Boolean isClient {get;set;}
    public User loggedInUser ;
    public Contact objContactPage {get;set; }

    public integer getPageCount(){
        return TimesheetPrintWrapperList.size();
    }

    public ts_TimesheetPrintPdfController() {

        TimesheetPrintWrapperList = new List<TimesheetPrintWrapper> ();
        // system.debug('TimesheetList: '+System.currentPageReference().getParameters().get('timesheetIds'));
        // String[] timesheetIds = ((String)System.currentPageReference().getParameters().get('timesheetIds')).split(';');
        loggedInUser = [Select ContactId from User where Id =: '0050C000005eNFbQAM' limit 1];
        if(!test.isrunningtest()){
            objContactPage = [Select Community_Contact_Type__c,Name from Contact where Id =:loggedInUser.ContactId limit 1];


            if(objContactPage.Community_Contact_Type__c == 'Candidate' || objContactPage.Community_Contact_Type__c == 'C And C'  ){
                isClient = false;
            }else if(objContactPage.Community_Contact_Type__c == 'Client'){
                isClient = true;
            }
        }

        // timesheetList = RC_AccessController.getTimesheetsByIds(timesheetIds);
        String strQueryTS = 'SELECT Id, Name, TR1__Week_Ending__c, Timesheet_Week__c, TR1__Status__c,TR1__Consultant_Name__c , TR1__Job_Order__r.TR1__Job_Title__c, Pay_Rate_1__c, TR1__Total_Hours__c, Pay_Rate_2__c, TR1__Client_Name__c, TR1__Approver__r.name, ';
        strQueryTS += 'Charge_Rate_1__c, Charge_Rate_2__c, Charge_Rate_3__c, ';
        strQueryTS += 'TR1__Total_Regular_Hours__c, Total_Days__c, Total_Half_Days__c, ';
        strQueryTS += 'Teacher_Rating__c, Request_Quality_Call__c, TR1__Approvers_Notes__c, ';
        strQueryTS += 'All_Approver__c, TR1__Consultant__c, ';
        strQueryTS += '(Select TR1__Date__c, TR1__Day__c, TR1__Double_Time_Hours__c, Id,DayShift__c,Half_Day__c, TR1__Overtime_Hours__c, TR1__Regular_Hours__c, TR1__Sick_Time_Hours__c,TR1__Timesheet__c, TR1__Vacation_Hours__c, TR1__Expenses__c, Start_Time__c,End_Time__c From TR1__Timecards__r order by TR1__date__c asc)  ';
        strQueryTS += ' from TR1__Timesheet__c where Id = \'a0y0C000006iUzMQAU\'';

        String whereClauseTSD = ' AND (All_Approver__c like \'%'+ ((String)objContactPage.Id).left(15) +'%\' OR TR1__Consultant__c = \'' + loggedInUser.ContactId + '\') ';
        
        timesheetList = Database.query(strQueryTS+whereClauseTSD);
        
        calculatehours();
    }

    public void calculatehours(){
        integer lstCount = 0;
        for(TR1__Timesheet__c timesheet : timesheetList) {
            TimesheetPrintWrapper wrapper = new TimesheetPrintWrapper(timesheet , ++lstCount)  ;
            for(TR1__Timesheet_Detail__c td : timesheet.TR1__Timecards__r){
                if(td.TR1__Double_Time_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Double_Time_Hours__c;
                if(td.TR1__Expenses__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Expenses__c;
                if(td.TR1__Overtime_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Overtime_Hours__c;
                if(td.TR1__Regular_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Regular_Hours__c;
                if(td.TR1__Sick_Time_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Sick_Time_Hours__c;
                if(td.TR1__Vacation_Hours__c != null)
                    wrapper.totalHours = wrapper.totalHours + td.TR1__Vacation_Hours__c;
            }
            TimesheetPrintWrapperList.add(wrapper);
        }
        LastPdf = TimesheetPrintWrapperList.size();
    }

    public class TimesheetPrintWrapper {

        public Double totalHours               {get;set;}
        public integer index                 {get;set;}
        public TR1__Timesheet__c timesheet      {get;set;}

        public TimesheetPrintWrapper(TR1__Timesheet__c timesheet,integer index) {
            this.timesheet =  timesheet;
            totalHours = 0;
            this.index = index;

        }
    }
}