src/objects/TR1__Associated_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>NCTL_Checked_Date__c</fullName>
        <label>NCTL Checked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NCTL_Number__c</fullName>
        <label>NCTL Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NCTL_Status__c</fullName>
        <label>NCTL Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Registered</fullName>
                </value>
                <value>
                    <fullName>Provisionally Registered</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Full Qual. Check</fullName>
                    <isActive>false</isActive>
                    <label>Full Qual. Check</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Provisional Trainee</fullName>
                    <isActive>false</isActive>
                    <label>Provisional Trainee</label>
                </value>
                <value>
                    <fullName>Waiver signed</fullName>
                    <isActive>false</isActive>
                    <label>Waiver signed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <label>Qualifications</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Qualification_Type2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>B.Ed + State Teaching Certification</fullName>
                </value>
                <value>
                    <fullName>BA + Teacher Training</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Arts / Bachelor of Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Arts/ Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Early Childhood Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education/ Bachelor of Science (Secondary)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education (Primary)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Education (Special Education)</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Health, Sport and Physical Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Primary Education</fullName>
                </value>
                <value>
                    <fullName>Bachelor of Science and Education in Secondary Teaching</fullName>
                </value>
                <value>
                    <fullName>Bachelors Degree</fullName>
                </value>
                <value>
                    <fullName>BA or BSc + Teacher Training</fullName>
                </value>
                <value>
                    <fullName>BA with QTS</fullName>
                </value>
                <value>
                    <fullName>B ED</fullName>
                </value>
                <value>
                    <fullName>BED with QTS</fullName>
                </value>
                <value>
                    <fullName>BSC with QTS</fullName>
                </value>
                <value>
                    <fullName>BTEC</fullName>
                </value>
                <value>
                    <fullName>CACHE L1</fullName>
                </value>
                <value>
                    <fullName>CACHE L2</fullName>
                </value>
                <value>
                    <fullName>CACHE L3</fullName>
                </value>
                <value>
                    <fullName>CERT ED FE</fullName>
                </value>
                <value>
                    <fullName>City and Guilds 7307</fullName>
                </value>
                <value>
                    <fullName>CTLLS</fullName>
                </value>
                <value>
                    <fullName>Degree</fullName>
                </value>
                <value>
                    <fullName>Degree in Curriculum Subject</fullName>
                </value>
                <value>
                    <fullName>Dip In Childcare and Education</fullName>
                </value>
                <value>
                    <fullName>Dip In Play Work</fullName>
                </value>
                <value>
                    <fullName>Dip in Support Work in Schools</fullName>
                </value>
                <value>
                    <fullName>Diploma in Education &amp; Training</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>TR1__Qualification__c</referenceTo>
        <relationshipLabel>Associated Qualifications</relationshipLabel>
        <relationshipName>Associated_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>TR1__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associated Qualification</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Associated Qualification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Qualifications</pluralLabel>
    <recordTypes>
        <fullName>CV</fullName>
        <active>false</active>
        <label>CV</label>
    </recordTypes>
    <recordTypes>
        <fullName>ID</fullName>
        <active>false</active>
        <label>ID</label>
    </recordTypes>
    <recordTypes>
        <fullName>Medical</fullName>
        <active>false</active>
        <label>Medical</label>
    </recordTypes>
    <recordTypes>
        <fullName>Photo</fullName>
        <active>false</active>
        <label>Photo</label>
    </recordTypes>
    <recordTypes>
        <fullName>Qualifications</fullName>
        <active>false</active>
        <label>Qualifications</label>
    </recordTypes>
    <recordTypes>
        <fullName>References</fullName>
        <active>false</active>
        <label>References</label>
    </recordTypes>
    <recordTypes>
        <fullName>Safeguarding</fullName>
        <active>false</active>
        <label>Safeguarding</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Qualification__c.object
<CustomObject>
    <label>Qualification</label>
    <nameField>
        <label>Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_AssociateQualificationTrigger.cls
@isTest
public class Test_AssociateQualificationTrigger {
    
    @isTest public static void newRecord(){
      Test.startTest();   
    Contact con = new Contact();
    con.LastName = 'Demo';
    con.Compliance_Owner__c = UserInfo.getUserId();
    insert con;
    
    List<TR1__Qualification__c> quaList = new List<TR1__Qualification__c>();
    quaList.add(new TR1__Qualification__c(Name = 'Barred List'));
    quaList.add(new TR1__Qualification__c(Name = 'CV'));
    quaList.add(new TR1__Qualification__c(Name = 'DBS'));
    quaList.add(new TR1__Qualification__c(Name = 'Disqualification by Association'));
    quaList.add(new TR1__Qualification__c(Name = 'Early Years Qualifications'));
    quaList.add(new TR1__Qualification__c(Name = 'Emergency Contact'));
    quaList.add(new TR1__Qualification__c(Name = 'Face to Face Interview'));
    quaList.add(new TR1__Qualification__c(Name = 'Id'));
    quaList.add(new TR1__Qualification__c(Name = 'Medical'));
    quaList.add(new TR1__Qualification__c(Name = 'Overseas DBS Check'));
    quaList.add(new TR1__Qualification__c(Name = 'Overseas Police Check'));
    quaList.add(new TR1__Qualification__c(Name = 'Overseas Teacher Qualifications'));
    quaList.add(new TR1__Qualification__c(Name = 'passport'));
    quaList.add(new TR1__Qualification__c(Name = 'Perm DBS'));
    quaList.add(new TR1__Qualification__c(Name = 'Perm Qualification'));
    quaList.add(new TR1__Qualification__c(Name = 'Photo'));
    quaList.add(new TR1__Qualification__c(Name = 'Post 16 Qualifications'));
    quaList.add(new TR1__Qualification__c(Name = 'References'));
    quaList.add(new TR1__Qualification__c(Name = 'Right to Work'));
    quaList.add(new TR1__Qualification__c(Name = 'Safeguarding'));
    quaList.add(new TR1__Qualification__c(Name = 'Teacher Qualification'));
    quaList.add(new TR1__Qualification__c(Name = 'Terms and Registration Forms'));

    insert quaList;

    List<TR1__Associated_Qualification__c> assQuaList = new List<TR1__Associated_Qualification__c>();
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[0].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[1].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[2].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[3].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[4].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[5].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[6].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[7].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[8].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[9].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[10].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[11].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[12].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[13].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[14].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[15].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[16].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[17].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[18].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[19].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[20].Id));
    assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Requested',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[21].Id));
    //assQuaList.add(new TR1__Associated_Qualification__c(TR1__Status__c = 'Rejected',TR1__Contact__c = con.Id,TR1__Qualification__c = quaList[17].Id));

    insert assQuaList;

    List<TR1__Associated_Qualification__c> softUpdate = new List<TR1__Associated_Qualification__c>();
    //softUpdate.add(new TR1__Associated_Qualification__c(Id=assQuaList[0].Id ,TR1__Status__c = 'Submitted'));
    softUpdate.add(new TR1__Associated_Qualification__c(Id=assQuaList[1].Id ,TR1__Status__c = 'Expired'));
    //softUpdate.add(new TR1__Associated_Qualification__c(Id=assQuaList[2].Id , TR1__Status__c = 'In Progress'));
    softUpdate.add(new TR1__Associated_Qualification__c(Id=assQuaList[3].Id ,TR1__Status__c = 'Rejected'));
    //softUpdate.add(new TR1__Associated_Qualification__c(Id=assQuaList[17].Id ,Qualification_Type__c = 'BTEC',NCTL_Status__c = 'Provisionally Registered',NCTL_Checked_Date__c = system.today(),NCTL_Number__c = '1234', TR1__Status__c = 'Active'));

    update softUpdate;
   
    Test.stopTest();
      
    }
    @isTest
    public  static void newRecord1(){
        Contact con = new Contact();
        con.LastName = 'Demo';
        con.Compliance_Owner__c = UserInfo.getUserId();
        insert con;
        TR1__Qualification__c qul = new TR1__Qualification__c();
        qul.Name='Barred List';
        insert qul;
        List<TR1__Associated_Qualification__c> asstList = new List<TR1__Associated_Qualification__c>();
        TR1__Associated_Qualification__c asst= new TR1__Associated_Qualification__c();
        asst.TR1__Status__c='Requested';
        asst.TR1__Contact__c = con.Id;
        asst.TR1__Qualification__c = qul.Id;
        asstList.add(asst);
        insert asstList;
        delete asstList;
    }
}