src/objects/TR1__Closing_Report__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <formula>TR1__Job__r.TR1__Contact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports (Hiring Manager)</relationshipLabel>
        <relationshipName>Closing_Reports2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <formula>TR1__Job__r.TR1__Contact__r.FirstName &amp; &quot; &quot; &amp;  TR1__Job__r.TR1__Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TR1__Job__c</fullName>
        <label>Job</label>
        <referenceTo>TR1__Job__c</referenceTo>
        <relationshipName>Closes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TR1__Person_Placed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Placed</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Closing Reports</relationshipLabel>
        <relationshipName>Closes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Closing Report</label>
    <nameField>
        <displayFormat>CL-{MM}{DD}{YYYY}-{0}</displayFormat>
        <label>Closing Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closing Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TR1__Job__c.object
<CustomObject>
    <fields>
        <fullName>TR1__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendConfirmationLetter.cls
public class SendConfirmationLetter{
    public static Boolean sendConfirmationLetterFlag = False;
    @future(callout=true)
    public static void sendVF(set<Id> crIdSet){
        List<TR1__Closing_Report__c> crList = [Select Name, Id, Contact_Email__c,Hiring_Manager__r.Email,TR1__Person_Placed__c,TR1__Person_Placed__r.Name,TR1__Contact__c,TR1__Job__r.Owner.Email,TR1__Job__r.Owner.Name from TR1__Closing_Report__c where Id IN :crIdSet ];
        if(crList.size() > 0){
            for(TR1__Closing_Report__c cr : crList){
                if(cr.Hiring_Manager__r.Email != null){
                    PageReference PageRef = Page.ConfirmationLetterPDF_V2;
                    pageRef.getParameters().put('Id',cr.Id);
                    Blob b;
                    if(!Test.isRunningTest()){
                        b = PageRef.getContentAsPDF();
                    }
                    else{
                        b= blob.valueOf('Test Data');
                    }
                    
                    Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
                    attachment.setFileName('Confirmation Letter.pdf');
                    attachment.setBody(b);
                    
                    List<string> sendTo = new List<string>{cr.Hiring_Manager__r.Email};
                        String vacancyOwnerEmail  = cr.TR1__Job__r.Owner.Email;
                    List<string> sendCC = new List<string>{vacancyOwnerEmail};
                        String vacancyOwnerName = cr.TR1__Job__r.Owner.Name;
                    
                    Id templateId = [SELECT Id,Name,HtmlValue,Body FROM EmailTemplate WHERE DeveloperName = 'Client_Confirmation_of_Checks'].Id;
                    Id orgEmailID = [SELECT Id,DisplayName FROM OrgWideEmailAddress WHERE DisplayName='Payroll Team'].Id;
                    
                    String CandidateName = String.isNotBlank(cr.TR1__Person_Placed__r.Name) ? cr.TR1__Person_Placed__r.Name : 'Candidate';
                    //String Body = 'Hi, \n\nPlease find attched confirmation Letter of '+ CandidateName +'.\n\nThanks, \nSupply Desk..';
                    
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    email = Messaging.renderStoredEmailTemplate(templateId, cr.Hiring_Manager__c, cr.Id);                    
                    email.setToAddresses(sendTo); 
                    email.setCcAddresses(sendCC); 
                    //email.setOrgWideEmailAddressId(orgEmailID);
                    email.setReplyTo(vacancyOwnerEmail);
                    email.setSenderDisplayName(vacancyOwnerName);
                    email.setFileAttachments(new Messaging.EmailFileAttachment[] {attachment});
                    
                    if(!Test.isRunningTest())
                        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});  
                }
            }
        }
    }
}